import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-001",
  title: "사건 대기열",
  route: "/internal/cases",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "views",
      title: "업무 대기열",
      component: "DataCollection",
      purpose: "investigation/editorial/review/publish.",
      test_id: "cas_001__section__views",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "state/owner/blocker/risk.",
      test_id: "cas_001__section__filters",
    },
    {
      order: 3,
      id: "table",
      title: "사건",
      component: "StructuredContentSection",
      purpose: "question·state·next task·due.",
      test_id: "cas_001__section__table",
    },
    {
      order: 4,
      id: "assignment",
      title: "배정",
      component: "StructuredContentSection",
      purpose: "handoff.",
      test_id: "cas_001__section__assignment",
    },
  ],
  actions: [
    {
      id: "open-case",
      label: "사건 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "assign",
      label: "담당자 지정",
      capability: "cases.assign",
      operation_id: "assignCase",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "save-view",
      label: "보기 저장",
      capability: "none",
      operation_id: "createSavedView",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listInternalCases",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-internal-cases",
      blocking: true,
      response_schema: "InternalCasesPage",
    },
    {
      operation_id: "assignCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/assign-case",
      blocking: false,
      response_schema: "assignCaseReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
