import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-034",
  title: "오류·시스템 상태",
  route: "/{systemPath}",
  archetype: "AUTH_SYSTEM",
  sections: [
    {
      order: 1,
      id: "message",
      title: "상황",
      component: "StructuredContentSection",
      purpose: "민감정보를 제외한 오류·점검·장애 현황.",
      test_id: "pub_034__section__message",
    },
    {
      order: 2,
      id: "impact",
      title: "영향",
      component: "CoverageStatement",
      purpose: "read/write/freshness.",
      test_id: "pub_034__section__impact",
    },
    {
      order: 3,
      id: "actions",
      title: "다음 행동",
      component: "StatusAndRevisionHeader",
      purpose: "재시도·홈·status·contact.",
      test_id: "pub_034__section__actions",
    },
    {
      order: 4,
      id: "reference",
      title: "참조",
      component: "StructuredContentSection",
      purpose: "trace ID.",
      test_id: "pub_034__section__reference",
    },
  ],
  actions: [
    {
      id: "retry",
      label: "다시 시도",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "go-home",
      label: "홈으로",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-status",
      label: "상태 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getPublicSystemStatus",
      api: "public-api",
      method: "GET",
      path: "/v1/system/status",
      blocking: false,
      response_schema: "PublicSystemStatusResponse",
    },
  ],
} as const satisfies ScreenViewModel;
