import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-012",
  title: "계약 상세",
  route: "/contracts/{contractId}",
  archetype: "EVIDENCE_LANDING",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "계약 identity",
      component: "StatusAndRevisionHeader",
      purpose: "source ID·기관·업체·상태.",
      test_id: "pub_012__section__identity",
    },
    {
      order: 2,
      id: "terms",
      title: "계약 조건",
      component: "StructuredContentSection",
      purpose: "금액·기간·방식·line items.",
      test_id: "pub_012__section__terms",
    },
    {
      order: 3,
      id: "changes",
      title: "변경 계약",
      component: "StructuredContentSection",
      purpose: "금액·기간 변경.",
      test_id: "pub_012__section__changes",
    },
    {
      order: 4,
      id: "procurement",
      title: "입찰·낙찰 연결",
      component: "StructuredContentSection",
      purpose: "가능한 source 연결.",
      test_id: "pub_012__section__procurement",
    },
    {
      order: 5,
      id: "provenance",
      title: "필드 provenance",
      component: "StructuredContentSection",
      purpose: "raw locator·parser version.",
      test_id: "pub_012__section__provenance",
    },
    {
      order: 6,
      id: "related",
      title: "관련 공개 사건",
      component: "DataCollection",
      purpose: "내부 signal count는 숨김.",
      test_id: "pub_012__section__related",
    },
    {
      order: 7,
      id: "limitations",
      title: "데이터 한계",
      component: "StructuredContentSection",
      purpose: "누락·bundle·unit.",
      test_id: "pub_012__section__limitations",
    },
  ],
  actions: [
    {
      id: "open-source",
      label: "원문 보기",
      capability: "none",
      interaction_kind: "EXTERNAL_LINK",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-case",
      label: "관련 사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "copy-contract-id",
      label: "계약 ID 복사",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getContract",
      api: "public-api",
      method: "GET",
      path: "/v1/contracts/{contractId}",
      blocking: true,
      response_schema: "ContractResponse",
    },
    {
      operation_id: "listContractChanges",
      api: "public-api",
      method: "GET",
      path: "/v1/contracts/{contractId}/changes",
      blocking: true,
      response_schema: "ContractChangesPage",
    },
  ],
} as const satisfies ScreenViewModel;
