import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-011",
  title: "Agent 실행 상세",
  route: "/internal/cases/{caseId}/agent-runs/{runId}",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "실행 identity",
      component: "StructuredContentSection",
      purpose: "purpose·version·timestamps.",
      test_id: "cas_011__section__identity",
    },
    {
      order: 2,
      id: "inputs",
      title: "입력",
      component: "EvidenceLedger",
      purpose: "evidence IDs·hash.",
      test_id: "cas_011__section__inputs",
    },
    {
      order: 3,
      id: "model",
      title: "모델·policy",
      component: "StructuredContentSection",
      purpose: "provider·prompt version.",
      test_id: "cas_011__section__model",
    },
    {
      order: 4,
      id: "output",
      title: "structured output",
      component: "StructuredContentSection",
      purpose: "validation.",
      test_id: "cas_011__section__output",
    },
    {
      order: 5,
      id: "citations",
      title: "citation",
      component: "StructuredContentSection",
      purpose: "source 존재.",
      test_id: "cas_011__section__citations",
    },
    {
      order: 6,
      id: "safety",
      title: "safety",
      component: "StructuredContentSection",
      purpose: "injection/PII.",
      test_id: "cas_011__section__safety",
    },
    {
      order: 7,
      id: "decisions",
      title: "사람 결정",
      component: "DecisionReviewPanel",
      purpose: "accepted/rejected.",
      test_id: "cas_011__section__decisions",
    },
    {
      order: 8,
      id: "cost",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "tokens/cost.",
      test_id: "cas_011__section__cost",
    },
  ],
  actions: [
    {
      id: "accept-suggestion",
      label: "제안 채택",
      capability: "cases.investigate",
      operation_id: "acceptAgentSuggestion",
      guard: "human verification",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "reject-suggestion",
      label: "제안 거절",
      capability: "cases.investigate",
      operation_id: "rejectAgentSuggestion",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "rerun",
      label: "새 버전으로 다시 실행",
      capability: "cases.investigate",
      operation_id: "startAgentRun",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getAgentRun",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-agent-run",
      blocking: true,
      response_schema: "AgentRunResponse",
    },
    {
      operation_id: "acceptAgentSuggestion",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/accept-agent-suggestion",
      blocking: false,
      response_schema: "acceptAgentSuggestionReceipt",
    },
    {
      operation_id: "rejectAgentSuggestion",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/reject-agent-suggestion",
      blocking: false,
      response_schema: "rejectAgentSuggestionReceipt",
    },
    {
      operation_id: "startAgentRun",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/start-agent-run",
      blocking: false,
      response_schema: "startAgentRunReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
