import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-017",
  title: "데이터 출처 상세",
  route: "/sources/{sourceId}",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "출처 설명",
      component: "StructuredContentSection",
      purpose: "출처 운영 기관·공식 접근 경로.",
      test_id: "pub_017__section__identity",
    },
    {
      order: 2,
      id: "freshness",
      title: "수집 상태",
      component: "StatusAndRevisionHeader",
      purpose: "last success·lag·incident.",
      test_id: "pub_017__section__freshness",
    },
    {
      order: 3,
      id: "coverage",
      title: "범위",
      component: "CoverageStatement",
      purpose: "기간·기관·record.",
      test_id: "pub_017__section__coverage",
    },
    {
      order: 4,
      id: "schema",
      title: "데이터 구조",
      component: "RevisionTimeline",
      purpose: "현재 version·변경 이력.",
      test_id: "pub_017__section__schema",
    },
    {
      order: 5,
      id: "quality",
      title: "알려진 품질 이슈",
      component: "StructuredContentSection",
      purpose: "누락·중복·형식.",
      test_id: "pub_017__section__quality",
    },
    {
      order: 6,
      id: "terms",
      title: "이용 조건",
      component: "StructuredContentSection",
      purpose: "redistribution.",
      test_id: "pub_017__section__terms",
    },
    {
      order: 7,
      id: "impact",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "관련 공개 데이터/규칙.",
      test_id: "pub_017__section__impact",
    },
  ],
  actions: [
    {
      id: "view-official",
      label: "공식 출처 열기",
      capability: "none",
      interaction_kind: "EXTERNAL_LINK",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-related-rules",
      label: "관련 규칙",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getSource",
      api: "public-api",
      method: "GET",
      path: "/v1/sources/{sourceId}",
      blocking: true,
      response_schema: "SourceResponse",
    },
  ],
} as const satisfies ScreenViewModel;
