import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-004",
  title: "근거",
  route: "/internal/cases/{caseId}/evidence",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "matrix",
      title: "evidence matrix",
      component: "EvidenceLedger",
      purpose: "hypothesis/claim 관계.",
      test_id: "cas_004__section__matrix",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "type/status/access.",
      test_id: "cas_004__section__filters",
    },
    {
      order: 3,
      id: "list",
      title: "근거 목록",
      component: "EvidenceLedger",
      purpose: "source·locator·verification.",
      test_id: "cas_004__section__list",
    },
    {
      order: 4,
      id: "gaps",
      title: "근거 gap",
      component: "EvidenceLedger",
      purpose: "unresolved questions.",
      test_id: "cas_004__section__gaps",
    },
  ],
  actions: [
    {
      id: "add-evidence",
      label: "근거 추가",
      capability: "evidence.create",
      operation_id: "addEvidence",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-evidence",
      label: "근거 검토",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "link",
      label: "claim/가설 연결",
      capability: "evidence.create",
      operation_id: "linkEvidence",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseEvidence",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-evidence",
      blocking: true,
      response_schema: "CaseEvidencePage",
    },
    {
      operation_id: "addEvidence",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/add-evidence",
      blocking: true,
      response_schema: "addEvidenceReceipt",
    },
    {
      operation_id: "linkEvidence",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/link-evidence",
      blocking: true,
      response_schema: "linkEvidenceReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
