import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "INT-002",
  title: "내 작업",
  route: "/internal/my-work",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "views",
      title: "보기",
      component: "StructuredContentSection",
      purpose: "today/overdue/blocked.",
      test_id: "int_002__section__views",
    },
    {
      order: 2,
      id: "tasks",
      title: "작업",
      component: "StructuredContentSection",
      purpose: "type·object·reason·due.",
      test_id: "int_002__section__tasks",
    },
    {
      order: 3,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "role/type/state.",
      test_id: "int_002__section__filters",
    },
    {
      order: 4,
      id: "handoff",
      title: "인계",
      component: "StructuredContentSection",
      purpose: "assignment history.",
      test_id: "int_002__section__handoff",
    },
  ],
  actions: [
    {
      id: "open-task",
      label: "작업 수행",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "reassign",
      label: "재배정",
      capability: "cases.assign",
      operation_id: "reassignTask",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "save-view",
      label: "보기 저장",
      capability: "none",
      operation_id: "createSavedView",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "create-action-proposal",
      label: "외부 전달 제안 만들기",
      capability: "actions.propose",
      operation_id: "createActionProposal",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "preview-action-draft",
      label: "전달 내용 미리보기",
      capability: "actions.propose",
      operation_id: "previewActionDraft",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "submit-action-review",
      label: "승인 검토 요청",
      capability: "actions.propose",
      operation_id: "submitActionForReview",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "submit-action-decision",
      label: "전달 승인·반려 결정",
      capability: "actions.review",
      operation_id: "submitActionDecision",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listMyTasks",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-my-tasks",
      blocking: true,
      response_schema: "MyTasksPage",
    },
    {
      operation_id: "reassignTask",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/reassign-task",
      blocking: true,
      response_schema: "reassignTaskReceipt",
    },
    {
      operation_id: "listActionApprovalQueue",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/action-proposals",
      blocking: true,
      response_schema: "ActionApprovalQueuePageV1",
    },
    {
      operation_id: "getActionExecutionReceipt",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/action-executions/{executionId}/receipt",
      blocking: true,
      response_schema: "ActionExecutionReceiptChainV1",
    },
    {
      operation_id: "getActionProposal",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/action-proposals/{proposalId}",
      blocking: true,
      response_schema: "ActionProposalDetailV1",
    },
  ],
} as const satisfies ScreenViewModel;
