import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-001",
  title: "홈",
  route: "/",
  archetype: "EVIDENCE_LANDING",
  sections: [
    {
      order: 1,
      id: "mission",
      title: "서비스 정의와 한계",
      component: "StructuredContentSection",
      purpose: "이상 징후와 비리 확정을 분리한다.",
      test_id: "pub_001__section__mission",
    },
    {
      order: 2,
      id: "search",
      title: "통합 검색",
      component: "UnifiedSearch",
      purpose: "기관·업체·계약·사건 검색 진입점이다.",
      test_id: "pub_001__section__search",
    },
    {
      order: 3,
      id: "recent",
      title: "최근 공개 기록",
      component: "StatusAndRevisionHeader",
      purpose: "상태가 균형 잡힌 최신 기록을 보여준다.",
      test_id: "pub_001__section__recent",
    },
    {
      order: 4,
      id: "corrections",
      title: "최근 설명·정정·철회",
      component: "RevisionAndCorrectionPanel",
      purpose: "제품이 오류와 해소 사례를 숨기지 않음을 보여준다.",
      test_id: "pub_001__section__corrections",
    },
    {
      order: 5,
      id: "coverage",
      title: "데이터 범위와 최신성",
      component: "CoverageStatement",
      purpose: "포함 source와 지연을 요약한다.",
      test_id: "pub_001__section__coverage",
    },
    {
      order: 6,
      id: "method",
      title: "방법론",
      component: "LongFormArticle",
      purpose: "탐지 방식과 한계를 설명한다.",
      test_id: "pub_001__section__method",
    },
  ],
  actions: [
    {
      id: "search",
      label: "검색",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "browse-cases",
      label: "사례 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe",
      label: "업데이트 구독",
      capability: "none",
      operation_id: "createSubscription",
      preset: {
        scope_type: "CORRECTIONS",
      },
      interaction_kind: "NAVIGATION",
      assurance_level: "ANONYMOUS_PROOF",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listPublicCases",
      api: "public-api",
      method: "GET",
      path: "/v1/cases",
      blocking: true,
      response_schema: "PublicCasesPage",
    },
    {
      operation_id: "listCorrections",
      api: "public-api",
      method: "GET",
      path: "/v1/corrections",
      blocking: true,
      response_schema: "CorrectionsPage",
    },
    {
      operation_id: "listSourceStatus",
      api: "public-api",
      method: "GET",
      path: "/v1/sources/status",
      blocking: true,
      response_schema: "SourceStatusPage",
    },
    {
      operation_id: "searchPublicRecords",
      api: "public-api",
      method: "GET",
      path: "/v1/search",
      blocking: true,
      response_schema: "PublicRecordsSearchResultPage",
    },
  ],
} as const satisfies ScreenViewModel;
