import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-007",
  title: "조사 가설",
  route: "/internal/cases/{caseId}/hypotheses",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "board",
      title: "가설 board",
      component: "StructuredContentSection",
      purpose: "OPEN/SUPPORTED/CONTRADICTED/RESOLVED.",
      test_id: "cas_007__section__board",
    },
    {
      order: 2,
      id: "matrix",
      title: "근거 관계",
      component: "EvidenceLedger",
      purpose: "support/contradict.",
      test_id: "cas_007__section__matrix",
    },
    {
      order: 3,
      id: "questions",
      title: "미확인 질문",
      component: "KnownUnknownResponse",
      purpose: "owner·next action.",
      test_id: "cas_007__section__questions",
    },
  ],
  actions: [
    {
      id: "add-hypothesis",
      label: "가설 추가",
      capability: "cases.investigate",
      operation_id: "createHypothesis",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "update-status",
      label: "상태 변경",
      capability: "cases.investigate",
      operation_id: "updateHypothesis",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "link-evidence",
      label: "근거 연결",
      capability: "evidence.create",
      operation_id: "linkEvidence",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseHypotheses",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-hypotheses",
      blocking: true,
      response_schema: "CaseHypothesesPage",
    },
    {
      operation_id: "createHypothesis",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-hypothesis",
      blocking: true,
      response_schema: "createHypothesisReceipt",
    },
    {
      operation_id: "updateHypothesis",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/update-hypothesis",
      blocking: true,
      response_schema: "updateHypothesisReceipt",
    },
    {
      operation_id: "linkEvidence",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/link-evidence",
      blocking: false,
      response_schema: "linkEvidenceReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
