import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-001",
  title: "운영 Overview",
  route: "/internal/operations",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "incidents",
      title: "active incident",
      component: "OperationsStatusPanel",
      purpose: "영향·owner·started.",
      test_id: "ops_001__section__incidents",
    },
    {
      order: 2,
      id: "services",
      title: "서비스 health",
      component: "OperationsStatusPanel",
      purpose: "API/web/worker.",
      test_id: "ops_001__section__services",
    },
    {
      order: 3,
      id: "pipelines",
      title: "pipeline",
      component: "StructuredContentSection",
      purpose: "ingest/analysis/projection.",
      test_id: "ops_001__section__pipelines",
    },
    {
      order: 4,
      id: "queues",
      title: "queue·DLQ",
      component: "DataCollection",
      purpose: "age/backlog.",
      test_id: "ops_001__section__queues",
    },
    {
      order: 5,
      id: "cost",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "budget envelope.",
      test_id: "ops_001__section__cost",
    },
    {
      order: 6,
      id: "security",
      title: "보안",
      component: "StructuredContentSection",
      purpose: "kill/break-glass.",
      test_id: "ops_001__section__security",
    },
    {
      order: 7,
      id: "slo",
      title: "SLO",
      component: "StructuredContentSection",
      purpose: "trend·error budget.",
      test_id: "ops_001__section__slo",
    },
  ],
  actions: [
    {
      id: "open-incident",
      label: "incident 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-jobs",
      label: "작업 큐",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-kill",
      label: "Kill switch",
      capability: "kill_switch.execute",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getOperationsOverview",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-operations-overview",
      blocking: true,
      response_schema: "OperationsOverviewResponse",
    },
  ],
} as const satisfies ScreenViewModel;
