import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "INT-001",
  title: "운영 대시보드",
  route: "/internal/dashboard",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "critical",
      title: "긴급 차단 요인",
      component: "RevisionAndCorrectionPanel",
      purpose: "publication/correction/security.",
      test_id: "int_001__section__critical",
    },
    {
      order: 2,
      id: "my-work",
      title: "내 작업",
      component: "StructuredContentSection",
      purpose: "due·SLA.",
      test_id: "int_001__section__my-work",
    },
    {
      order: 3,
      id: "incidents",
      title: "출처·운영 장애",
      component: "OperationsStatusPanel",
      purpose: "영향.",
      test_id: "int_001__section__incidents",
    },
    {
      order: 4,
      id: "queues",
      title: "대기열 상태",
      component: "KnownUnknownResponse",
      purpose: "review/response/job.",
      test_id: "int_001__section__queues",
    },
    {
      order: 5,
      id: "cost",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "budget risk.",
      test_id: "int_001__section__cost",
    },
  ],
  actions: [
    {
      id: "open-task",
      label: "작업 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-incident",
      label: "인시던트 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getInternalDashboard",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-internal-dashboard",
      blocking: true,
      response_schema: "InternalDashboardResponse",
    },
  ],
} as const satisfies ScreenViewModel;
