import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-004",
  title: "사건 상세",
  route: "/cases/{caseSlug}",
  archetype: "EVIDENCE_LANDING",
  sections: [
    {
      order: 1,
      id: "status",
      title: "상태·개정·최신성",
      component: "StatusAndRevisionHeader",
      purpose: "최신 공개 상태·정정·개정 기준.",
      test_id: "pub_004__section__status",
    },
    {
      order: 2,
      id: "known",
      title: "확인된 사실",
      component: "KnownUnknownResponse",
      purpose: "source에 연결된 사실과 계산.",
      test_id: "pub_004__section__known",
    },
    {
      order: 3,
      id: "unknown",
      title: "중요한 미확인",
      component: "KnownUnknownResponse",
      purpose: "판단을 바꿀 수 있는 누락 정보.",
      test_id: "pub_004__section__unknown",
    },
    {
      order: 4,
      id: "response",
      title: "기관·업체 소명",
      component: "StatusAndRevisionHeader",
      purpose: "응답 상태·제출일·검증 범위.",
      test_id: "pub_004__section__response",
    },
    {
      order: 5,
      id: "comparison",
      title: "비교 맥락",
      component: "ComparisonWorkbench",
      purpose: "cohort·제외·분포·단위.",
      test_id: "pub_004__section__comparison",
    },
    {
      order: 6,
      id: "counter",
      title: "반대 근거",
      component: "EvidenceLedger",
      purpose: "대안 설명과 반박 자료.",
      test_id: "pub_004__section__counter",
    },
    {
      order: 7,
      id: "evidence",
      title: "근거·원문",
      component: "EvidenceLedger",
      purpose: "claim별 locator와 provenance.",
      test_id: "pub_004__section__evidence",
    },
    {
      order: 8,
      id: "timeline",
      title: "조사·공개 이력",
      component: "RevisionTimeline",
      purpose: "공개 가능한 사건 timeline.",
      test_id: "pub_004__section__timeline",
    },
    {
      order: 9,
      id: "revision",
      title: "정정·개정 이력",
      component: "StatusAndRevisionHeader",
      purpose: "불변 revision과 변경 이유.",
      test_id: "pub_004__section__revision",
    },
  ],
  actions: [
    {
      id: "open-evidence",
      label: "근거 원문 보기",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "copy-citation",
      label: "인용 정보 복사",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "request-correction",
      label: "정정 요청",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe-case",
      label: "이 사건 구독",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getPublicCase",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}",
      blocking: true,
      response_schema: "PublicCaseResponse",
    },
    {
      operation_id: "listCaseRevisions",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/revisions",
      blocking: true,
      response_schema: "CaseRevisionsPage",
    },
    {
      operation_id: "getCaseReproducibility",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/reproducibility",
      blocking: true,
      response_schema: "CaseReproducibilityResponse",
    },
  ],
} as const satisfies ScreenViewModel;
