import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-008",
  title: "소명 관리",
  route: "/internal/cases/{caseId}/responses",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "requests",
      title: "요청 목록",
      component: "DataCollection",
      purpose: "target·due·delivery.",
      test_id: "cas_008__section__requests",
    },
    {
      order: 2,
      id: "submissions",
      title: "제출",
      component: "GuidedFormSection",
      purpose: "receipt·consent·attachments.",
      test_id: "cas_008__section__submissions",
    },
    {
      order: 3,
      id: "verification",
      title: "검증",
      component: "KnownUnknownResponse",
      purpose: "claim별 확인.",
      test_id: "cas_008__section__verification",
    },
    {
      order: 4,
      id: "public-copy",
      title: "공개 excerpt",
      component: "StructuredContentSection",
      purpose: "원문/요약·redaction.",
      test_id: "cas_008__section__public-copy",
    },
    {
      order: 5,
      id: "timeline",
      title: "소명 timeline",
      component: "KnownUnknownResponse",
      purpose: "reminder·extension.",
      test_id: "cas_008__section__timeline",
    },
  ],
  actions: [
    {
      id: "new-request",
      label: "소명 요청 작성",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-submission",
      label: "제출 검토",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "approve-excerpt",
      label: "공개 excerpt 승인",
      capability: "responses.review",
      operation_id: "approveResponseExcerpt",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseResponses",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-responses",
      blocking: true,
      response_schema: "CaseResponsesPage",
    },
    {
      operation_id: "approveResponseExcerpt",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/approve-response-excerpt",
      blocking: true,
      response_schema: "approveResponseExcerptReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
