import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-023",
  title: "재원·수익 투명성",
  route: "/about/funding",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "principles",
      title: "독립성 원칙",
      component: "StructuredContentSection",
      purpose: "돈과 편집의 방화벽.",
      test_id: "pub_023__section__principles",
    },
    {
      order: 2,
      id: "income",
      title: "재원",
      component: "StructuredContentSection",
      purpose: "후원·grant·API/SaaS.",
      test_id: "pub_023__section__income",
    },
    {
      order: 3,
      id: "expenses",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "인프라·인력·법률.",
      test_id: "pub_023__section__expenses",
    },
    {
      order: 4,
      id: "donors",
      title: "공개 기준",
      component: "StructuredContentSection",
      purpose: "기준 이상 후원 공개.",
      test_id: "pub_023__section__donors",
    },
    {
      order: 5,
      id: "conflicts",
      title: "이해상충",
      component: "StructuredContentSection",
      purpose: "회피·검토.",
      test_id: "pub_023__section__conflicts",
    },
    {
      order: 6,
      id: "reports",
      title: "보고서",
      component: "StructuredContentSection",
      purpose: "기간별 transparency report.",
      test_id: "pub_023__section__reports",
    },
  ],
  actions: [
    {
      id: "download-report",
      label: "투명성 보고서 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-governance",
      label: "governance 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getFundingContent",
      api: "public-api",
      method: "GET",
      path: "/v1/content/funding",
      blocking: false,
      response_schema: "FundingContentResponse",
    },
    {
      operation_id: "listTransparencyReports",
      api: "public-api",
      method: "GET",
      path: "/v1/transparency-reports",
      blocking: false,
      response_schema: "TransparencyReportsPage",
    },
  ],
} as const satisfies ScreenViewModel;
