import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-023",
  title: "재원·수익 투명성",
  route: "/about/funding",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "principles",
      title: "독립성 원칙",
      component: "StructuredContentSection",
      purpose: "후원·수익과 편집 독립성의 분리 원칙.",
      test_id: "pub_023__section__principles",
    },
    {
      order: 2,
      id: "income",
      title: "재원",
      component: "StructuredContentSection",
      purpose: "후원·지원금·조직용 서비스.",
      test_id: "pub_023__section__income",
    },
    {
      order: 3,
      id: "expenses",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "인프라·인력·법률.",
      test_id: "pub_023__section__expenses",
    },
    {
      order: 4,
      id: "donors",
      title: "공개 기준",
      component: "StructuredContentSection",
      purpose: "승인된 공개명·비공개 사유·출처 링크와 UNKNOWN 사유.",
      test_id: "pub_023__section__donors",
    },
    {
      order: 5,
      id: "conflicts",
      title: "이해상충",
      component: "DecisionReviewPanel",
      purpose: "승인된 이해상충·완화·독립 검토 결과.",
      test_id: "pub_023__section__conflicts",
    },
    {
      order: 6,
      id: "reports",
      title: "보고서",
      component: "StructuredContentSection",
      purpose: "기간별 투명성 보고서.",
      test_id: "pub_023__section__reports",
    },
  ],
  actions: [
    {
      id: "download-report",
      label: "투명성 보고서 다운로드",
      capability: "none",
      operation_id: "downloadTransparencyReport",
      request_binding: {
        reportId: "listTransparencyReports.items[].id",
      },
      href_binding: {
        source: "listTransparencyReports.items[].href",
        must_equal: "/v1/transparency-reports/{reportId}/download",
      },
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "view-governance",
      label: "거버넌스 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getFundingContent",
      api: "public-api",
      method: "GET",
      path: "/v1/content/funding",
      blocking: false,
      response_schema: "FundingContentResponse",
    },
    {
      operation_id: "listTransparencyReports",
      api: "public-api",
      method: "GET",
      path: "/v1/transparency-reports",
      blocking: false,
      response_schema: "TransparencyReportsPage",
    },
    {
      operation_id: "downloadTransparencyReport",
      api: "public-api",
      method: "GET",
      path: "/v1/transparency-reports/{reportId}/download",
      blocking: false,
      request_schema: "DownloadTransparencyReportRequestV1",
      response_schema: "TransparencyReportDownloadV1",
      success_status: 200,
    },
  ],
} as const satisfies ScreenViewModel;
