import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "INT-004",
  title: "알림",
  route: "/internal/notifications",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "unread/type.",
      test_id: "int_004__section__filters",
    },
    {
      order: 2,
      id: "notifications",
      title: "알림",
      component: "StructuredContentSection",
      purpose: "event·object·action.",
      test_id: "int_004__section__notifications",
    },
    {
      order: 3,
      id: "preferences",
      title: "설정",
      component: "AccessManagementPanel",
      purpose: "role-appropriate delivery.",
      test_id: "int_004__section__preferences",
    },
  ],
  actions: [
    {
      id: "open",
      label: "알림 대상 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "mark-read",
      label: "읽음 처리",
      capability: "none",
      operation_id: "markNotificationRead",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "manage",
      label: "알림 설정",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listInternalNotifications",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-internal-notifications",
      blocking: true,
      response_schema: "InternalNotificationsPage",
    },
    {
      operation_id: "markNotificationRead",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/mark-notification-read",
      blocking: false,
      response_schema: "markNotificationReadReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
