import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SRC-002",
  title: "출처 상세",
  route: "/internal/sources/{sourceId}",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "출처 식별 정보",
      component: "StructuredContentSection",
      purpose: "owner·access·terms.",
      test_id: "src_002__section__identity",
    },
    {
      order: 2,
      id: "status",
      title: "상태·서비스 수준 목표",
      component: "StatusAndRevisionHeader",
      purpose: "last success·lag.",
      test_id: "src_002__section__status",
    },
    {
      order: 3,
      id: "checkpoint",
      title: "처리 기준점",
      component: "StructuredContentSection",
      purpose: "pagination cursor·watermark.",
      test_id: "src_002__section__checkpoint",
    },
    {
      order: 4,
      id: "quality",
      title: "품질 지표",
      component: "StructuredContentSection",
      purpose: "duplicate/missing/parser.",
      test_id: "src_002__section__quality",
    },
    {
      order: 5,
      id: "schema",
      title: "스키마 버전",
      component: "StructuredContentSection",
      purpose: "drift.",
      test_id: "src_002__section__schema",
    },
    {
      order: 6,
      id: "downstream",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "normalized fields/rules/public.",
      test_id: "src_002__section__downstream",
    },
    {
      order: 7,
      id: "runbook",
      title: "대응 절차",
      component: "StructuredContentSection",
      purpose: "safe action.",
      test_id: "src_002__section__runbook",
    },
  ],
  actions: [
    {
      id: "view-runs",
      label: "실행 기록",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-drift",
      label: "스키마 드리프트",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "start-manual-run",
      label: "수동 실행 요청",
      capability: "sources.operate",
      operation_id: "startSourceRun",
      guard: "bounded scope + idempotency",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getInternalSource",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-internal-source",
      blocking: true,
      response_schema: "InternalSourceResponse",
    },
    {
      operation_id: "startSourceRun",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/start-source-run",
      blocking: false,
      response_schema: "startSourceRunReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
