import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-003",
  title: "작업 상세",
  route: "/internal/operations/jobs/{jobId}",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "작업 식별 정보",
      component: "StructuredContentSection",
      purpose: "type·aggregate·created.",
      test_id: "ops_003__section__identity",
    },
    {
      order: 2,
      id: "state",
      title: "상태·실행 소유권",
      component: "StatusAndRevisionHeader",
      purpose: "owner/fencing/heartbeat.",
      test_id: "ops_003__section__state",
    },
    {
      order: 3,
      id: "attempts",
      title: "시도 이력",
      component: "StructuredContentSection",
      purpose: "error/fingerprint/backoff.",
      test_id: "ops_003__section__attempts",
    },
    {
      order: 4,
      id: "payload",
      title: "입력 자료 참조",
      component: "StructuredContentSection",
      purpose: "redacted.",
      test_id: "ops_003__section__payload",
    },
    {
      order: 5,
      id: "effects",
      title: "후속 반영",
      component: "StructuredContentSection",
      purpose: "outbox/inbox/projection.",
      test_id: "ops_003__section__effects",
    },
    {
      order: 6,
      id: "recovery",
      title: "복구",
      component: "StructuredContentSection",
      purpose: "retry/cancel/quarantine.",
      test_id: "ops_003__section__recovery",
    },
    {
      order: 7,
      id: "audit",
      title: "이벤트",
      component: "StructuredContentSection",
      purpose: "commands.",
      test_id: "ops_003__section__audit",
    },
  ],
  actions: [
    {
      id: "retry",
      label: "작업 재시도",
      capability: "jobs.operate",
      operation_id: "retryJob",
      guard: "idempotency verified",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "cancel",
      label: "작업 취소",
      capability: "jobs.operate",
      operation_id: "cancelJob",
      guard: "safe cancellation + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "quarantine",
      label: "격리",
      capability: "jobs.operate",
      operation_id: "quarantineJob",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getJob",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-job",
      blocking: true,
      response_schema: "JobResponse",
    },
    {
      operation_id: "retryJob",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/retry-job",
      blocking: false,
      response_schema: "retryJobReceipt",
    },
    {
      operation_id: "cancelJob",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/cancel-job",
      blocking: false,
      response_schema: "cancelJobReceipt",
    },
    {
      operation_id: "quarantineJob",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/quarantine-job",
      blocking: false,
      response_schema: "quarantineJobReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
