import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-032",
  title: "이용약관",
  route: "/terms",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "service",
      title: "서비스 조건",
      component: "AgentSuggestionPanel",
      purpose: "서비스 제공 범위와 이용 조건.",
      test_id: "pub_032__section__service",
    },
    {
      order: 2,
      id: "content",
      title: "콘텐츠",
      component: "StatusAndRevisionHeader",
      purpose: "attribution·revision.",
      test_id: "pub_032__section__content",
    },
    {
      order: 3,
      id: "data",
      title: "데이터·공개 인터페이스",
      component: "StructuredContentSection",
      purpose: "license·rate.",
      test_id: "pub_032__section__data",
    },
    {
      order: 4,
      id: "prohibited",
      title: "금지",
      component: "StructuredContentSection",
      purpose: "abuse·reidentification.",
      test_id: "pub_032__section__prohibited",
    },
    {
      order: 5,
      id: "liability",
      title: "책임·한계",
      component: "DecisionReviewPanel",
      purpose: "법률 검토.",
      test_id: "pub_032__section__liability",
    },
    {
      order: 6,
      id: "changes",
      title: "변경",
      component: "StructuredContentSection",
      purpose: "notice.",
      test_id: "pub_032__section__changes",
    },
  ],
  actions: [
    {
      id: "view-data",
      label: "데이터 안내",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "contact",
      label: "문의",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getTerms",
      api: "public-api",
      method: "GET",
      path: "/v1/content/terms",
      blocking: false,
      response_schema: "TermsResponse",
    },
  ],
} as const satisfies ScreenViewModel;
