import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SRC-005",
  title: "Schema Drift",
  route: "/internal/sources/{sourceId}/schema-drift",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "alert",
      title: "drift identity",
      component: "StructuredContentSection",
      purpose: "detected version/time.",
      test_id: "src_005__section__alert",
    },
    {
      order: 2,
      id: "diff",
      title: "schema diff",
      component: "StructuredContentSection",
      purpose: "add/remove/type.",
      test_id: "src_005__section__diff",
    },
    {
      order: 3,
      id: "samples",
      title: "redacted samples",
      component: "StructuredContentSection",
      purpose: "frequency.",
      test_id: "src_005__section__samples",
    },
    {
      order: 4,
      id: "impact",
      title: "dependency impact",
      component: "StructuredContentSection",
      purpose: "parser/field/rule/public.",
      test_id: "src_005__section__impact",
    },
    {
      order: 5,
      id: "mapping",
      title: "proposed mapping",
      component: "StructuredContentSection",
      purpose: "code/task.",
      test_id: "src_005__section__mapping",
    },
    {
      order: 6,
      id: "shadow",
      title: "shadow result",
      component: "DataCollection",
      purpose: "fixture/records.",
      test_id: "src_005__section__shadow",
    },
    {
      order: 7,
      id: "decision",
      title: "승인·보류",
      component: "DecisionReviewPanel",
      purpose: "reason.",
      test_id: "src_005__section__decision",
    },
  ],
  actions: [
    {
      id: "approve-mapping",
      label: "mapping 승인",
      capability: "sources.operate",
      operation_id: "approveSchemaMapping",
      guard: "shadow pass + reviewer",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "reject-mapping",
      label: "변경 요청",
      capability: "sources.operate",
      operation_id: "rejectSchemaMapping",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "pause-source",
      label: "source pause",
      capability: "sources.operate",
      operation_id: "pauseSource",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getSchemaDrift",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-schema-drift",
      blocking: true,
      response_schema: "SchemaDriftResponse",
    },
    {
      operation_id: "approveSchemaMapping",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/approve-schema-mapping",
      blocking: true,
      response_schema: "approveSchemaMappingReceipt",
    },
    {
      operation_id: "rejectSchemaMapping",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/reject-schema-mapping",
      blocking: false,
      response_schema: "rejectSchemaMappingReceipt",
    },
    {
      operation_id: "pauseSource",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/pause-source",
      blocking: false,
      response_schema: "pauseSourceReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
