import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RSP-002",
  title: "요청 내용",
  route: "/respond/overview",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "questions",
      title: "질문",
      component: "GuidedFormSection",
      purpose: "중립적 구조화 질문.",
      test_id: "rsp_002__section__questions",
    },
    {
      order: 2,
      id: "references",
      title: "관련 자료",
      component: "EvidenceLedger",
      purpose: "공개 claim/evidence만.",
      test_id: "rsp_002__section__references",
    },
    {
      order: 3,
      id: "deadline",
      title: "기한·연장",
      component: "StructuredContentSection",
      purpose: "현재 due.",
      test_id: "rsp_002__section__deadline",
    },
    {
      order: 4,
      id: "public-use",
      title: "공개 범위",
      component: "CoverageStatement",
      purpose: "동의 선택 설명.",
      test_id: "rsp_002__section__public-use",
    },
    {
      order: 5,
      id: "support",
      title: "지원",
      component: "StructuredContentSection",
      purpose: "담당자와 안전 채널.",
      test_id: "rsp_002__section__support",
    },
  ],
  actions: [
    {
      id: "start-answer",
      label: "답변 작성",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "request-extension",
      label: "기한 연장 요청",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "download-request",
      label: "요청서 저장",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getResponseRequest",
      api: "submission-api",
      method: "GET",
      path: "/v1/response-session",
      blocking: true,
      response_schema: "ResponseRequestResponse",
    },
    {
      operation_id: "downloadResponseRequest",
      api: "submission-api",
      method: "GET",
      path: "/v1/response-session/download",
      blocking: true,
      response_schema: "BinaryDownload",
    },
  ],
} as const satisfies ScreenViewModel;
