import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "AUTH-004",
  title: "세션 만료",
  route: "/auth/session-expired",
  archetype: "AUTH_SYSTEM",
  sections: [
    {
      order: 1,
      id: "status",
      title: "만료 안내",
      component: "StatusAndRevisionHeader",
      purpose: "시각·이유 범주.",
      test_id: "auth_004__section__status",
    },
    {
      order: 2,
      id: "draft",
      title: "초안 상태",
      component: "StatusAndRevisionHeader",
      purpose: "server/local 안전 보존.",
      test_id: "auth_004__section__draft",
    },
    {
      order: 3,
      id: "signin",
      title: "재로그인",
      component: "StructuredContentSection",
      purpose: "return URL.",
      test_id: "auth_004__section__signin",
    },
    {
      order: 4,
      id: "support",
      title: "지원",
      component: "StructuredContentSection",
      purpose: "반복 만료.",
      test_id: "auth_004__section__support",
    },
  ],
  actions: [
    {
      id: "sign-in-again",
      label: "다시 로그인",
      capability: "none",
      operation_id: "startOidcLogin",
      interaction_kind: "COMMAND",
      assurance_level: "ANONYMOUS_PROOF",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "discard-local",
      label: "로컬 임시 상태 삭제",
      capability: "none",
      local_only: true,
      persistence: "browser_session",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "startOidcLogin",
      api: "identity-provider",
      method: "GET",
      path: "/auth/login",
      blocking: true,
      response_schema: "startOidcLoginReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
