import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-011",
  title: "계약",
  route: "/contracts",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "계약 coverage",
      component: "CoverageStatement",
      purpose: "사건 여부와 무관한 관측 범위.",
      test_id: "pub_011__section__scope",
    },
    {
      order: 2,
      id: "filters",
      title: "계약 필터",
      component: "UnifiedSearch",
      purpose: "기관·업체·날짜·방식·품목·금액.",
      test_id: "pub_011__section__filters",
    },
    {
      order: 3,
      id: "results",
      title: "계약 결과",
      component: "DataCollection",
      purpose: "금액·기간·source·related case.",
      test_id: "pub_011__section__results",
    },
    {
      order: 4,
      id: "limitations",
      title: "비교 한계",
      component: "ComparisonWorkbench",
      purpose: "금액·단위 정렬 주의.",
      test_id: "pub_011__section__limitations",
    },
  ],
  actions: [
    {
      id: "open-contract",
      label: "계약 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "apply-filter",
      label: "필터 적용",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "download",
      label: "결과 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listContracts",
      api: "public-api",
      method: "GET",
      path: "/v1/contracts",
      blocking: true,
      response_schema: "ContractsPage",
    },
    {
      operation_id: "downloadContracts",
      api: "public-api",
      method: "GET",
      path: "/v1/contracts/download",
      blocking: false,
      response_schema: "BinaryDownload",
    },
  ],
} as const satisfies ScreenViewModel;
