import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-021",
  title: "공개 API 문서",
  route: "/api",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "getting-started",
      title: "시작",
      component: "StructuredContentSection",
      purpose: "base URL·auth/rate.",
      test_id: "pub_021__section__getting-started",
    },
    {
      order: 2,
      id: "resources",
      title: "resource",
      component: "RevisionAndCorrectionPanel",
      purpose: "case/contract/entity/method/correction.",
      test_id: "pub_021__section__resources",
    },
    {
      order: 3,
      id: "pagination",
      title: "pagination",
      component: "StructuredContentSection",
      purpose: "cursor·sort.",
      test_id: "pub_021__section__pagination",
    },
    {
      order: 4,
      id: "errors",
      title: "오류",
      component: "StructuredContentSection",
      purpose: "Problem Details.",
      test_id: "pub_021__section__errors",
    },
    {
      order: 5,
      id: "versioning",
      title: "versioning",
      component: "StructuredContentSection",
      purpose: "OpenAPI와 deprecation.",
      test_id: "pub_021__section__versioning",
    },
    {
      order: 6,
      id: "download",
      title: "OpenAPI",
      component: "StructuredContentSection",
      purpose: "JSON 다운로드.",
      test_id: "pub_021__section__download",
    },
  ],
  actions: [
    {
      id: "download-openapi",
      label: "OpenAPI JSON 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-data-policy",
      label: "데이터 정책",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getPublicApiDocumentation",
      api: "public-api",
      method: "GET",
      path: "/v1/content/api",
      blocking: false,
      response_schema: "PublicApiDocumentationResponse",
    },
    {
      operation_id: "downloadPublicOpenApi",
      api: "public-api",
      method: "GET",
      path: "/v1/openapi.json",
      blocking: false,
      response_schema: "BinaryDownload",
    },
  ],
} as const satisfies ScreenViewModel;
