import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RSP-003",
  title: "답변 작성",
  route: "/respond/answer",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "progress",
      title: "진행 상태",
      component: "StepIndicator",
      purpose: "단계와 저장.",
      test_id: "rsp_003__section__progress",
    },
    {
      order: 2,
      id: "questions",
      title: "질문별 답변",
      component: "GuidedFormSection",
      purpose: "answer·reference.",
      test_id: "rsp_003__section__questions",
    },
    {
      order: 3,
      id: "statement",
      title: "전체 입장",
      component: "StructuredContentSection",
      purpose: "선택적.",
      test_id: "rsp_003__section__statement",
    },
    {
      order: 4,
      id: "consent",
      title: "공개 동의",
      component: "StructuredContentSection",
      purpose: "FULL/REDACTED/SUMMARY/NO_CONSENT.",
      test_id: "rsp_003__section__consent",
    },
    {
      order: 5,
      id: "save",
      title: "저장 상태",
      component: "SaveStatus",
      purpose: "last saved·conflict.",
      test_id: "rsp_003__section__save",
    },
  ],
  actions: [
    {
      id: "save-draft",
      label: "답변 임시 저장",
      capability: "none",
      operation_id: "saveResponseDraft",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "next",
      label: "첨부자료로",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "discard-change",
      label: "변경 취소",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getResponseDraft",
      api: "submission-api",
      method: "GET",
      path: "/v1/response-session/draft",
      blocking: true,
      response_schema: "ResponseDraftResponse",
    },
    {
      operation_id: "saveResponseDraft",
      api: "submission-api",
      method: "PUT",
      path: "/v1/response-session/draft",
      blocking: true,
      response_schema: "saveResponseDraftReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
