import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-018",
  title: "정정·철회",
  route: "/corrections",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "principle",
      title: "정정 정책",
      component: "RevisionAndCorrectionPanel",
      purpose: "공개 기록의 정정·철회·변경 공개 원칙.",
      test_id: "pub_018__section__principle",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "유형·기간·영향.",
      test_id: "pub_018__section__filters",
    },
    {
      order: 3,
      id: "records",
      title: "정정 목록",
      component: "DataCollection",
      purpose: "대상·변경 요약·이유·공개일을 포함한 정정 대장.",
      test_id: "pub_018__section__records",
    },
    {
      order: 4,
      id: "feed",
      title: "구독·정정 알림",
      component: "RevisionAndCorrectionPanel",
      purpose: "정정 알림.",
      test_id: "pub_018__section__feed",
    },
  ],
  actions: [
    {
      id: "apply-filter",
      label: "필터 적용",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-correction",
      label: "정정 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe",
      label: "정정 알림 구독",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listCorrections",
      api: "public-api",
      method: "GET",
      path: "/v1/corrections",
      blocking: true,
      response_schema: "CorrectionsPage",
    },
  ],
} as const satisfies ScreenViewModel;
