import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-004",
  title: "비용·예산",
  route: "/internal/operations/budgets",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "envelope",
      title: "예산 범위",
      component: "AgentSuggestionPanel",
      purpose: "daily/monthly.",
      test_id: "ops_004__section__envelope",
    },
    {
      order: 2,
      id: "spend",
      title: "사용량",
      component: "StructuredContentSection",
      purpose: "provider/workload/case bucket.",
      test_id: "ops_004__section__spend",
    },
    {
      order: 3,
      id: "forecast",
      title: "지출 전망",
      component: "StructuredContentSection",
      purpose: "confidence/assumption.",
      test_id: "ops_004__section__forecast",
    },
    {
      order: 4,
      id: "limits",
      title: "한도",
      component: "StructuredContentSection",
      purpose: "soft/hard/fallback.",
      test_id: "ops_004__section__limits",
    },
    {
      order: 5,
      id: "alerts",
      title: "경고",
      component: "StructuredContentSection",
      purpose: "threshold.",
      test_id: "ops_004__section__alerts",
    },
    {
      order: 6,
      id: "changes",
      title: "변경 이력",
      component: "RevisionTimeline",
      purpose: "approver/reason.",
      test_id: "ops_004__section__changes",
    },
  ],
  actions: [
    {
      id: "change-limit",
      label: "예산 한도 변경",
      capability: "budgets.manage",
      operation_id: "updateBudgetLimit",
      guard: "reauth + approver + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "export",
      label: "비용 보고서",
      capability: "audit.read",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-provider",
      label: "공급자 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getBudgetOverview",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-budget-overview",
      blocking: true,
      response_schema: "BudgetOverviewResponse",
    },
    {
      operation_id: "updateBudgetLimit",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/update-budget-limit",
      blocking: false,
      response_schema: "updateBudgetLimitReceipt",
    },
    {
      operation_id: "exportCostReport",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/export-cost-report",
      blocking: false,
      response_schema: "BinaryDownload",
    },
  ],
} as const satisfies ScreenViewModel;
