import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-006",
  title: "킬 스위치",
  route: "/internal/operations/kill-switches",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "active",
      title: "활성 비상 중지",
      component: "StructuredContentSection",
      purpose: "scope·reason·expiry.",
      test_id: "ops_006__section__active",
    },
    {
      order: 2,
      id: "catalog",
      title: "비상 중지 목록",
      component: "DataCollection",
      purpose: "safe fallback.",
      test_id: "ops_006__section__catalog",
    },
    {
      order: 3,
      id: "impact",
      title: "영향",
      component: "AccessManagementPanel",
      purpose: "users/data/jobs.",
      test_id: "ops_006__section__impact",
    },
    {
      order: 4,
      id: "approval",
      title: "승인",
      component: "DecisionReviewPanel",
      purpose: "SoD·reauth.",
      test_id: "ops_006__section__approval",
    },
    {
      order: 5,
      id: "history",
      title: "이력",
      component: "RevisionTimeline",
      purpose: "activation/resume.",
      test_id: "ops_006__section__history",
    },
    {
      order: 6,
      id: "runbook",
      title: "대응 절차",
      component: "StructuredContentSection",
      purpose: "verification.",
      test_id: "ops_006__section__runbook",
    },
  ],
  actions: [
    {
      id: "activate",
      label: "킬 스위치 활성화",
      capability: "kill_switch.execute",
      operation_id: "activateKillSwitch",
      guard: "reauth + reason + expiry + two-person where required",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "deactivate",
      label: "기능 재개",
      capability: "kill_switch.execute",
      operation_id: "deactivateKillSwitch",
      guard: "recovery checks",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "extend",
      label: "만료 연장",
      capability: "kill_switch.execute",
      operation_id: "extendKillSwitch",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listKillSwitches",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-kill-switches",
      blocking: true,
      response_schema: "KillSwitchesPage",
    },
    {
      operation_id: "activateKillSwitch",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/activate-kill-switch",
      blocking: true,
      response_schema: "activateKillSwitchReceipt",
    },
    {
      operation_id: "deactivateKillSwitch",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/deactivate-kill-switch",
      blocking: true,
      response_schema: "deactivateKillSwitchReceipt",
    },
    {
      operation_id: "extendKillSwitch",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/extend-kill-switch",
      blocking: false,
      response_schema: "extendKillSwitchReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
