import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "REV-001",
  title: "검토 Queue",
  route: "/internal/review",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "views",
      title: "검토 유형",
      component: "DecisionReviewPanel",
      purpose: "editorial/legal/publish.",
      test_id: "rev_001__section__views",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "risk/state/due/reviewer.",
      test_id: "rev_001__section__filters",
    },
    {
      order: 3,
      id: "queue",
      title: "snapshot 목록",
      component: "KnownUnknownResponse",
      purpose: "hash·case·response·changes.",
      test_id: "rev_001__section__queue",
    },
    {
      order: 4,
      id: "independence",
      title: "독립성",
      component: "StructuredContentSection",
      purpose: "conflict 표시.",
      test_id: "rev_001__section__independence",
    },
  ],
  actions: [
    {
      id: "open-review",
      label: "검토 시작",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "assign-reviewer",
      label: "검토자 배정",
      capability: "review.editorial",
      operation_id: "assignReview",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listReviewQueue",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-review-queue",
      blocking: true,
      response_schema: "ReviewQueuePage",
    },
    {
      operation_id: "assignReview",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/assign-review",
      blocking: false,
      response_schema: "assignReviewReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
