import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RULE-004",
  title: "규칙 활성화",
  route: "/internal/rules/{ruleId}/versions/{version}/activation",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "target",
      title: "활성화 대상",
      component: "StructuredContentSection",
      purpose: "version/hash.",
      test_id: "rule_004__section__target",
    },
    {
      order: 2,
      id: "gates",
      title: "품질 검증",
      component: "DecisionReviewPanel",
      purpose: "eval/shadow/review.",
      test_id: "rule_004__section__gates",
    },
    {
      order: 3,
      id: "impact",
      title: "영향",
      component: "SignalTriagePanel",
      purpose: "signals/cases/cost/source.",
      test_id: "rule_004__section__impact",
    },
    {
      order: 4,
      id: "schedule",
      title: "일정",
      component: "StructuredContentSection",
      purpose: "effective time.",
      test_id: "rule_004__section__schedule",
    },
    {
      order: 5,
      id: "rollback",
      title: "되돌리기",
      component: "StructuredContentSection",
      purpose: "target/version.",
      test_id: "rule_004__section__rollback",
    },
    {
      order: 6,
      id: "approval",
      title: "승인",
      component: "DecisionReviewPanel",
      purpose: "SoD·reauth.",
      test_id: "rule_004__section__approval",
    },
    {
      order: 7,
      id: "receipt",
      title: "결과",
      component: "DataCollection",
      purpose: "activation event.",
      test_id: "rule_004__section__receipt",
    },
  ],
  actions: [
    {
      id: "activate",
      label: "규칙 활성화",
      capability: "rules.activate",
      operation_id: "activateRuleVersion",
      guard: "independent approval + reauth + rollback",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "schedule",
      label: "활성화 예약",
      capability: "rules.activate",
      operation_id: "scheduleRuleActivation",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "rollback",
      label: "이전 버전으로 되돌리기",
      capability: "rules.activate",
      operation_id: "rollbackRuleVersion",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getRuleActivationReadiness",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-rule-activation-readiness",
      blocking: true,
      response_schema: "RuleActivationReadinessResponse",
    },
    {
      operation_id: "activateRuleVersion",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/activate-rule-version",
      blocking: true,
      response_schema: "activateRuleVersionReceipt",
    },
    {
      operation_id: "scheduleRuleActivation",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/schedule-rule-activation",
      blocking: false,
      response_schema: "scheduleRuleActivationReceipt",
    },
    {
      operation_id: "rollbackRuleVersion",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/rollback-rule-version",
      blocking: false,
      response_schema: "rollbackRuleVersionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
