import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-013",
  title: "방법론",
  route: "/methodology",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "overview",
      title: "방법론 개요",
      component: "LongFormArticle",
      purpose: "발견과 판정 분리.",
      test_id: "pub_013__section__overview",
    },
    {
      order: 2,
      id: "pipeline",
      title: "데이터에서 공개까지",
      component: "StructuredContentSection",
      purpose: "provenance와 human gate.",
      test_id: "pub_013__section__pipeline",
    },
    {
      order: 3,
      id: "rules",
      title: "규칙 목록",
      component: "DataCollection",
      purpose: "active/retired version.",
      test_id: "pub_013__section__rules",
    },
    {
      order: 4,
      id: "ai",
      title: "AI 역할",
      component: "AccessManagementPanel",
      purpose: "보조·금지 권한.",
      test_id: "pub_013__section__ai",
    },
    {
      order: 5,
      id: "quality",
      title: "평가와 오탐",
      component: "StructuredContentSection",
      purpose: "gold/false-positive.",
      test_id: "pub_013__section__quality",
    },
    {
      order: 6,
      id: "changes",
      title: "변경 이력",
      component: "RevisionTimeline",
      purpose: "effective version.",
      test_id: "pub_013__section__changes",
    },
  ],
  actions: [
    {
      id: "open-rule",
      label: "규칙 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-coverage",
      label: "데이터 범위 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listRules",
      api: "public-api",
      method: "GET",
      path: "/v1/rules",
      blocking: true,
      response_schema: "RulesPage",
    },
    {
      operation_id: "getMethodologyOverview",
      api: "public-api",
      method: "GET",
      path: "/v1/content/methodology",
      blocking: false,
      response_schema: "MethodologyOverviewResponse",
    },
  ],
} as const satisfies ScreenViewModel;
