import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "ADM-003",
  title: "역할 정의",
  route: "/internal/admin/roles",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "catalog",
      title: "role catalog",
      component: "StatusAndRevisionHeader",
      purpose: "description/status.",
      test_id: "adm_003__section__catalog",
    },
    {
      order: 2,
      id: "capabilities",
      title: "capability matrix",
      component: "StructuredContentSection",
      purpose: "read/write/high impact.",
      test_id: "adm_003__section__capabilities",
    },
    {
      order: 3,
      id: "conflicts",
      title: "SoD",
      component: "AccessManagementPanel",
      purpose: "conflicting roles.",
      test_id: "adm_003__section__conflicts",
    },
    {
      order: 4,
      id: "grants",
      title: "grant stats",
      component: "StructuredContentSection",
      purpose: "count/expiry.",
      test_id: "adm_003__section__grants",
    },
    {
      order: 5,
      id: "review",
      title: "정기 검토",
      component: "DecisionReviewPanel",
      purpose: "owner/last review.",
      test_id: "adm_003__section__review",
    },
    {
      order: 6,
      id: "history",
      title: "변경 이력",
      component: "RevisionTimeline",
      purpose: "version.",
      test_id: "adm_003__section__history",
    },
  ],
  actions: [
    {
      id: "open-role",
      label: "역할 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "propose-change",
      label: "역할 변경 제안",
      capability: "roles.grant",
      operation_id: "proposeRoleDefinitionChange",
      interaction_kind: "COMMAND",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: false,
    },
    {
      id: "export-matrix",
      label: "권한 matrix 다운로드",
      capability: "audit.read",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listRoleDefinitions",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-role-definitions",
      blocking: true,
      response_schema: "RoleDefinitionsPage",
    },
    {
      operation_id: "proposeRoleDefinitionChange",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/propose-role-definition-change",
      blocking: false,
      response_schema: "proposeRoleDefinitionChangeReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
