BEGIN;

-- Application schemas are trusted and owned by the migration authority.
CREATE SCHEMA IF NOT EXISTS extensions;
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS editorial;
CREATE SCHEMA IF NOT EXISTS intake;
CREATE SCHEMA IF NOT EXISTS ops;
CREATE SCHEMA IF NOT EXISTS public;

-- Extension objects never live in public. Runtime roles receive USAGE only.
REVOKE ALL ON SCHEMA extensions FROM PUBLIC;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;

CREATE TYPE core.source_document_status AS ENUM ('DISCOVERED','FETCHED','PARSED','QUARANTINED','REJECTED');
CREATE TYPE core.contract_status AS ENUM ('ANNOUNCED','AWARDED','ACTIVE','COMPLETED','CANCELLED','UNKNOWN');
CREATE TYPE core.signal_status AS ENUM ('NEW','ASSIGNED','NEEDS_DATA','LINKED','DISMISSED','DUPLICATE');
CREATE TYPE editorial.investigation_state AS ENUM ('SIGNAL_DETECTED','TRIAGE','INVESTIGATING','AWAITING_RESPONSE','EDITORIAL_REVIEW','LEGAL_REVIEW','READY_TO_PUBLISH','CLOSED');
CREATE TYPE editorial.publication_state AS ENUM ('NEVER_PUBLISHED','PUBLISHED_ANOMALY','PUBLISHED_EXPLAINED','OFFICIALLY_CONFIRMED','CORRECTED','RETRACTED','TEMPORARILY_RESTRICTED');
CREATE TYPE editorial.resolution_code AS ENUM ('NONE','DATA_ERROR','DUPLICATE','EXPLAINED','INSUFFICIENT_EVIDENCE','REFERRED_CONFIDENTIAL','ARCHIVED');
CREATE TYPE editorial.claim_type AS ENUM ('FACT','CALCULATION','INFERENCE','LIMITATION','OFFICIAL_OUTCOME');
CREATE TYPE editorial.evidence_classification AS ENUM ('PUBLIC','RESTRICTED','PERSONAL_DATA','LEGAL_HOLD');
CREATE TYPE editorial.review_decision AS ENUM ('APPROVE','REJECT','CHANGES_REQUIRED');
CREATE TYPE intake.submission_status AS ENUM ('DRAFT','SUBMITTED','ACCEPTED','REJECTED','EXPIRED');
CREATE TYPE ops.job_status AS ENUM ('QUEUED','LEASED','RUNNING','SUCCEEDED','FAILED','DEAD_LETTER','CANCELLED','QUARANTINED');
CREATE TYPE ops.incident_severity AS ENUM ('INFO','MINOR','MAJOR','CRITICAL');
CREATE TYPE ops.kill_switch_state AS ENUM ('INACTIVE','ACTIVE','EXPIRED');
CREATE TYPE ops.audit_outcome AS ENUM ('SUCCESS','DENIED','FAILED');

CREATE OR REPLACE FUNCTION ops.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = clock_timestamp();
  RETURN NEW;
END
$$;

COMMIT;
