BEGIN;
CREATE TABLE ops.source_registry (source_id text PRIMARY KEY, display_name text NOT NULL, connector_type text NOT NULL, owner_team text NOT NULL, enabled boolean NOT NULL DEFAULT false, schedule_cron text NOT NULL, credential_reference text, base_url text, legal_status text NOT NULL CHECK (legal_status IN ('APPROVED','BLOCKED','REVIEW_REQUIRED')), configuration jsonb NOT NULL, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TRIGGER source_registry_updated_at BEFORE UPDATE ON ops.source_registry FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE ops.source_checkpoints (source_id text NOT NULL REFERENCES ops.source_registry(source_id) ON DELETE CASCADE, partition_key text NOT NULL, cursor_payload jsonb NOT NULL, remote_high_watermark text, last_success_at timestamptz, version bigint NOT NULL DEFAULT 1, updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY (source_id,partition_key));
CREATE TABLE ops.schema_drifts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_id text NOT NULL REFERENCES ops.source_registry(source_id), detected_at timestamptz NOT NULL, fingerprint_before char(64), fingerprint_after char(64) NOT NULL, added_fields jsonb NOT NULL DEFAULT '[]', removed_fields jsonb NOT NULL DEFAULT '[]', changed_fields jsonb NOT NULL DEFAULT '[]', sample_document_ids jsonb NOT NULL DEFAULT '[]', status text NOT NULL CHECK(status IN ('OPEN','APPROVED','REJECTED','RESOLVED')), impact text NOT NULL, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TRIGGER schema_drifts_updated_at BEFORE UPDATE ON ops.schema_drifts FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE ops.schema_mappings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), schema_drift_id uuid NOT NULL REFERENCES ops.schema_drifts(id), mapping_version integer NOT NULL CHECK(mapping_version>0), mapping_digest char(64) NOT NULL, field_mappings jsonb NOT NULL, status text NOT NULL CHECK(status IN ('DRAFT','APPROVED','REJECTED','SUPERSEDED')), proposed_by uuid REFERENCES ops.users(id), decided_by uuid REFERENCES ops.users(id), decision_reason text, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), decided_at timestamptz, UNIQUE(schema_drift_id,mapping_version), UNIQUE(schema_drift_id,mapping_digest));
CREATE TABLE ops.tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), task_type text NOT NULL, object_type text NOT NULL, object_id uuid NOT NULL, title text NOT NULL, status text NOT NULL CHECK(status IN ('OPEN','IN_PROGRESS','BLOCKED','DONE','CANCELLED')), priority text NOT NULL CHECK(priority IN ('LOW','NORMAL','HIGH','URGENT')), assignee_user_id uuid REFERENCES ops.users(id), due_at timestamptz, blocker_code text, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), completed_at timestamptz);
CREATE INDEX tasks_assignee_status_idx ON ops.tasks(assignee_user_id,status,due_at); CREATE TRIGGER tasks_updated_at BEFORE UPDATE ON ops.tasks FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE ops.saved_views (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES ops.users(id) ON DELETE CASCADE, name text NOT NULL, surface text NOT NULL CHECK(surface IN ('MY_WORK','SIGNALS','CASES','SEARCH')), query jsonb NOT NULL, is_default boolean NOT NULL DEFAULT false, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(), UNIQUE(user_id,name,surface)); CREATE UNIQUE INDEX saved_views_one_default_idx ON ops.saved_views(user_id,surface) WHERE is_default; CREATE TRIGGER saved_views_updated_at BEFORE UPDATE ON ops.saved_views FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE ops.agent_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), case_id uuid NOT NULL REFERENCES editorial.cases(id), agent_type text NOT NULL, objective text NOT NULL, evidence_scope_ids jsonb NOT NULL, provider_policy text NOT NULL, provider text, model text, status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED','BUDGET_BLOCKED','POLICY_BLOCKED')), input_snapshot_hash char(64) NOT NULL, output_payload jsonb, output_schema_version text, max_cost numeric(18,6) NOT NULL, actual_cost numeric(18,6), started_at timestamptz, completed_at timestamptz, version bigint NOT NULL DEFAULT 1, created_by uuid NOT NULL REFERENCES ops.users(id), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp()); CREATE TRIGGER agent_runs_updated_at BEFORE UPDATE ON ops.agent_runs FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE ops.agent_suggestions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), agent_run_id uuid NOT NULL REFERENCES ops.agent_runs(id) ON DELETE CASCADE, case_id uuid NOT NULL REFERENCES editorial.cases(id), suggestion_type text NOT NULL, payload jsonb NOT NULL, evidence_ids jsonb NOT NULL, citation_checks jsonb NOT NULL, status text NOT NULL CHECK(status IN ('PENDING','ACCEPTED','REJECTED','SUPERSEDED')), decision_reason text, decided_by uuid REFERENCES ops.users(id), decided_at timestamptz, version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE ops.access_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), requester_user_id uuid NOT NULL REFERENCES ops.users(id), requested_role_codes jsonb NOT NULL, reason text NOT NULL, requested_until timestamptz, status text NOT NULL CHECK(status IN ('PENDING','APPROVED','REJECTED','CANCELLED','EXPIRED')), decided_by uuid REFERENCES ops.users(id), decision_reason text, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), decided_at timestamptz);
CREATE TABLE ops.access_reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), scope text NOT NULL CHECK(scope IN ('ALL_USERS','ROLE','USER')), scope_id uuid, reviewer_user_ids jsonb NOT NULL, due_at timestamptz NOT NULL, reason text NOT NULL, status text NOT NULL CHECK(status IN ('OPEN','IN_PROGRESS','COMPLETED','CANCELLED')), findings jsonb NOT NULL DEFAULT '[]', created_by uuid NOT NULL REFERENCES ops.users(id), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), completed_at timestamptz);
CREATE TABLE ops.role_change_proposals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), role_id uuid NOT NULL REFERENCES ops.roles(id), add_capabilities jsonb NOT NULL, remove_capabilities jsonb NOT NULL, reason text NOT NULL, status text NOT NULL CHECK(status IN ('DRAFT','REVIEW','APPROVED','REJECTED','APPLIED')), proposed_by uuid NOT NULL REFERENCES ops.users(id), decided_by uuid REFERENCES ops.users(id), version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), decided_at timestamptz);
CREATE TABLE editorial.legal_holds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES editorial.cases(id),
  review_snapshot_id uuid NOT NULL REFERENCES editorial.review_snapshots(id),
  object_type text NOT NULL CHECK (object_type IN ('CASE','PUBLICATION','EVIDENCE','RESPONSE')),
  object_id uuid NOT NULL,
  scope text NOT NULL CHECK (scope IN ('RETENTION','DISCLOSURE','DELETION','ALL')),
  affected_ids jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(affected_ids)='array'),
  reason text NOT NULL CHECK (length(btrim(reason)) BETWEEN 1 AND 4000),
  authority_reference text NOT NULL CHECK (length(btrim(authority_reference)) BETWEEN 1 AND 1000),
  expires_at timestamptz,
  active boolean NOT NULL DEFAULT true,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  placed_by uuid NOT NULL REFERENCES ops.users(id),
  placed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  released_by uuid REFERENCES ops.users(id),
  released_at timestamptz,
  CHECK (expires_at IS NULL OR expires_at > placed_at),
  CHECK ((active AND released_at IS NULL AND released_by IS NULL) OR (NOT active AND released_at IS NOT NULL))
);
CREATE UNIQUE INDEX active_legal_hold_idx ON editorial.legal_holds(object_type,object_id) WHERE active;
CREATE INDEX legal_holds_case_idx ON editorial.legal_holds(case_id,active,placed_at DESC);
CREATE TABLE ops.retention_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), subject_type text NOT NULL, subject_ref_hash char(64) NOT NULL, request_type text NOT NULL CHECK(request_type IN ('ACCESS','CORRECTION','DELETION','RESTRICTION')), status text NOT NULL CHECK(status IN ('RECEIVED','REVIEW','APPROVED','REJECTED','COMPLETED')), legal_hold_blocked boolean NOT NULL DEFAULT false, reason text, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), completed_at timestamptz);
CREATE TABLE ops.email_deliveries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), message_type text NOT NULL, recipient_hash char(64) NOT NULL, template_version text NOT NULL, object_type text, object_id uuid, provider_message_id text, status text NOT NULL CHECK(status IN ('QUEUED','SENDING','DELIVERED','BOUNCED','FAILED','SUPPRESSED')), attempt_count integer NOT NULL DEFAULT 0, last_error_code text, queued_at timestamptz NOT NULL DEFAULT clock_timestamp(), delivered_at timestamptz);
CREATE TABLE ops.queue_controls (queue_name text PRIMARY KEY, state text NOT NULL CHECK(state IN ('RUNNING','PAUSED_NEW','DRAINING','PAUSED')), reason text, version bigint NOT NULL DEFAULT 1, changed_by uuid REFERENCES ops.users(id), changed_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE TABLE core.parser_versions (parser_name text NOT NULL, version text NOT NULL, supported_media_types jsonb NOT NULL, implementation_digest char(64) NOT NULL, sandbox_profile text NOT NULL, status text NOT NULL CHECK(status IN ('ACTIVE','RETIRED','BLOCKED')), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(parser_name,version));
CREATE TABLE core.parser_runs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), source_document_id uuid NOT NULL REFERENCES raw.source_documents(id), parser_name text NOT NULL, parser_version text NOT NULL, status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','QUARANTINED')), output_record_count integer NOT NULL DEFAULT 0, output_digest char(64), error_code text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), FOREIGN KEY(parser_name,parser_version) REFERENCES core.parser_versions(parser_name,version));
CREATE TABLE intake.correction_request_drafts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), token_hash char(64) NOT NULL UNIQUE, version bigint NOT NULL DEFAULT 1, case_slug text, publication_revision integer, requester_type text, contact_email_hash char(64), contact_email_encrypted bytea, summary text, requested_changes jsonb NOT NULL DEFAULT '[]', evidence_description text, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp()); CREATE TRIGGER correction_request_drafts_updated_at BEFORE UPDATE ON intake.correction_request_drafts FOR EACH ROW EXECUTE FUNCTION ops.set_updated_at();
CREATE TABLE intake.dataset_export_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), request_token_hash char(64) NOT NULL UNIQUE, email_hash char(64), dataset_id text NOT NULL, format text NOT NULL CHECK(format IN ('CSV','JSONL','PARQUET')), filters jsonb NOT NULL, status text NOT NULL CHECK(status IN ('QUEUED','RUNNING','READY','FAILED','EXPIRED')), object_key text, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), completed_at timestamptz);
CREATE TABLE ops.oidc_transactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), state_hash char(64) NOT NULL UNIQUE, nonce_hash char(64) NOT NULL, pkce_verifier_encrypted bytea NOT NULL, safe_return_to text NOT NULL, action_digest char(64), expires_at timestamptz NOT NULL, consumed_at timestamptz, created_at timestamptz NOT NULL DEFAULT clock_timestamp());
COMMIT;
