import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "AUD-001",
  title: "감사 로그 Explorer",
  route: "/internal/audit",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "query",
      title: "감사 검색",
      component: "UnifiedSearch",
      purpose: "actor/action/object/time.",
      test_id: "aud_001__section__query",
    },
    {
      order: 2,
      id: "filters",
      title: "risk·surface·result",
      component: "UnifiedSearch",
      purpose: "high impact.",
      test_id: "aud_001__section__filters",
    },
    {
      order: 3,
      id: "events",
      title: "이벤트",
      component: "StructuredContentSection",
      purpose: "reason·policy·receipt.",
      test_id: "aud_001__section__events",
    },
    {
      order: 4,
      id: "integrity",
      title: "무결성",
      component: "StructuredContentSection",
      purpose: "sequence/hash/gap.",
      test_id: "aud_001__section__integrity",
    },
    {
      order: 5,
      id: "export",
      title: "export",
      component: "StructuredContentSection",
      purpose: "scope·watermark.",
      test_id: "aud_001__section__export",
    },
  ],
  actions: [
    {
      id: "open-event",
      label: "이벤트 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "export",
      label: "감사 export 요청",
      capability: "audit.export",
      operation_id: "createAuditExport",
      guard:
        "bounded range + exact scope + reason + watermark policy + expiry + step-up",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "verify-integrity",
      label: "무결성 검증",
      capability: "audit.read",
      operation_id: "verifyAuditIntegrity",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "searchAuditEvents",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/search-audit-events",
      blocking: true,
      response_schema: "AuditEventsSearchResultPage",
    },
    {
      operation_id: "verifyAuditIntegrity",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/verify-audit-integrity",
      blocking: false,
      response_schema: "verifyAuditIntegrityResult",
    },
    {
      operation_id: "createAuditExport",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-audit-export",
      blocking: false,
      response_schema: "createAuditExportReceipt",
    },
    {
      operation_id: "getAuditExport",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-audit-export",
      blocking: false,
      response_schema: "AuditExportResponse",
    },
  ],
} as const satisfies ScreenViewModel;
