import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-010",
  title: "업체 상세",
  route: "/suppliers/{supplierSlug}",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "업체 식별 정보",
      component: "KnownUnknownResponse",
      purpose: "업체 공식명·식별 정보·변경 이력·확인 한계.",
      test_id: "pub_010__section__identity",
    },
    {
      order: 2,
      id: "coverage",
      title: "수집 범위",
      component: "CoverageStatement",
      purpose: "source·기간.",
      test_id: "pub_010__section__coverage",
    },
    {
      order: 3,
      id: "metrics",
      title: "계약 현황 통계",
      component: "ComparisonWorkbench",
      purpose: "계약·기관 분포와 denominator.",
      test_id: "pub_010__section__metrics",
    },
    {
      order: 4,
      id: "contracts",
      title: "계약",
      component: "StructuredContentSection",
      purpose: "관측된 계약.",
      test_id: "pub_010__section__contracts",
    },
    {
      order: 5,
      id: "cases",
      title: "공개 사건",
      component: "StatusAndRevisionHeader",
      purpose: "상태별.",
      test_id: "pub_010__section__cases",
    },
    {
      order: 6,
      id: "corrections",
      title: "설명·정정",
      component: "RevisionAndCorrectionPanel",
      purpose: "identity 수정 포함.",
      test_id: "pub_010__section__corrections",
    },
    {
      order: 7,
      id: "relationships",
      title: "확인된 관계",
      component: "KnownUnknownResponse",
      purpose: "공식 자료로 확인된 관계만.",
      test_id: "pub_010__section__relationships",
    },
  ],
  actions: [
    {
      id: "view-contract",
      label: "계약 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-case",
      label: "사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe-supplier",
      label: "업체 업데이트 구독",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getSupplier",
      api: "public-api",
      method: "GET",
      path: "/v1/suppliers/{supplierId}",
      blocking: true,
      response_schema: "SupplierResponse",
    },
    {
      operation_id: "listSupplierContracts",
      api: "public-api",
      method: "GET",
      path: "/v1/suppliers/{supplierId}/contracts",
      blocking: true,
      response_schema: "SupplierContractsPage",
    },
    {
      operation_id: "listSupplierCases",
      api: "public-api",
      method: "GET",
      path: "/v1/suppliers/{supplierId}/cases",
      blocking: true,
      response_schema: "SupplierCasesPage",
    },
  ],
} as const satisfies ScreenViewModel;
