import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-019",
  title: "정정 상세",
  route: "/corrections/{correctionId}",
  archetype: "EVIDENCE_LANDING",
  sections: [
    {
      order: 1,
      id: "status",
      title: "정정 유형·시각",
      component: "StatusAndRevisionHeader",
      purpose: "correction/retraction과 effective time.",
      test_id: "pub_019__section__status",
    },
    {
      order: 2,
      id: "target",
      title: "대상",
      component: "StatusAndRevisionHeader",
      purpose: "사건·revision·claim.",
      test_id: "pub_019__section__target",
    },
    {
      order: 3,
      id: "before-after",
      title: "변경 전후",
      component: "ComparisonWorkbench",
      purpose: "정확한 값·문구 비교.",
      test_id: "pub_019__section__before-after",
    },
    {
      order: 4,
      id: "reason",
      title: "이유와 근거",
      component: "EvidenceLedger",
      purpose: "root cause와 evidence.",
      test_id: "pub_019__section__reason",
    },
    {
      order: 5,
      id: "impact",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "페이지·API·download·알림.",
      test_id: "pub_019__section__impact",
    },
    {
      order: 6,
      id: "review",
      title: "검토 절차",
      component: "RevisionTimeline",
      purpose: "공개 가능한 승인 정보.",
      test_id: "pub_019__section__review",
    },
  ],
  actions: [
    {
      id: "open-case",
      label: "대상 사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-old-revision",
      label: "이전 revision 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "copy-citation",
      label: "정정 인용",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getCorrection",
      api: "public-api",
      method: "GET",
      path: "/v1/corrections/{correctionId}",
      blocking: true,
      response_schema: "CorrectionResponse",
    },
  ],
} as const satisfies ScreenViewModel;
