import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-005",
  title: "사건 공개 revision",
  route: "/cases/{caseSlug}/revisions/{revision}",
  archetype: "EVIDENCE_LANDING",
  sections: [
    {
      order: 1,
      id: "revision-banner",
      title: "revision 안내",
      component: "StatusAndRevisionHeader",
      purpose: "과거본 여부와 최신본 링크.",
      test_id: "pub_005__section__revision-banner",
    },
    {
      order: 2,
      id: "snapshot",
      title: "불변 공개 내용",
      component: "KnownUnknownResponse",
      purpose: "해당 시점의 claim·evidence·response.",
      test_id: "pub_005__section__snapshot",
    },
    {
      order: 3,
      id: "diff",
      title: "변경 요약",
      component: "StatusAndRevisionHeader",
      purpose: "다음/이전 revision과 차이.",
      test_id: "pub_005__section__diff",
    },
    {
      order: 4,
      id: "citation",
      title: "인용 정보",
      component: "StatusAndRevisionHeader",
      purpose: "stable URL·timestamp·revision.",
      test_id: "pub_005__section__citation",
    },
  ],
  actions: [
    {
      id: "view-latest",
      label: "최신 revision 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "compare",
      label: "변경 비교",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "copy-citation",
      label: "이 revision 인용",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getPublicCaseRevision",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/revisions/{revision}",
      blocking: true,
      response_schema: "PublicCaseRevisionResponse",
    },
    {
      operation_id: "listCaseRevisions",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/revisions",
      blocking: true,
      response_schema: "CaseRevisionsPage",
    },
  ],
} as const satisfies ScreenViewModel;
