import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-030",
  title: "구독 관리",
  route: "/subscription/manage",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "구독 확인",
      component: "KnownUnknownResponse",
      purpose: "마스킹 이메일.",
      test_id: "pub_030__section__identity",
    },
    {
      order: 2,
      id: "topics",
      title: "대상",
      component: "StructuredContentSection",
      purpose: "현재 구독.",
      test_id: "pub_030__section__topics",
    },
    {
      order: 3,
      id: "preferences",
      title: "이벤트·빈도",
      component: "StructuredContentSection",
      purpose: "수정.",
      test_id: "pub_030__section__preferences",
    },
    {
      order: 4,
      id: "delivery",
      title: "전송 상태",
      component: "StatusAndRevisionHeader",
      purpose: "bounce/suppression.",
      test_id: "pub_030__section__delivery",
    },
    {
      order: 5,
      id: "unsubscribe",
      title: "해지",
      component: "DataCollection",
      purpose: "명확한 결과.",
      test_id: "pub_030__section__unsubscribe",
    },
  ],
  actions: [
    {
      id: "save-preferences",
      label: "구독 설정 저장",
      capability: "none",
      operation_id: "updateSubscription",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "unsubscribe",
      label: "구독 해지",
      capability: "none",
      operation_id: "unsubscribe",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "exchangeSubscriptionManagementToken",
      api: "submission-api",
      method: "POST",
      path: "/v1/submission-session/subscription-management:exchange",
      blocking: true,
      response_schema: "ExchangeSubmissionSessionResult",
    },
    {
      operation_id: "getSubscription",
      api: "submission-api",
      method: "GET",
      path: "/v1/subscription-session",
      blocking: true,
      response_schema: "SubscriptionResponse",
    },
    {
      operation_id: "updateSubscription",
      api: "submission-api",
      method: "PATCH",
      path: "/v1/subscription-session",
      blocking: true,
      response_schema: "updateSubscriptionReceipt",
    },
    {
      operation_id: "unsubscribe",
      api: "submission-api",
      method: "POST",
      path: "/v1/subscription-session:unsubscribe",
      blocking: true,
      response_schema: "unsubscribeReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
