/**
 * Browser-facing labels for closed uppercase enum values.
 *
 * Keep protocol abbreviations and wire values out of this table only when
 * they are explicitly retained by `retainedTechnicalEnumValues`.
 */
export const ENUM_PRESENTATION_LABELS = {
  ABUSE_PROOF_INVALID: "오남용 방지 증명 오류",
  ACCEPT: "수락",
  ACCEPTED: "접수됨",
  ACCEPT_SUGGESTION: "제안 수락",
  ACCESS: "접근",
  ACKNOWLEDGE: "확인",
  ACKNOWLEDGED: "확인됨",
  ACTION_ASSIGNMENT_STATE_INVALID: "처리 배정 상태 오류",
  ACTION_DECISION_CLOSED: "처리 결정 종료됨",
  ACTION_KIND_MISMATCH: "처리 종류 불일치",
  ACTION_PREVIEW_STALE: "처리 미리보기 만료",
  ACTION_PROPOSAL_REQUIRED: "처리 제안 필요",
  ACTION_PROPOSAL_STALE: "처리 제안 만료",
  ACTIVE: "활성",
  ACTIVE_SESSION: "활성 세션",
  ACTOR_AND_TIME: "행위자와 시각",
  ACTOR_ASSERTION_REQUIRED: "행위자 증명 필요",
  AGENCY: "기관",
  ALLOWED: "허용됨",
  ALL: "전체",
  ALL_USERS: "전체 사용자",
  AMBIGUOUS: "식별 불명확",
  ANALYST: "분석 담당자",
  ANNOUNCED: "공고됨",
  ANONYMIZE: "익명화",
  ANONYMOUS: "익명",
  APPROVE: "승인",
  APPROVED: "승인됨",
  ASSIGNED: "배정됨",
  ASSET_RIGHTS_DECISION: "자료 권리 결정",
  ATTACHMENT_CONTENT_MISMATCH: "첨부 내용 불일치",
  ATTACHMENT_FINALIZE_MISMATCH: "첨부 완료 정보 불일치",
  ATTACHMENT_UPLOAD_TARGET_INVALID: "첨부 업로드 대상 오류",
  AUTHORITY_AGENT_RUN_HAS_NO_SAFETY_PROJECTION: "실행 안전 자료 없음",
  AUTHORITY_V1: "확인 자료 계약 v1",
  AUTHORSHIP: "작성 주체",
  AUTH_SYSTEM: "인증 시스템",
  AVAILABLE: "사용 가능",
  AWARDED: "낙찰됨",
  AWAIT_DECISION: "결정 대기",
  AWAIT_EXECUTION: "처리 대기",
  AWAIT_REVIEW: "검토 대기",
  AWAITING_APPROVAL: "승인 대기",
  AWAITING_RESPONSE: "답변 대기",
  BACKGROUND: "배경",
  BLOCKED: "차단됨",
  BOUNDED_PROVIDER_RETENTION: "제공자 제한 보관",
  BUDGET_BLOCKED: "예산으로 차단됨",
  CALCULATION: "계산",
  CANCELLED: "취소됨",
  CAPABILITY: "권한",
  CAPABILITY_ACTIVATION: "권한 활성화",
  CAPABILITY_UNAVAILABLE: "역량 사용 불가",
  CASE: "사건",
  CASE_CLOSED_AT: "사건 종료 시각",
  CASE_UPDATED: "사건 갱신됨",
  CASES: "사건",
  CENTRAL: "중앙 기관",
  CHANGES_REQUIRED: "변경 필요",
  CLAIM: "주장",
  CLAIMS: "주장",
  CLASSIFICATION_BANNER: "분류 안내",
  CLEAN: "이상 없음",
  CLOSED: "종료됨",
  CLEAR: "해제됨",
  COMMAND: "명령",
  COMMAND_INPUT: "명령 입력",
  COMMERCIAL_CONTROL: "상업 운영 제어",
  COMMUNICATION: "연락",
  COMMUNICATION_AUTHORIZATION: "연락 승인",
  COMPACT_SINGLE_COLUMN: "좁은 화면 한 열",
  COMPARABLE: "비교 가능",
  COMPLETE: "완료",
  COMPLETED: "완료됨",
  CONFIGURED: "설정됨",
  CONFIRMED: "확인됨",
  CONFLICT: "충돌",
  CONFLICT_OF_INTEREST: "이해상충",
  CONTRACT: "계약",
  CONTEXT: "문맥",
  CONTRADICTS: "반박",
  CONTINUE: "계속",
  CONSENT_REVOKED_AT: "동의 철회 시각",
  CONSUMED_AT: "사용 시각",
  CONTROL_API: "제어 API",
  CORRECTED: "정정됨",
  CORRECTION: "정정",
  CORRECTION_DRAFT: "정정 초안",
  CORRECTION_RECEIPT: "정정 접수증",
  CORRECTIONS: "정정",
  COST_LEDGER_UNAVAILABLE: "비용 대장 없음",
  CREATED_AT: "생성 시각",
  CRYPTO_ERASE: "암호 삭제",
  CSRF_TOKEN_STALE: "요청 보호 토큰 만료",
  CURRENT: "현재",
  DAILY: "일간",
  DATASET: "데이터셋",
  DAY: "일",
  DECISION: "결정",
  DECISION_REVIEW: "결정 검토",
  DECLINE: "거절",
  DECLINED: "거절됨",
  DELETION: "삭제",
  DELIVERED: "전달됨",
  DELIVERED_AT: "전달 시각",
  DELIVERY_DISPUTE: "전달 이의",
  DEPENDENCY_BLOCKED: "선행 조건 차단",
  DESTRUCTIVE_CONFIRMATION: "중요 변경 확인",
  DETECTED: "감지됨",
  DISCLOSURE: "공개",
  DIRECT: "수의계약",
  DISCRETIONARY_EXTERNAL: "선택적 외부 처리",
  DISMISS: "기각",
  DOCUMENT: "문서",
  DOCUMENT_ANALYSIS: "문서 분석",
  DOWNLOAD: "내려받기",
  DRAFT: "초안",
  DUE_ASC: "기한 빠른 순",
  DUPLICATE: "중복",
  E2E_REVIEW: "E2E 검토",
  EMAIL: "이메일",
  EMAIL_LINK: "이메일 링크",
  EDITORIAL_REVIEW: "편집 검토",
  EMPTY: "자료 없음",
  ENTITY_DETAIL: "항목 상세",
  ERROR: "오류",
  EVIDENCE: "근거",
  EVIDENCE_CHANGED: "근거 변경됨",
  EVIDENCE_LANDING: "근거 시작",
  EVIDENCE_SEGMENT: "근거 구간",
  EXECUTION_RECEIPT_INCOMPLETE: "실행 접수증 불완전",
  EXTERNAL_COMMUNICATION: "외부 연락",
  EXTERNAL_LINK: "외부 링크",
  EXPIRED: "만료됨",
  EXPIRES_AT: "만료 시각",
  FACT: "사실",
  FACTUAL: "사실 관계",
  FAILED: "실패",
  FINALIZED: "확정됨",
  FORBIDDEN: "접근 금지",
  FORECAST_OWNER_FACT_MISSING: "예측 책임 근거 없음",
  FRESH: "최신",
  FULL: "전체 범위",
  FUNDING_DISCLOSURE: "재원 공개",
  GLOBAL: "전체",
  GUIDED_FORM: "단계별 입력",
  HANDOFF_STATE_INVALID: "인계 상태 오류",
  HIGH: "높음",
  HOST_ONLY: "호스트 전용",
  HUMAN: "사람",
  HYPOTHESIS: "가설",
  IDEMPOTENCY_KEY_REQUIRED: "중복 방지 키 필요",
  IDEMPOTENCY_REQUEST_CONFLICT: "중복 방지 요청 충돌",
  IMMEDIATE: "즉시",
  LAST_MATERIAL_USE_AT: "마지막 주요 사용 시각",
  INFERENCE: "추론",
  INTERNAL_MATERIALIZATION: "내부 자료화",
  INTERNAL_OBJECT: "내부 객체",
  INVALID_ATTACHMENT_METADATA: "첨부 정보 오류",
  INVALID_DATASET_EXPORT: "자료 내보내기 오류",
  INVALID_PARAMETER: "매개변수 오류",
  INVALID_REQUEST: "요청 오류",
  INVESTIGATING: "조사 중",
  IN_PROGRESS: "진행 중",
  JOB: "작업",
  KILL_SWITCH: "킬 스위치",
  LEGAL_HOLD: "법적 보존",
  LEGAL_REVIEW: "법률 검토",
  LIMITATION: "제한",
  LINK_TO_CASE: "사건에 연결",
  LOADING: "불러오는 중",
  LOCAL_ONLY: "로컬 전용",
  LOW: "낮음",
  MARK_DUPLICATE: "중복 표시",
  MATERIAL: "중요",
  MEDIAN: "중앙값",
  MEDIUM: "보통",
  MEDIUM_REFLOW: "중간 화면 재배치",
  METHODOLOGY: "방법론",
  METRIC: "지표",
  MOCK_OPENAPI_RESPONSE_INVALID: "검증 응답 계약 오류",
  MOCK_READ_RESPONSE_SAMPLE_MISSING: "조회 응답 표본 없음",
  MOCK_SUBMISSION_READ_UNHANDLED: "제출 조회 처리 없음",
  MODEL: "모델",
  MY_WORK: "내 작업",
  NAVIGATION: "이동",
  NEEDS_DATA: "자료 필요",
  NEEDS_INFORMATION: "추가 정보 필요",
  NEVER_PUBLISHED: "게시 이력 없음",
  NEW: "신규",
  NEWEST: "최신 순",
  NONE: "없음",
  NOT_APPLICABLE: "해당 없음",
  NOT_DUE: "기한 전",
  NOT_REQUESTED: "요청 전",
  NOT_RUN: "실행 전",
  NOT_STARTED: "시작 전",
  NO_PAID_EFFECT: "유료 영향 없음",
  NORMAL: "보통",
  OBJECT: "객체",
  OBJECT_SCOPE_MISMATCH: "대상 범위 불일치",
  OFFICIAL_OUTCOME: "공식 결과",
  OFFICIAL_RECORD: "공식 기록",
  OFFICIALLY_CONFIRMED: "공식 확인됨",
  OIDC_TRANSACTION_INVALID: "OIDC 인증 거래 오류",
  ONE_TIME_TOKEN_INVALID: "일회용 토큰 오류",
  ONE_TIME_TOKEN_REQUIRED: "일회용 토큰 필요",
  OPEN: "열림",
  OPEN_BID: "공개 입찰",
  OPERATIONAL_CONTROL: "운영 제어",
  OPERATIONS: "운영",
  OTHER: "기타",
  OWNER_UNAVAILABLE: "담당자 부재",
  ORGANIZATION_NAME: "조직명",
  PARTIAL: "일부 확인",
  PASS: "통과",
  PASSED: "통과됨",
  PENDING: "대기 중",
  PENDING_ACK: "확인 대기",
  PENDING_QUORUM: "정족수 대기",
  PENDING_VERIFICATION: "검증 대기",
  PAUSE_AND_DRAIN: "신규 중단 후 완료 대기",
  PAUSE_NEW: "신규 처리 중단",
  PERSONAL_DATA: "개인정보",
  POLICY: "정책",
  POLICY_BLOCKED: "정책으로 차단됨",
  PRESENT: "있음",
  PRESERVE_IDENTITY_GRAPH: "신원 그래프 보존",
  PRESERVE_PUBLIC_REVISION: "공개 개정본 보존",
  PRESERVE_REFERENCED_REVISION: "참조 개정본 보존",
  PRESERVE_WITH_PARENT: "상위 기록과 함께 보존",
  PRIMARY: "기본",
  PRIMARY_REVIEWER: "주 검토자",
  PRICE_OBSERVATION: "가격 관측",
  PROMOTE_TO_CASE: "사건으로 전환",
  PROVIDER_CONTROL: "제공자 제어",
  PROVIDER_CONTROL_REVIEW: "제공자 제어 검토",
  PROVIDER: "제공자",
  PUBLIC: "공개",
  PUBLICATION: "공개",
  PUBLISHED: "게시됨",
  PUBLISHED_ANOMALY: "이상 징후 게시됨",
  PUBLISHED_EXPLAINED: "소명 병기 게시됨",
  QUERY: "검색 조건",
  QUEUE: "대기열",
  QUEUED: "대기열 등록",
  RANGE: "범위",
  READY: "준비됨",
  READY_TO_PUBLISH: "게시 준비 완료",
  RECEIVED: "받음",
  RECEIVER_DECLINED: "수신자 거절",
  RECONCILIATION_REQUIRED: "상태 확인 필요",
  REGION: "지역",
  REGRESSION: "회귀",
  RECUSE: "회피",
  REJECT: "반려",
  REJECTED: "반려됨",
  REJECT_SUGGESTION: "제안 반려",
  REOPEN_RESPONSE: "답변 다시 열기",
  RESOLVED: "해결됨",
  RESOURCE_NOT_FOUND: "자료를 찾을 수 없음",
  RESPONSE_ACTIVE: "답변 진행 중",
  RESPONSE_PENDING: "답변 대기",
  RESPONSE_RECEIPT: "답변 접수증",
  RESPONSE_POLICY_CALENDAR: "답변 정책 일정",
  RESPONDS: "응답",
  RESPONSE: "답변",
  RESTRICTED: "제한됨",
  RETENTION: "보관",
  RETENTION_SCHEDULE: "보관 일정",
  RETRACTION: "철회",
  RETRACTED: "철회됨",
  REVIEW: "검토",
  REVIEW_REFUSAL_NOTICE: "거절 통지 확인",
  REVIEW_REQUIRED: "검토 필요",
  REVISION_PUBLISHED: "개정본 게시됨",
  ROLE: "역할",
  ROLE_GRANT: "역할 부여",
  ROLE_ONLY: "역할만",
  RULE: "규칙",
  RULE_ACTIVATION: "규칙 활성화",
  RUNNING: "실행 중",
  RUN_STARTED: "실행 시작됨",
  SAME_LOGICAL_EVENT: "동일 사건 흐름",
  SAME_SOURCE: "동일 출처",
  SAME_TARGET: "동일 대상",
  SAVED: "저장됨",
  SEALED_BFF_SESSION_SYNCHRONIZER: "봉인된 세션 요청 보호",
  SEARCH: "검색",
  SEARCH_INDEX: "검색 색인",
  SELF_DECLARED: "직접 밝힘",
  SHADOW: "시범 적용",
  SHADOW_THEN_ALL: "시범 후 전체 적용",
  SERVICE_ASSERTION_REQUIRED: "서비스 증명 필요",
  SESSION_NOT_ACTIVE: "활성 세션 아님",
  SETTLED: "정산됨",
  SIGNAL: "신호",
  SIGNALS: "신호",
  SIGNAL_DETECTED: "탐지 신호 있음",
  SKEPTIC: "반대 검토자",
  SMTP_EMAIL: "SMTP 이메일",
  SOURCE: "출처",
  SOURCE_FIELD: "출처 필드",
  SNAPSHOT_STALE: "검토본 만료",
  STALE: "최신 아님",
  START_REVIEW: "검토 시작",
  STEP_UP: "추가 인증",
  STEP_UP_TRANSACTION_INVALID: "추가 인증 거래 오류",
  STRUCTURED_CHANGE: "구조화 변경",
  SUBMISSION_SESSION_REQUIRED: "제출 세션 필요",
  SUBMITTED: "제출됨",
  SUBSCRIPTION_MANAGEMENT: "구독 관리",
  SUBSCRIPTION_PENDING: "구독 확인 대기",
  SUBJECT_INVALID: "대상 오류",
  SUCCEEDED: "성공",
  SUPERSEDED_AT: "대체 시각",
  SUPPLIER: "업체",
  SUPPORTS: "뒷받침",
  SUPPORTED: "근거로 뒷받침됨",
  SYNTHETIC: "합성 자료",
  SYNTHETIC_READ_ONLY: "합성 읽기 전용",
  SYNTHETIC_TEST: "합성 검증",
  TAIL: "최신 구간",
  TASK: "작업",
  TERMINAL: "종료됨",
  TERMINAL_AT: "종료 시각",
  TEMPORARILY_RESTRICTED: "일시 공개 제한",
  TEST_ONLY: "테스트 전용",
  TRIAGE: "분류 검토",
  TURNSTILE: "Turnstile",
  UNCONFIGURED: "설정 안 됨",
  UNDER_REVIEW: "검토 중",
  UNKNOWN: "알 수 없음",
  UNMATCHED: "일치 없음",
  UNVERIFIED: "미확인",
  URGENT: "긴급",
  USER: "사용자",
  UPDATED_AT: "갱신 시각",
  UPDATED_DESC: "최근 갱신순",
  UPSTREAM_TEMPORARY_FAILURE: "연결 대상 일시 오류",
  VALIDATED: "검증됨",
  VALIDATION_FAILED: "검증 실패",
  VERIFICATION_FAILED: "확인 실패",
  VERIFICATION_TOKEN_REQUIRED: "확인 토큰 필요",
  VERIFIED: "확인됨",
  VERIFY_IDENTITY: "신원 확인",
  VERSION_CONFLICT: "버전 충돌",
  AGENCY_IDENTIFIER: "기관 식별자",
  AGENCY_MASTER: "기관 식별 원장",
  ENTITY_ALIAS: "기관·업체 별칭",
  ENTITY_RETENTION_SNAPSHOT: "기관·업체 보존 기준 스냅샷",
  LEGAL_HOLD_GOVERNANCE: "법적 보존 처리 기록",
  NAMED_PERSON_PUBLICATION_GOVERNANCE: "자연인 실명 공개 판정 기록",
  PERSON_ERASURE_GOVERNANCE: "자연인 문맥 삭제 기록",
  PRIVACY_REQUEST: "개인정보 권리행사 요청",
  PRIVACY_REQUEST_EXECUTION: "권리행사 결정·실행 기록",
  PRIVACY_REQUEST_NOTICE: "권리행사 통지 기록",
  PRIVACY_REQUEST_TOKEN: "권리행사 일회용 토큰",
  RELATIONSHIP_PERSON_CONTEXT: "자연인 성명·직책 문맥",
  RELATIONSHIP_PERSON_TOPOLOGY: "자연인 관계 위상",
  RESPONSE_IDENTITY_GOVERNANCE: "소명 조직 신원 판정 기록",
  SUPPLIER_IDENTIFIER: "업체 식별자",
  SUPPLIER_MASTER: "업체 식별 원장",
  WEEKLY: "주간",
  WIDE_AUTHORITY_LAYOUT: "넓은 화면 자료 배치",
  WITHDRAWN: "철회됨",
  WITHIN_LIMIT: "한도 이내",
  WORKSPACE: "작업 공간",
  WORKLOAD_CAPACITY: "업무 수용 한도",
  ZERO_RETENTION: "보관 안 함",
} as const satisfies Readonly<Record<string, string>>;
