// Generated from specs/ui/effective-screen-contracts.yaml; do not hand-edit.
export const ROUTE_SCREEN_CONTRACTS = {
  "ACC-001": {
    route: "/internal/account",
    objectLabel: "내 계정·세션",
    persona: "조사 담당자",
    primaryActionId: "revoke-session",
    primaryActionLabel: "다른 세션 종료",
    sections: [{ id: "identity", region: "object", testId: "acc_001__section__identity", component: "StructuredContentSection", fields: ["account_id", "account_version"] }, { id: "roles", region: "state", testId: "acc_001__section__roles", component: "AccessManagementPanel", fields: ["role_projection"] }, { id: "sessions", region: "answer", testId: "acc_001__section__sessions", component: "StructuredContentSection", fields: ["roles_and_sessions", "session_actions", "session_summary"] }, { id: "security", region: "state", testId: "acc_001__section__security", component: "StructuredContentSection", fields: ["account_state", "security_evidence", "updated_at"] }, { id: "notifications", region: "state", testId: "acc_001__section__notifications", component: "StructuredContentSection", fields: ["notification_projection"] }, { id: "access-request", region: "unknown", testId: "acc_001__section__access-request", component: "StatusAndRevisionHeader", fields: ["access_request_unknowns"] }],
  },
  "ADM-001": {
    route: "/internal/admin/users",
    objectLabel: "사용자·접근 관리",
    persona: "조사 담당자",
    primaryActionId: "review-access",
    primaryActionLabel: "접근 검토 시작",
    sections: [{ id: "summary", region: "object", testId: "adm_001__section__summary", component: "StatusAndRevisionHeader", fields: ["summary_object"] }, { id: "filters", region: "state", testId: "adm_001__section__filters", component: "UnifiedSearch", fields: ["user_filters"] }, { id: "users", region: "answer", testId: "adm_001__section__users", component: "DataCollection", fields: ["users_answer"] }, { id: "requests", region: "unknown", testId: "adm_001__section__requests", component: "StructuredContentSection", fields: ["requests_unknown"] }, { id: "review", region: "state", testId: "adm_001__section__review", component: "DecisionReviewPanel", fields: ["review_evidence", "review_next_action", "review_state"] }],
  },
  "ADM-002": {
    route: "/internal/admin/users/{userId}",
    objectLabel: "사용자 상세·역할",
    persona: "조사 담당자",
    primaryActionId: "grant-role",
    primaryActionLabel: "역할 부여",
    sections: [{ id: "identity", region: "object", testId: "adm_002__section__identity", component: "StatusAndRevisionHeader", fields: ["access_version", "user_id"] }, { id: "roles", region: "answer", testId: "adm_002__section__roles", component: "AccessManagementPanel", fields: ["role_summary", "roles_and_sessions"] }, { id: "conflicts", region: "state", testId: "adm_002__section__conflicts", component: "AccessManagementPanel", fields: ["access_state", "conflicts", "updated_at"] }, { id: "sessions", region: "state", testId: "adm_002__section__sessions", component: "StructuredContentSection", fields: ["session_projection"] }, { id: "requests", region: "next_action", testId: "adm_002__section__requests", component: "StructuredContentSection", fields: ["access_change_actions"] }, { id: "activity", region: "evidence", testId: "adm_002__section__activity", component: "CoverageStatement", fields: ["activity_evidence"] }, { id: "offboarding", region: "state", testId: "adm_002__section__offboarding", component: "StructuredContentSection", fields: ["offboarding_projection"] }],
  },
  "ADM-003": {
    route: "/internal/admin/roles",
    objectLabel: "역할 정의",
    persona: "조사 담당자",
    primaryActionId: "propose-change",
    primaryActionLabel: "역할 변경 제안",
    sections: [{ id: "catalog", region: "object", testId: "adm_003__section__catalog", component: "StatusAndRevisionHeader", fields: ["catalog_object"] }, { id: "capabilities", region: "answer", testId: "adm_003__section__capabilities", component: "StructuredContentSection", fields: ["capabilities_answer"] }, { id: "conflicts", region: "unknown", testId: "adm_003__section__conflicts", component: "AccessManagementPanel", fields: ["conflicts_unknown"] }, { id: "grants", region: "state", testId: "adm_003__section__grants", component: "StructuredContentSection", fields: ["grant_projection"] }, { id: "review", region: "state", testId: "adm_003__section__review", component: "DecisionReviewPanel", fields: ["review_next_action", "review_state"] }, { id: "history", region: "evidence", testId: "adm_003__section__history", component: "RevisionTimeline", fields: ["history_evidence"] }],
  },
  "AUD-001": {
    route: "/internal/audit",
    objectLabel: "감사 로그 Explorer",
    persona: "조사 담당자",
    primaryActionId: "verify-integrity",
    primaryActionLabel: "무결성 검증",
    sections: [{ id: "query", region: "object", testId: "aud_001__section__query", component: "UnifiedSearch", fields: ["query_object"] }, { id: "filters", region: "state", testId: "aud_001__section__filters", component: "UnifiedSearch", fields: ["audit_filters"] }, { id: "events", region: "answer", testId: "aud_001__section__events", component: "StructuredContentSection", fields: ["events_answer", "events_next_action", "events_unknown"] }, { id: "integrity", region: "state", testId: "aud_001__section__integrity", component: "StructuredContentSection", fields: ["integrity_evidence", "integrity_state"] }, { id: "export", region: "state", testId: "aud_001__section__export", component: "StructuredContentSection", fields: ["export_projection"] }],
  },
  "AUTH-001": {
    route: "/auth/sign-in",
    objectLabel: "직원 로그인",
    persona: "조사 담당자",
    primaryActionId: "sign-in",
    primaryActionLabel: "조직 계정으로 로그인",
    sections: [{ id: "environment", region: "object", testId: "auth_001__section__environment", component: "StructuredContentSection", fields: ["identity_provider_label", "login_attempt_id", "login_status", "updated_at"] }, { id: "signin", region: "answer", testId: "auth_001__section__signin", component: "StructuredContentSection", fields: ["sign_in_action", "sign_in_guidance"] }, { id: "support", region: "evidence", testId: "auth_001__section__support", component: "AccessManagementPanel", fields: ["environment_limitations", "support_links"] }],
  },
  "AUTH-002": {
    route: "/auth/verify",
    objectLabel: "MFA·재인증",
    persona: "조사 담당자",
    primaryActionId: "verify",
    primaryActionLabel: "추가 인증 시작",
    sections: [{ id: "reason", region: "object", testId: "auth_002__section__reason", component: "StructuredContentSection", fields: ["action_context", "challenge_state", "method_unknowns"] }, { id: "methods", region: "answer", testId: "auth_002__section__methods", component: "StructuredContentSection", fields: ["available_methods", "verify_action"] }, { id: "recovery", region: "evidence", testId: "auth_002__section__recovery", component: "StructuredContentSection", fields: ["recovery_receipt"] }],
  },
  "AUTH-003": {
    route: "/auth/access-denied",
    objectLabel: "접근 권한 없음",
    persona: "조사 담당자",
    primaryActionId: "request-access",
    primaryActionLabel: "접근 권한 요청",
    sections: [{ id: "message", region: "object", testId: "auth_003__section__message", component: "StatusAndRevisionHeader", fields: ["access_context", "access_status", "actor_id", "denial_category", "policy_version", "safe_reason_scope"] }, { id: "actions", region: "next_action", testId: "auth_003__section__actions", component: "StructuredContentSection", fields: ["access_request_action"] }, { id: "reference", region: "evidence", testId: "auth_003__section__reference", component: "StructuredContentSection", fields: ["policy_reference"] }],
  },
  "AUTH-004": {
    route: "/auth/session-expired",
    objectLabel: "세션 만료",
    persona: "조사 담당자",
    primaryActionId: "sign-in-again",
    primaryActionLabel: "다시 로그인",
    sections: [{ id: "status", region: "object", testId: "auth_004__section__status", component: "StatusAndRevisionHeader", fields: ["reauth_attempt_id", "reauth_status", "session_context", "updated_at"] }, { id: "draft", region: "answer", testId: "auth_004__section__draft", component: "StatusAndRevisionHeader", fields: ["draft_preservation_summary", "draft_unknowns"] }, { id: "signin", region: "next_action", testId: "auth_004__section__signin", component: "StructuredContentSection", fields: ["sign_in_action"] }, { id: "support", region: "evidence", testId: "auth_004__section__support", component: "StructuredContentSection", fields: ["support_reference"] }],
  },
  "CAS-001": {
    route: "/internal/cases",
    objectLabel: "사건 Queue",
    persona: "조사 담당자",
    primaryActionId: "assign",
    primaryActionLabel: "담당자 지정",
    sections: [{ id: "views", region: "object", testId: "cas_001__section__views", component: "DataCollection", fields: ["views_object"] }, { id: "filters", region: "unknown", testId: "cas_001__section__filters", component: "UnifiedSearch", fields: ["filters_unknown"] }, { id: "table", region: "state", testId: "cas_001__section__table", component: "StructuredContentSection", fields: ["table_answer", "table_next_action", "table_state"] }, { id: "assignment", region: "evidence", testId: "cas_001__section__assignment", component: "StructuredContentSection", fields: ["assignment_evidence"] }],
  },
  "CAS-002": {
    route: "/internal/cases/{caseId}/overview",
    objectLabel: "사건 Overview",
    persona: "조사 담당자",
    primaryActionId: "transition",
    primaryActionLabel: "상태 전이",
    sections: [{ id: "header", region: "object", testId: "cas_002__section__header", component: "StructuredContentSection", fields: ["case_id", "case_title"] }, { id: "known-unknown", region: "answer", testId: "cas_002__section__known-unknown", component: "KnownUnknownResponse", fields: ["answer_first_summary", "known_unknowns", "readiness"] }, { id: "readiness", region: "state", testId: "cas_002__section__readiness", component: "StructuredContentSection", fields: ["case_status", "case_version"] }, { id: "next", region: "next_action", testId: "cas_002__section__next", component: "AccessManagementPanel", fields: ["next_case_tasks"] }, { id: "activity", region: "evidence", testId: "cas_002__section__activity", component: "StructuredContentSection", fields: ["activity_and_evidence"] }],
  },
  "CAS-003": {
    route: "/internal/cases/{caseId}/signals",
    objectLabel: "연결된 Signal",
    persona: "조사 담당자",
    primaryActionId: "link-signal",
    primaryActionLabel: "signal 연결",
    sections: [{ id: "summary", region: "object", testId: "cas_003__section__summary", component: "ComparisonWorkbench", fields: ["summary_object"] }, { id: "signals", region: "answer", testId: "cas_003__section__signals", component: "DataCollection", fields: ["signals_answer", "signals_next_action"] }, { id: "relationships", region: "state", testId: "cas_003__section__relationships", component: "StructuredContentSection", fields: ["relationships_evidence", "relationships_state", "relationships_unknown"] }],
  },
  "CAS-004": {
    route: "/internal/cases/{caseId}/evidence",
    objectLabel: "근거",
    persona: "조사 담당자",
    primaryActionId: "add-evidence",
    primaryActionLabel: "근거 추가",
    sections: [{ id: "matrix", region: "object", testId: "cas_004__section__matrix", component: "EvidenceLedger", fields: ["matrix_evidence", "matrix_object"] }, { id: "filters", region: "state", testId: "cas_004__section__filters", component: "UnifiedSearch", fields: ["evidence_filters"] }, { id: "list", region: "answer", testId: "cas_004__section__list", component: "EvidenceLedger", fields: ["list_answer", "list_next_action"] }, { id: "gaps", region: "state", testId: "cas_004__section__gaps", component: "EvidenceLedger", fields: ["gaps_state", "gaps_unknown"] }],
  },
  "CAS-005": {
    route: "/internal/cases/{caseId}/evidence/{evidenceId}",
    objectLabel: "근거 검증",
    persona: "조사 담당자",
    primaryActionId: "verify",
    primaryActionLabel: "근거 검증 완료",
    sections: [{ id: "source", region: "object", testId: "cas_005__section__source", component: "EvidenceLedger", fields: ["evidence_identity"] }, { id: "locator", region: "evidence", testId: "cas_005__section__locator", component: "StructuredContentSection", fields: ["provenance", "verification_evidence"] }, { id: "content", region: "answer", testId: "cas_005__section__content", component: "StructuredContentSection", fields: ["evidence_content", "source_context"] }, { id: "verification", region: "state", testId: "cas_005__section__verification", component: "StatusAndRevisionHeader", fields: ["verification_actions", "verification_state"] }, { id: "relationships", region: "state", testId: "cas_005__section__relationships", component: "ClaimWorkbench", fields: ["relationship_projection"] }, { id: "access", region: "unknown", testId: "cas_005__section__access", component: "StructuredContentSection", fields: ["access_unknowns", "redaction_unknowns"] }],
  },
  "CAS-006": {
    route: "/internal/cases/{caseId}/claims",
    objectLabel: "공개 Claim 작성",
    persona: "조사 담당자",
    primaryActionId: "add-claim",
    primaryActionLabel: "Claim 추가",
    sections: [{ id: "summary", region: "object", testId: "cas_006__section__summary", component: "ClaimWorkbench", fields: ["summary_object"] }, { id: "claims", region: "answer", testId: "cas_006__section__claims", component: "DataCollection", fields: ["claims_answer"] }, { id: "editor", region: "next_action", testId: "cas_006__section__editor", component: "StructuredContentSection", fields: ["editor_next_action"] }, { id: "lint", region: "state", testId: "cas_006__section__lint", component: "StructuredContentSection", fields: ["lint_state", "lint_unknown"] }, { id: "relationships", region: "evidence", testId: "cas_006__section__relationships", component: "KnownUnknownResponse", fields: ["relationships_evidence"] }],
  },
  "CAS-007": {
    route: "/internal/cases/{caseId}/hypotheses",
    objectLabel: "조사 가설",
    persona: "조사 담당자",
    primaryActionId: "add-hypothesis",
    primaryActionLabel: "가설 추가",
    sections: [{ id: "board", region: "object", testId: "cas_007__section__board", component: "StructuredContentSection", fields: ["board_answer", "board_next_action", "board_object"] }, { id: "matrix", region: "state", testId: "cas_007__section__matrix", component: "EvidenceLedger", fields: ["matrix_evidence", "matrix_state"] }, { id: "questions", region: "unknown", testId: "cas_007__section__questions", component: "KnownUnknownResponse", fields: ["questions_unknown"] }],
  },
  "CAS-008": {
    route: "/internal/cases/{caseId}/responses",
    objectLabel: "소명 관리",
    persona: "조사 담당자",
    primaryActionId: "approve-excerpt",
    primaryActionLabel: "공개 excerpt 승인",
    sections: [{ id: "requests", region: "object", testId: "cas_008__section__requests", component: "DataCollection", fields: ["requests_object"] }, { id: "submissions", region: "answer", testId: "cas_008__section__submissions", component: "GuidedFormSection", fields: ["submissions_answer"] }, { id: "verification", region: "state", testId: "cas_008__section__verification", component: "KnownUnknownResponse", fields: ["verification_state", "verification_unknown"] }, { id: "public-copy", region: "next_action", testId: "cas_008__section__public-copy", component: "StructuredContentSection", fields: ["public_copy_next_action"] }, { id: "timeline", region: "evidence", testId: "cas_008__section__timeline", component: "KnownUnknownResponse", fields: ["timeline_evidence"] }],
  },
  "CAS-009": {
    route: "/internal/cases/{caseId}/responses/new",
    objectLabel: "소명 요청 작성",
    persona: "조사 담당자",
    primaryActionId: "save-draft",
    primaryActionLabel: "요청 임시 저장",
    sections: [{ id: "target", region: "object", testId: "cas_009__section__target", component: "StructuredContentSection", fields: ["composer_id", "composer_version"] }, { id: "questions", region: "answer", testId: "cas_009__section__questions", component: "EvidenceLedger", fields: ["preview", "questions_and_target"] }, { id: "deadline", region: "state", testId: "cas_009__section__deadline", component: "StructuredContentSection", fields: ["deadline_projection"] }, { id: "disclosure", region: "unknown", testId: "cas_009__section__disclosure", component: "StatusAndRevisionHeader", fields: ["disclosure_unknowns"] }, { id: "preview", region: "evidence", testId: "cas_009__section__preview", component: "DecisionReviewPanel", fields: ["source_and_policy_evidence"] }, { id: "gate", region: "state", testId: "cas_009__section__gate", component: "StructuredContentSection", fields: ["composer_status", "review_action", "updated_at"] }],
  },
  "CAS-010": {
    route: "/internal/cases/{caseId}/agent-runs",
    objectLabel: "Agent 실행",
    persona: "조사 담당자",
    primaryActionId: "start-run",
    primaryActionLabel: "새 조사 실행",
    sections: [{ id: "runs", region: "object", testId: "cas_010__section__runs", component: "StatusAndRevisionHeader", fields: ["runs_evidence", "runs_next_action", "runs_object"] }, { id: "filters", region: "state", testId: "cas_010__section__filters", component: "UnifiedSearch", fields: ["agent_run_filters"] }, { id: "suggestions", region: "answer", testId: "cas_010__section__suggestions", component: "StatusAndRevisionHeader", fields: ["suggestions_answer"] }, { id: "budget", region: "state", testId: "cas_010__section__budget", component: "StructuredContentSection", fields: ["budget_state", "budget_unknown"] }],
  },
  "CAS-011": {
    route: "/internal/cases/{caseId}/agent-runs/{runId}",
    objectLabel: "Agent 실행 상세",
    persona: "조사 담당자",
    primaryActionId: "accept-suggestion",
    primaryActionLabel: "제안 채택",
    sections: [{ id: "identity", region: "object", testId: "cas_011__section__identity", component: "StructuredContentSection", fields: ["run_id", "run_version"] }, { id: "inputs", region: "state", testId: "cas_011__section__inputs", component: "EvidenceLedger", fields: ["agent_input_projection"] }, { id: "model", region: "state", testId: "cas_011__section__model", component: "StructuredContentSection", fields: ["provider_turn_projection"] }, { id: "output", region: "answer", testId: "cas_011__section__output", component: "AgentSuggestionPanel", fields: ["proposals", "typed_findings"] }, { id: "citations", region: "evidence", testId: "cas_011__section__citations", component: "EvidenceLedger", fields: ["tool_receipts", "verified_citations"] }, { id: "safety", region: "state", testId: "cas_011__section__safety", component: "SensitiveDataNotice", fields: ["counter_evidence", "run_status", "unknowns", "updated_at"] }, { id: "decisions", region: "next_action", testId: "cas_011__section__decisions", component: "AgentSuggestionPanel", fields: ["proposal_actions"] }, { id: "cost", region: "state", testId: "cas_011__section__cost", component: "MetricWithContext", fields: ["cost_projection"] }],
  },
  "CAS-012": {
    route: "/internal/cases/{caseId}/timeline",
    objectLabel: "사건 Timeline",
    persona: "조사 담당자",
    primaryActionId: "filter",
    primaryActionLabel: "이벤트 필터",
    sections: [{ id: "filters", region: "object", testId: "cas_012__section__filters", component: "UnifiedSearch", fields: ["filters_object"] }, { id: "timeline", region: "state", testId: "cas_012__section__timeline", component: "RevisionTimeline", fields: ["timeline_answer", "timeline_next_action", "timeline_state"] }, { id: "public-view", region: "unknown", testId: "cas_012__section__public-view", component: "RevisionTimeline", fields: ["public_view_unknown"] }, { id: "related", region: "evidence", testId: "cas_012__section__related", component: "StructuredContentSection", fields: ["related_evidence"] }],
  },
  "CAS-013": {
    route: "/internal/cases/{caseId}/review",
    objectLabel: "검토 준비도",
    persona: "조사 담당자",
    primaryActionId: "open-blocker",
    primaryActionLabel: "blocker 해결",
    sections: [{ id: "summary", region: "object", testId: "cas_013__section__summary", component: "StructuredContentSection", fields: ["case_id", "case_version", "gate_results", "readiness_summary"] }, { id: "gates", region: "state", testId: "cas_013__section__gates", component: "KnownUnknownResponse", fields: ["blocking_gaps", "evaluated_at", "readiness_status"] }, { id: "tasks", region: "next_action", testId: "cas_013__section__tasks", component: "StructuredContentSection", fields: ["blocker_actions"] }, { id: "reviews", region: "evidence", testId: "cas_013__section__reviews", component: "DecisionReviewPanel", fields: ["review_evidence"] }, { id: "snapshot", region: "state", testId: "cas_013__section__snapshot", component: "StructuredContentSection", fields: ["snapshot_receipt_projection"] }],
  },
  "CAS-014": {
    route: "/internal/cases/{caseId}/preview",
    objectLabel: "공개 Preview",
    persona: "조사 담당자",
    primaryActionId: "refresh-preview",
    primaryActionLabel: "Preview 재생성",
    sections: [{ id: "watermark", region: "object", testId: "cas_014__section__watermark", component: "StatusAndRevisionHeader", fields: ["preview_hash", "snapshot_id"] }, { id: "render", region: "answer", testId: "cas_014__section__render", component: "StructuredContentSection", fields: ["public_render", "rendered_routes"] }, { id: "checks", region: "state", testId: "cas_014__section__checks", component: "EvidenceLedger", fields: ["blocking_checks", "expires_at", "refresh_and_review_actions", "validation_state"] }, { id: "variants", region: "state", testId: "cas_014__section__variants", component: "StructuredContentSection", fields: ["route_variant_projection"] }, { id: "diff", region: "evidence", testId: "cas_014__section__diff", component: "RevisionAndCorrectionPanel", fields: ["render_digest", "validation_evidence"] }],
  },
  "CAS-015": {
    route: "/internal/cases/{caseId}/corrections",
    objectLabel: "사건 정정·철회",
    persona: "조사 담당자",
    primaryActionId: "start-correction",
    primaryActionLabel: "정정 작업 시작",
    sections: [{ id: "history", region: "object", testId: "cas_015__section__history", component: "StatusAndRevisionHeader", fields: ["history_object"] }, { id: "requests", region: "state", testId: "cas_015__section__requests", component: "StatusAndRevisionHeader", fields: ["request_projection"] }, { id: "proposal", region: "answer", testId: "cas_015__section__proposal", component: "RevisionAndCorrectionPanel", fields: ["proposal_answer", "proposal_next_action"] }, { id: "impact", region: "evidence", testId: "cas_015__section__impact", component: "StructuredContentSection", fields: ["impact_evidence"] }, { id: "reviews", region: "state", testId: "cas_015__section__reviews", component: "DecisionReviewPanel", fields: ["reviews_state", "reviews_unknown"] }],
  },
  "CAS-016": {
    route: "/internal/cases/{caseId}/audit",
    objectLabel: "사건 Audit",
    persona: "조사 담당자",
    primaryActionId: "open-event",
    primaryActionLabel: "이벤트 상세",
    sections: [{ id: "scope", region: "object", testId: "cas_016__section__scope", component: "StructuredContentSection", fields: ["scope_object"] }, { id: "filters", region: "state", testId: "cas_016__section__filters", component: "UnifiedSearch", fields: ["audit_filters"] }, { id: "events", region: "state", testId: "cas_016__section__events", component: "StructuredContentSection", fields: ["events_answer", "events_next_action", "events_state", "events_unknown"] }, { id: "exports", region: "evidence", testId: "cas_016__section__exports", component: "StructuredContentSection", fields: ["exports_evidence"] }],
  },
  "COR-001": {
    route: "/internal/corrections",
    objectLabel: "정정 Queue",
    persona: "조사 담당자",
    primaryActionId: "assign",
    primaryActionLabel: "담당자 배정",
    sections: [{ id: "urgent", region: "object", testId: "cor_001__section__urgent", component: "DataCollection", fields: ["urgent_object", "urgent_unknown"] }, { id: "filters", region: "state", testId: "cor_001__section__filters", component: "UnifiedSearch", fields: ["correction_filters"] }, { id: "requests", region: "state", testId: "cor_001__section__requests", component: "DataCollection", fields: ["requests_answer", "requests_evidence", "requests_next_action", "requests_state"] }, { id: "assignment", region: "state", testId: "cor_001__section__assignment", component: "StructuredContentSection", fields: ["assignment_projection"] }],
  },
  "COR-002": {
    route: "/internal/corrections/{correctionId}",
    objectLabel: "정정 Workspace",
    persona: "조사 담당자",
    primaryActionId: "reject-request",
    primaryActionLabel: "정정하지 않음 결정",
    sections: [{ id: "request", region: "object", testId: "cor_002__section__request", component: "EvidenceLedger", fields: ["correction_id", "correction_version"] }, { id: "original", region: "evidence", testId: "cor_002__section__original", component: "StatusAndRevisionHeader", fields: ["original_and_review_evidence"] }, { id: "investigation", region: "answer", testId: "cor_002__section__investigation", component: "StructuredContentSection", fields: ["investigation_summary", "proposed_correction"] }, { id: "proposal", region: "state", testId: "cor_002__section__proposal", component: "StructuredContentSection", fields: ["proposal_projection"] }, { id: "impact", region: "unknown", testId: "cor_002__section__impact", component: "StructuredContentSection", fields: ["impact_and_unknowns"] }, { id: "review", region: "state", testId: "cor_002__section__review", component: "DecisionReviewPanel", fields: ["decision_actions", "updated_at", "workspace_status"] }, { id: "receipt", region: "state", testId: "cor_002__section__receipt", component: "StatusAndRevisionHeader", fields: ["receipt_projection"] }],
  },
  "INT-001": {
    route: "/internal/dashboard",
    objectLabel: "운영 대시보드",
    persona: "조사 담당자",
    primaryActionId: "open-task",
    primaryActionLabel: "작업 열기",
    sections: [{ id: "critical", region: "object", testId: "int_001__section__critical", component: "RevisionAndCorrectionPanel", fields: ["job_evidence", "source_evidence", "task_scope"] }, { id: "my-work", region: "answer", testId: "int_001__section__my-work", component: "StructuredContentSection", fields: ["highest_value_work", "overdue_work", "task_actions"] }, { id: "incidents", region: "state", testId: "int_001__section__incidents", component: "OperationsStatusPanel", fields: ["incident_state", "job_health"] }, { id: "queues", region: "state", testId: "int_001__section__queues", component: "KnownUnknownResponse", fields: ["queue_projection"] }, { id: "cost", region: "unknown", testId: "int_001__section__cost", component: "StructuredContentSection", fields: ["cost_risk", "unread_unknowns"] }],
  },
  "INT-002": {
    route: "/internal/my-work",
    objectLabel: "내 작업",
    persona: "조사 담당자",
    primaryActionId: "reassign",
    primaryActionLabel: "재배정",
    sections: [{ id: "views", region: "object", testId: "int_002__section__views", component: "StructuredContentSection", fields: ["views_object"] }, { id: "tasks", region: "answer", testId: "int_002__section__tasks", component: "StructuredContentSection", fields: ["tasks_answer", "tasks_next_action"] }, { id: "filters", region: "state", testId: "int_002__section__filters", component: "UnifiedSearch", fields: ["task_filters"] }, { id: "handoff", region: "state", testId: "int_002__section__handoff", component: "StructuredContentSection", fields: ["handoff_evidence", "handoff_state", "handoff_unknown"] }],
  },
  "INT-003": {
    route: "/internal/search",
    objectLabel: "내부 검색",
    persona: "조사 담당자",
    primaryActionId: "submit-search",
    primaryActionLabel: "검색",
    sections: [{ id: "query", region: "object", testId: "int_003__section__query", component: "UnifiedSearch", fields: ["query_next_action", "query_object"] }, { id: "types", region: "state", testId: "int_003__section__types", component: "EvidenceLedger", fields: ["type_filters"] }, { id: "results", region: "state", testId: "int_003__section__results", component: "UnifiedSearch", fields: ["results_answer", "results_state", "results_unknown"] }, { id: "recent", region: "evidence", testId: "int_003__section__recent", component: "RevisionTimeline", fields: ["recent_evidence"] }],
  },
  "INT-004": {
    route: "/internal/notifications",
    objectLabel: "알림",
    persona: "조사 담당자",
    primaryActionId: "open",
    primaryActionLabel: "알림 대상 열기",
    sections: [{ id: "filters", region: "object", testId: "int_004__section__filters", component: "UnifiedSearch", fields: ["filters_object"] }, { id: "notifications", region: "state", testId: "int_004__section__notifications", component: "StructuredContentSection", fields: ["notifications_answer", "notifications_evidence", "notifications_next_action", "notifications_state"] }, { id: "preferences", region: "unknown", testId: "int_004__section__preferences", component: "AccessManagementPanel", fields: ["preferences_unknown"] }],
  },
  "OPS-001": {
    route: "/internal/operations",
    objectLabel: "운영 Overview",
    persona: "조사 담당자",
    primaryActionId: "open-incident",
    primaryActionLabel: "incident 열기",
    sections: [{ id: "incidents", region: "state", testId: "ops_001__section__incidents", component: "OperationsStatusPanel", fields: ["incident_actions", "incident_state", "incident_unknowns", "telemetry_gap_state", "telemetry_unknowns"] }, { id: "services", region: "object", testId: "ops_001__section__services", component: "OperationsStatusPanel", fields: ["system_status"] }, { id: "pipelines", region: "state", testId: "ops_001__section__pipelines", component: "StructuredContentSection", fields: ["pipeline_projection"] }, { id: "queues", region: "state", testId: "ops_001__section__queues", component: "DataCollection", fields: ["queue_rows"] }, { id: "cost", region: "state", testId: "ops_001__section__cost", component: "StructuredContentSection", fields: ["cost_projection"] }, { id: "security", region: "evidence", testId: "ops_001__section__security", component: "StructuredContentSection", fields: ["recent_action_receipts", "source_evidence"] }, { id: "slo", region: "answer", testId: "ops_001__section__slo", component: "StructuredContentSection", fields: ["queue_slo", "service_slo"] }],
  },
  "OPS-002": {
    route: "/internal/operations/jobs",
    objectLabel: "작업 Queue·DLQ",
    persona: "조사 담당자",
    primaryActionId: "retry-selected",
    primaryActionLabel: "선택 작업 재시도",
    sections: [{ id: "summary", region: "object", testId: "ops_002__section__summary", component: "DataCollection", fields: ["summary_object"] }, { id: "filters", region: "state", testId: "ops_002__section__filters", component: "UnifiedSearch", fields: ["job_filters"] }, { id: "jobs", region: "state", testId: "ops_002__section__jobs", component: "DataCollection", fields: ["jobs_answer", "jobs_next_action", "jobs_state", "jobs_unknown"] }, { id: "bulk", region: "state", testId: "ops_002__section__bulk", component: "StructuredContentSection", fields: ["bulk_selection_projection"] }, { id: "runbook", region: "evidence", testId: "ops_002__section__runbook", component: "StructuredContentSection", fields: ["runbook_evidence"] }],
  },
  "OPS-003": {
    route: "/internal/operations/jobs/{jobId}",
    objectLabel: "작업 상세",
    persona: "조사 담당자",
    primaryActionId: "retry",
    primaryActionLabel: "작업 재시도",
    sections: [{ id: "identity", region: "object", testId: "ops_003__section__identity", component: "StructuredContentSection", fields: ["job_id", "job_version"] }, { id: "state", region: "state", testId: "ops_003__section__state", component: "StatusAndRevisionHeader", fields: ["job_state", "updated_at"] }, { id: "attempts", region: "state", testId: "ops_003__section__attempts", component: "StructuredContentSection", fields: ["attempt_projection"] }, { id: "payload", region: "state", testId: "ops_003__section__payload", component: "StructuredContentSection", fields: ["redacted_payload_projection"] }, { id: "effects", region: "answer", testId: "ops_003__section__effects", component: "StructuredContentSection", fields: ["attempts_and_effects", "effect_summary", "possible_effect_unknowns"] }, { id: "recovery", region: "next_action", testId: "ops_003__section__recovery", component: "StructuredContentSection", fields: ["recovery_actions"] }, { id: "audit", region: "evidence", testId: "ops_003__section__audit", component: "StructuredContentSection", fields: ["audit_and_receipts"] }],
  },
  "OPS-004": {
    route: "/internal/operations/budgets",
    objectLabel: "비용·예산",
    persona: "조사 담당자",
    primaryActionId: "change-limit",
    primaryActionLabel: "예산 한도 변경",
    sections: [{ id: "envelope", region: "object", testId: "ops_004__section__envelope", component: "AgentSuggestionPanel", fields: ["budget_id", "budget_version"] }, { id: "spend", region: "state", testId: "ops_004__section__spend", component: "StructuredContentSection", fields: ["as_of", "budget_state"] }, { id: "forecast", region: "answer", testId: "ops_004__section__forecast", component: "StructuredContentSection", fields: ["forecast_summary", "spend_and_value"] }, { id: "limits", region: "next_action", testId: "ops_004__section__limits", component: "StructuredContentSection", fields: ["limit_actions"] }, { id: "alerts", region: "unknown", testId: "ops_004__section__alerts", component: "StructuredContentSection", fields: ["alerts_and_unknowns"] }, { id: "changes", region: "evidence", testId: "ops_004__section__changes", component: "RevisionTimeline", fields: ["cost_evidence"] }],
  },
  "OPS-005": {
    route: "/internal/operations/providers",
    objectLabel: "외부 공급자 상태",
    persona: "조사 담당자",
    primaryActionId: "test",
    primaryActionLabel: "연결 테스트",
    sections: [{ id: "status", region: "object", testId: "ops_005__section__status", component: "StatusAndRevisionHeader", fields: ["status_next_action", "status_object", "status_state"] }, { id: "quotas", region: "state", testId: "ops_005__section__quotas", component: "StructuredContentSection", fields: ["quota_projection"] }, { id: "latency", region: "answer", testId: "ops_005__section__latency", component: "StructuredContentSection", fields: ["latency_answer"] }, { id: "privacy", region: "evidence", testId: "ops_005__section__privacy", component: "SensitiveDataNotice", fields: ["privacy_evidence"] }, { id: "fallback", region: "state", testId: "ops_005__section__fallback", component: "StructuredContentSection", fields: ["fallback_projection"] }, { id: "incidents", region: "unknown", testId: "ops_005__section__incidents", component: "OperationsStatusPanel", fields: ["incidents_unknown"] }],
  },
  "OPS-006": {
    route: "/internal/operations/kill-switches",
    objectLabel: "Kill Switch",
    persona: "조사 담당자",
    primaryActionId: "activate",
    primaryActionLabel: "Kill switch 활성화",
    sections: [{ id: "active", region: "object", testId: "ops_006__section__active", component: "OperationsStatusPanel", fields: ["active_object", "active_state"] }, { id: "catalog", region: "state", testId: "ops_006__section__catalog", component: "DataCollection", fields: ["kill_switch_rows"] }, { id: "impact", region: "answer", testId: "ops_006__section__impact", component: "OperationsStatusPanel", fields: ["impact_answer"] }, { id: "approval", region: "unknown", testId: "ops_006__section__approval", component: "DecisionReviewPanel", fields: ["approval_next_action", "approval_unknown"] }, { id: "history", region: "evidence", testId: "ops_006__section__history", component: "RevisionTimeline", fields: ["history_evidence"] }, { id: "runbook", region: "state", testId: "ops_006__section__runbook", component: "StructuredContentSection", fields: ["runbook_projection"] }],
  },
  "PUB-001": {
    route: "/",
    objectLabel: "홈",
    persona: "공개 독자·연구자",
    primaryActionId: "search",
    primaryActionLabel: "검색",
    sections: [{ id: "mission", region: "object", testId: "pub_001__section__mission", component: "StructuredContentSection", fields: ["mission_answer", "mission_object"] }, { id: "search", region: "next_action", testId: "pub_001__section__search", component: "UnifiedSearch", fields: ["search_next_action"] }, { id: "recent", region: "state", testId: "pub_001__section__recent", component: "StatusAndRevisionHeader", fields: ["recent_state"] }, { id: "corrections", region: "unknown", testId: "pub_001__section__corrections", component: "RevisionAndCorrectionPanel", fields: ["corrections_unknown"] }, { id: "coverage", region: "evidence", testId: "pub_001__section__coverage", component: "CoverageStatement", fields: ["coverage_evidence"] }, { id: "method", region: "state", testId: "pub_001__section__method", component: "LongFormArticle", fields: ["methodology_projection"] }],
  },
  "PUB-002": {
    route: "/search",
    objectLabel: "통합 검색",
    persona: "공개 독자·연구자",
    primaryActionId: "submit-search",
    primaryActionLabel: "검색",
    sections: [{ id: "query", region: "object", testId: "pub_002__section__query", component: "UnifiedSearch", fields: ["query_next_action", "query_object"] }, { id: "types", region: "state", testId: "pub_002__section__types", component: "RevisionAndCorrectionPanel", fields: ["types_applied_filters"] }, { id: "results", region: "state", testId: "pub_002__section__results", component: "UnifiedSearch", fields: ["results_answer", "results_state"] }, { id: "coverage", region: "evidence", testId: "pub_002__section__coverage", component: "UnifiedSearch", fields: ["coverage_evidence", "coverage_unknown"] }],
  },
  "PUB-003": {
    route: "/cases",
    objectLabel: "공개 사례",
    persona: "공개 독자·연구자",
    primaryActionId: "apply-filter",
    primaryActionLabel: "필터 적용",
    sections: [{ id: "scope", region: "object", testId: "pub_003__section__scope", component: "StatusAndRevisionHeader", fields: ["scope_evidence", "scope_object", "scope_unknown"] }, { id: "filters", region: "next_action", testId: "pub_003__section__filters", component: "UnifiedSearch", fields: ["filters_next_action"] }, { id: "results", region: "state", testId: "pub_003__section__results", component: "StatusAndRevisionHeader", fields: ["results_answer", "results_state"] }, { id: "pagination", region: "state", testId: "pub_003__section__pagination", component: "DataCollection", fields: ["pagination_as_of", "pagination_next_cursor", "pagination_total_approximate"] }],
  },
  "PUB-004": {
    route: "/cases/{caseSlug}",
    objectLabel: "사건 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "open-evidence",
    primaryActionLabel: "근거 원문 보기",
    sections: [{ id: "status", region: "object", testId: "pub_004__section__status", component: "StatusAndRevisionHeader", fields: ["case_slug", "case_title", "freshness", "public_state", "revision"] }, { id: "known", region: "answer", testId: "pub_004__section__known", component: "KnownUnknownResponse", fields: ["answer_first_summary", "confirmed_facts"] }, { id: "unknown", region: "unknown", testId: "pub_004__section__unknown", component: "KnownUnknownResponse", fields: ["counter_evidence", "limitations", "material_unknowns"] }, { id: "response", region: "state", testId: "pub_004__section__response", component: "StatusAndRevisionHeader", fields: ["response_party_responses"] }, { id: "comparison", region: "state", testId: "pub_004__section__comparison", component: "ComparisonWorkbench", fields: ["comparison_model"] }, { id: "counter", region: "state", testId: "pub_004__section__counter", component: "EvidenceLedger", fields: ["counter_evidence"] }, { id: "evidence", region: "evidence", testId: "pub_004__section__evidence", component: "EvidenceLedger", fields: ["evidence_items", "evidence_timeline", "reproduction_case_slug", "reproduction_rule_id"] }, { id: "timeline", region: "state", testId: "pub_004__section__timeline", component: "RevisionTimeline", fields: ["timeline_items"] }, { id: "revision", region: "state", testId: "pub_004__section__revision", component: "StatusAndRevisionHeader", fields: ["revision_corrections", "revision_number"] }],
  },
  "PUB-005": {
    route: "/cases/{caseSlug}/revisions/{revision}",
    objectLabel: "사건 공개 revision",
    persona: "공개 독자·연구자",
    primaryActionId: "view-latest",
    primaryActionLabel: "최신 revision 보기",
    sections: [{ id: "revision-banner", region: "object", testId: "pub_005__section__revision-banner", component: "StatusAndRevisionHeader", fields: ["available_revisions", "case_slug", "is_latest", "revision", "superseded_by_revision"] }, { id: "snapshot", region: "answer", testId: "pub_005__section__snapshot", component: "KnownUnknownResponse", fields: ["diff_from_previous", "fixed_content"] }, { id: "diff", region: "unknown", testId: "pub_005__section__diff", component: "StatusAndRevisionHeader", fields: ["material_changes"] }, { id: "citation", region: "evidence", testId: "pub_005__section__citation", component: "StatusAndRevisionHeader", fields: ["published_at", "snapshot_hash"] }],
  },
  "PUB-006": {
    route: "/cases/{caseSlug}/reproduce",
    objectLabel: "계산 재현",
    persona: "공개 독자·연구자",
    primaryActionId: "download-json",
    primaryActionLabel: "JSON 다운로드",
    sections: [{ id: "summary", region: "object", testId: "pub_006__section__summary", component: "StructuredContentSection", fields: ["case_slug", "input_digest", "result_digest", "rule_id", "rule_version"] }, { id: "inputs", region: "evidence", testId: "pub_006__section__inputs", component: "StructuredContentSection", fields: ["excluded_cohort", "included_cohort"] }, { id: "cohort", region: "state", testId: "pub_006__section__cohort", component: "ComparisonWorkbench", fields: ["excluded_cohort", "included_cohort"] }, { id: "formula", region: "answer", testId: "pub_006__section__formula", component: "ComparisonWorkbench", fields: ["formula", "result", "rounding_policy"] }, { id: "download", region: "next_action", testId: "pub_006__section__download", component: "StructuredContentSection", fields: ["download_metadata"] }, { id: "limitations", region: "unknown", testId: "pub_006__section__limitations", component: "StructuredContentSection", fields: ["limitations"] }],
  },
  "PUB-007": {
    route: "/agencies",
    objectLabel: "기관",
    persona: "공개 독자·연구자",
    primaryActionId: "open-agency",
    primaryActionLabel: "기관 보기",
    sections: [{ id: "search", region: "object", testId: "pub_007__section__search", component: "UnifiedSearch", fields: ["search_next_action", "search_object"] }, { id: "filters", region: "state", testId: "pub_007__section__filters", component: "UnifiedSearch", fields: ["agency_filters"] }, { id: "results", region: "answer", testId: "pub_007__section__results", component: "CoverageStatement", fields: ["results_answer"] }, { id: "coverage", region: "state", testId: "pub_007__section__coverage", component: "CoverageStatement", fields: ["coverage_evidence", "coverage_state", "coverage_unknown"] }],
  },
  "PUB-008": {
    route: "/agencies/{agencySlug}",
    objectLabel: "기관 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "view-contract",
    primaryActionLabel: "계약 보기",
    sections: [{ id: "identity", region: "object", testId: "pub_008__section__identity", component: "RevisionTimeline", fields: ["agency_id", "agency_name"] }, { id: "coverage", region: "state", testId: "pub_008__section__coverage", component: "CoverageStatement", fields: ["freshness"] }, { id: "metrics", region: "answer", testId: "pub_008__section__metrics", component: "StatusAndRevisionHeader", fields: ["coverage", "metrics"] }, { id: "contracts", region: "next_action", testId: "pub_008__section__contracts", component: "StructuredContentSection", fields: ["recent_cases"] }, { id: "cases", region: "state", testId: "pub_008__section__cases", component: "StatusAndRevisionHeader", fields: ["case_as_of", "case_next_cursor", "case_rows"] }, { id: "corrections", region: "unknown", testId: "pub_008__section__corrections", component: "RevisionAndCorrectionPanel", fields: ["identity_warnings"] }, { id: "methods", region: "evidence", testId: "pub_008__section__methods", component: "LongFormArticle", fields: ["official_identifiers", "recent_contracts"] }],
  },
  "PUB-009": {
    route: "/suppliers",
    objectLabel: "업체",
    persona: "공개 독자·연구자",
    primaryActionId: "open-supplier",
    primaryActionLabel: "업체 보기",
    sections: [{ id: "search", region: "object", testId: "pub_009__section__search", component: "UnifiedSearch", fields: ["search_next_action", "search_object"] }, { id: "filters", region: "state", testId: "pub_009__section__filters", component: "UnifiedSearch", fields: ["supplier_filters"] }, { id: "results", region: "answer", testId: "pub_009__section__results", component: "CoverageStatement", fields: ["results_answer"] }, { id: "identity-note", region: "state", testId: "pub_009__section__identity-note", component: "StructuredContentSection", fields: ["identity_note_evidence", "identity_note_state", "identity_note_unknown"] }],
  },
  "PUB-010": {
    route: "/suppliers/{supplierSlug}",
    objectLabel: "업체 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "view-contract",
    primaryActionLabel: "계약 보기",
    sections: [{ id: "identity", region: "object", testId: "pub_010__section__identity", component: "KnownUnknownResponse", fields: ["supplier_id", "supplier_name"] }, { id: "coverage", region: "state", testId: "pub_010__section__coverage", component: "CoverageStatement", fields: ["freshness"] }, { id: "metrics", region: "answer", testId: "pub_010__section__metrics", component: "ComparisonWorkbench", fields: ["coverage", "metrics"] }, { id: "contracts", region: "next_action", testId: "pub_010__section__contracts", component: "StructuredContentSection", fields: ["recent_cases"] }, { id: "cases", region: "state", testId: "pub_010__section__cases", component: "StatusAndRevisionHeader", fields: ["case_as_of", "case_next_cursor", "case_rows"] }, { id: "corrections", region: "unknown", testId: "pub_010__section__corrections", component: "RevisionAndCorrectionPanel", fields: ["identity_warnings"] }, { id: "relationships", region: "evidence", testId: "pub_010__section__relationships", component: "KnownUnknownResponse", fields: ["official_identifiers", "recent_contracts"] }],
  },
  "PUB-011": {
    route: "/contracts",
    objectLabel: "계약",
    persona: "공개 독자·연구자",
    primaryActionId: "open-contract",
    primaryActionLabel: "계약 보기",
    sections: [{ id: "scope", region: "object", testId: "pub_011__section__scope", component: "CoverageStatement", fields: ["scope_evidence", "scope_object"] }, { id: "filters", region: "next_action", testId: "pub_011__section__filters", component: "UnifiedSearch", fields: ["filters_next_action"] }, { id: "results", region: "state", testId: "pub_011__section__results", component: "DataCollection", fields: ["results_answer", "results_state"] }, { id: "limitations", region: "unknown", testId: "pub_011__section__limitations", component: "ComparisonWorkbench", fields: ["limitations_unknown"] }],
  },
  "PUB-012": {
    route: "/contracts/{contractId}",
    objectLabel: "계약 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "open-source",
    primaryActionLabel: "원문 보기",
    sections: [{ id: "identity", region: "object", testId: "pub_012__section__identity", component: "StatusAndRevisionHeader", fields: ["contract_id", "contract_number"] }, { id: "terms", region: "answer", testId: "pub_012__section__terms", component: "StructuredContentSection", fields: ["current_amount", "line_items", "title"] }, { id: "changes", region: "state", testId: "pub_012__section__changes", component: "StructuredContentSection", fields: ["changes", "contract_status"] }, { id: "procurement", region: "state", testId: "pub_012__section__procurement", component: "StructuredContentSection", fields: ["procurement_changes", "procurement_method", "procurement_sources"] }, { id: "provenance", region: "evidence", testId: "pub_012__section__provenance", component: "StructuredContentSection", fields: ["related_cases", "source_documents"] }, { id: "related", region: "state", testId: "pub_012__section__related", component: "DataCollection", fields: ["related_cases"] }, { id: "limitations", region: "unknown", testId: "pub_012__section__limitations", component: "StructuredContentSection", fields: ["normalization_warnings"] }],
  },
  "PUB-013": {
    route: "/methodology",
    objectLabel: "방법론",
    persona: "공개 독자·연구자",
    primaryActionId: "open-rule",
    primaryActionLabel: "규칙 상세",
    sections: [{ id: "overview", region: "object", testId: "pub_013__section__overview", component: "LongFormArticle", fields: ["overview_object"] }, { id: "pipeline", region: "answer", testId: "pub_013__section__pipeline", component: "StructuredContentSection", fields: ["methodology_summary"] }, { id: "rules", region: "next_action", testId: "pub_013__section__rules", component: "DataCollection", fields: ["rules_next_action"] }, { id: "ai", region: "unknown", testId: "pub_013__section__ai", component: "StructuredContentSection", fields: ["ai_limitations"] }, { id: "quality", region: "evidence", testId: "pub_013__section__quality", component: "StructuredContentSection", fields: ["methodology_sources"] }, { id: "changes", region: "state", testId: "pub_013__section__changes", component: "RevisionTimeline", fields: ["changes_state"] }],
  },
  "PUB-014": {
    route: "/methodology/rules/{ruleId}",
    objectLabel: "탐지 규칙 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "view-related-cases",
    primaryActionLabel: "관련 공개 사례",
    sections: [{ id: "purpose", region: "object", testId: "pub_014__section__purpose", component: "StructuredContentSection", fields: ["rule_id", "rule_version"] }, { id: "inputs", region: "state", testId: "pub_014__section__inputs", component: "StructuredContentSection", fields: ["required_input_projection"] }, { id: "calculation", region: "answer", testId: "pub_014__section__calculation", component: "ComparisonWorkbench", fields: ["calculation_contract", "rule_summary"] }, { id: "blockers", region: "state", testId: "pub_014__section__blockers", component: "StructuredContentSection", fields: ["blocking_condition_projection"] }, { id: "false-positive", region: "unknown", testId: "pub_014__section__false-positive", component: "StructuredContentSection", fields: ["false_positive_and_limitations"] }, { id: "evaluation", region: "evidence", testId: "pub_014__section__evaluation", component: "DataCollection", fields: ["evaluation_links", "related_cases"] }, { id: "versions", region: "state", testId: "pub_014__section__versions", component: "StructuredContentSection", fields: ["rule_status", "updated_at"] }],
  },
  "PUB-015": {
    route: "/coverage",
    objectLabel: "데이터 범위",
    persona: "공개 독자·연구자",
    primaryActionId: "open-source",
    primaryActionLabel: "source 상세",
    sections: [{ id: "summary", region: "object", testId: "pub_015__section__summary", component: "StatusAndRevisionHeader", fields: ["coverage_as_of", "record_counts", "sources"] }, { id: "sources", region: "evidence", testId: "pub_015__section__sources", component: "CoverageStatement", fields: ["source_evidence", "source_status_actions"] }, { id: "gaps", region: "unknown", testId: "pub_015__section__gaps", component: "StructuredContentSection", fields: ["known_gaps"] }, { id: "latency", region: "state", testId: "pub_015__section__latency", component: "StructuredContentSection", fields: ["covered_date_range", "methodology_version"] }, { id: "changes", region: "state", testId: "pub_015__section__changes", component: "CoverageStatement", fields: ["coverage_change_projection"] }],
  },
  "PUB-016": {
    route: "/sources",
    objectLabel: "데이터 출처",
    persona: "공개 독자·연구자",
    primaryActionId: "open-source",
    primaryActionLabel: "source 상세",
    sections: [{ id: "status", region: "object", testId: "pub_016__section__status", component: "StatusAndRevisionHeader", fields: ["status_object", "status_state"] }, { id: "list", region: "next_action", testId: "pub_016__section__list", component: "CoverageStatement", fields: ["list_next_action"] }, { id: "quality", region: "answer", testId: "pub_016__section__quality", component: "StructuredContentSection", fields: ["quality_answer", "quality_unknown"] }, { id: "terms", region: "evidence", testId: "pub_016__section__terms", component: "StructuredContentSection", fields: ["terms_evidence"] }],
  },
  "PUB-017": {
    route: "/sources/{sourceId}",
    objectLabel: "데이터 출처 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "view-official",
    primaryActionLabel: "공식 source 열기",
    sections: [{ id: "identity", region: "object", testId: "pub_017__section__identity", component: "StructuredContentSection", fields: ["source_id", "source_title"] }, { id: "freshness", region: "state", testId: "pub_017__section__freshness", component: "StatusAndRevisionHeader", fields: ["source_status", "updated_at"] }, { id: "coverage", region: "answer", testId: "pub_017__section__coverage", component: "CoverageStatement", fields: ["coverage_summary", "schema_and_quality"] }, { id: "schema", region: "evidence", testId: "pub_017__section__schema", component: "RevisionTimeline", fields: ["official_and_terms_links"] }, { id: "quality", region: "state", testId: "pub_017__section__quality", component: "StructuredContentSection", fields: ["quality_projection"] }, { id: "terms", region: "unknown", testId: "pub_017__section__terms", component: "StructuredContentSection", fields: ["known_limitations"] }, { id: "impact", region: "next_action", testId: "pub_017__section__impact", component: "StructuredContentSection", fields: ["operational_links"] }],
  },
  "PUB-018": {
    route: "/corrections",
    objectLabel: "정정·철회",
    persona: "공개 독자·연구자",
    primaryActionId: "open-correction",
    primaryActionLabel: "정정 상세",
    sections: [{ id: "principle", region: "object", testId: "pub_018__section__principle", component: "RevisionAndCorrectionPanel", fields: ["principle_object", "principle_unknown"] }, { id: "filters", region: "next_action", testId: "pub_018__section__filters", component: "UnifiedSearch", fields: ["filters_next_action"] }, { id: "records", region: "state", testId: "pub_018__section__records", component: "RevisionAndCorrectionPanel", fields: ["records_answer", "records_state"] }, { id: "feed", region: "evidence", testId: "pub_018__section__feed", component: "RevisionAndCorrectionPanel", fields: ["feed_evidence"] }],
  },
  "PUB-019": {
    route: "/corrections/{correctionId}",
    objectLabel: "정정 상세",
    persona: "공개 독자·연구자",
    primaryActionId: "open-case",
    primaryActionLabel: "대상 사건 보기",
    sections: [{ id: "status", region: "state", testId: "pub_019__section__status", component: "StatusAndRevisionHeader", fields: ["correction_status", "correction_version"] }, { id: "target", region: "object", testId: "pub_019__section__target", component: "StatusAndRevisionHeader", fields: ["correction_id", "correction_title", "target_route"] }, { id: "before-after", region: "answer", testId: "pub_019__section__before-after", component: "ComparisonWorkbench", fields: ["before_after_summary", "impact"] }, { id: "reason", region: "unknown", testId: "pub_019__section__reason", component: "EvidenceLedger", fields: ["reason_and_limitations"] }, { id: "impact", region: "state", testId: "pub_019__section__impact", component: "StructuredContentSection", fields: ["impact_projection"] }, { id: "review", region: "evidence", testId: "pub_019__section__review", component: "RevisionTimeline", fields: ["review_records"] }],
  },
  "PUB-020": {
    route: "/data",
    objectLabel: "데이터·다운로드",
    persona: "공개 독자·연구자",
    primaryActionId: "download-dataset",
    primaryActionLabel: "데이터 다운로드",
    sections: [{ id: "datasets", region: "object", testId: "pub_020__section__datasets", component: "RevisionAndCorrectionPanel", fields: ["datasets_answer", "datasets_next_action", "datasets_object"] }, { id: "snapshots", region: "state", testId: "pub_020__section__snapshots", component: "StructuredContentSection", fields: ["snapshots_state"] }, { id: "schemas", region: "state", testId: "pub_020__section__schemas", component: "StructuredContentSection", fields: ["schema_dictionary_projection"] }, { id: "license", region: "evidence", testId: "pub_020__section__license", component: "StructuredContentSection", fields: ["license_evidence"] }, { id: "corrections", region: "state", testId: "pub_020__section__corrections", component: "StatusAndRevisionHeader", fields: ["correction_semantics_projection"] }, { id: "limits", region: "unknown", testId: "pub_020__section__limits", component: "StructuredContentSection", fields: ["limits_unknown"] }],
  },
  "PUB-021": {
    route: "/api",
    objectLabel: "공개 API 문서",
    persona: "공개 독자·연구자",
    primaryActionId: "download-openapi",
    primaryActionLabel: "OpenAPI JSON 다운로드",
    sections: [{ id: "getting-started", region: "object", testId: "pub_021__section__getting-started", component: "StructuredContentSection", fields: ["api_version", "documentation_id", "openapi_download"] }, { id: "resources", region: "answer", testId: "pub_021__section__resources", component: "RevisionAndCorrectionPanel", fields: ["endpoint_contracts", "resource_summary"] }, { id: "pagination", region: "state", testId: "pub_021__section__pagination", component: "StructuredContentSection", fields: ["pagination_contract_projection"] }, { id: "errors", region: "unknown", testId: "pub_021__section__errors", component: "StructuredContentSection", fields: ["errors_and_limits"] }, { id: "versioning", region: "state", testId: "pub_021__section__versioning", component: "StructuredContentSection", fields: ["documentation_status", "updated_at"] }, { id: "download", region: "evidence", testId: "pub_021__section__download", component: "StructuredContentSection", fields: ["schema_and_openapi_links"] }],
  },
  "PUB-022": {
    route: "/about",
    objectLabel: "소개",
    persona: "공개 독자·연구자",
    primaryActionId: "view-governance",
    primaryActionLabel: "운영 원칙",
    sections: [{ id: "mission", region: "object", testId: "pub_022__section__mission", component: "StructuredContentSection", fields: ["about_revision", "mission", "process", "service_name"] }, { id: "non-goals", region: "unknown", testId: "pub_022__section__non-goals", component: "StructuredContentSection", fields: ["non_goals"] }, { id: "team", region: "state", testId: "pub_022__section__team", component: "OperationsStatusPanel", fields: ["operating_entity_projection"] }, { id: "process", region: "state", testId: "pub_022__section__process", component: "RevisionAndCorrectionPanel", fields: ["content_status", "operating_records", "updated_at"] }, { id: "contact", region: "next_action", testId: "pub_022__section__contact", component: "StructuredContentSection", fields: ["contact_and_governance"] }],
  },
  "PUB-023": {
    route: "/about/funding",
    objectLabel: "재원·수익 투명성",
    persona: "공개 독자·연구자",
    primaryActionId: "download-report",
    primaryActionLabel: "투명성 보고서 다운로드",
    sections: [{ id: "principles", region: "object", testId: "pub_023__section__principles", component: "StructuredContentSection", fields: ["funding_report_title", "funding_revision"] }, { id: "income", region: "state", testId: "pub_023__section__income", component: "StructuredContentSection", fields: ["income_and_cost_detail", "income_and_cost_summary", "report_status", "updated_at"] }, { id: "expenses", region: "state", testId: "pub_023__section__expenses", component: "StructuredContentSection", fields: ["expense_projection"] }, { id: "donors", region: "state", testId: "pub_023__section__donors", component: "StructuredContentSection", fields: ["donor_disclosure_projection"] }, { id: "conflicts", region: "unknown", testId: "pub_023__section__conflicts", component: "StructuredContentSection", fields: ["conflicts_and_concentration"] }, { id: "reports", region: "evidence", testId: "pub_023__section__reports", component: "StructuredContentSection", fields: ["audited_reports", "downloadable_reports"] }],
  },
  "PUB-024": {
    route: "/about/governance",
    objectLabel: "운영·거버넌스",
    persona: "공개 독자·연구자",
    primaryActionId: "view-editorial-policy",
    primaryActionLabel: "편집 정책",
    sections: [{ id: "structure", region: "object", testId: "pub_024__section__structure", component: "OperationsStatusPanel", fields: ["governance_revision", "governance_title"] }, { id: "independence", region: "answer", testId: "pub_024__section__independence", component: "StructuredContentSection", fields: ["governance_summary", "independence_structure"] }, { id: "conflicts", region: "unknown", testId: "pub_024__section__conflicts", component: "StructuredContentSection", fields: ["conflicts_and_limitations"] }, { id: "oversight", region: "state", testId: "pub_024__section__oversight", component: "StructuredContentSection", fields: ["policy_status", "updated_at"] }, { id: "appeal", region: "next_action", testId: "pub_024__section__appeal", component: "RevisionAndCorrectionPanel", fields: ["appeal_and_policy_routes"] }, { id: "records", region: "evidence", testId: "pub_024__section__records", component: "RevisionTimeline", fields: ["oversight_records"] }],
  },
  "PUB-025": {
    route: "/editorial-policy",
    objectLabel: "편집·공개 정책",
    persona: "공개 독자·연구자",
    primaryActionId: "request-correction",
    primaryActionLabel: "정정 요청",
    sections: [{ id: "states", region: "object", testId: "pub_025__section__states", component: "StatusAndRevisionHeader", fields: ["policy_revision", "policy_title"] }, { id: "publication-gate", region: "answer", testId: "pub_025__section__publication-gate", component: "KnownUnknownResponse", fields: ["publication_policy", "state_and_gate_rules"] }, { id: "language", region: "state", testId: "pub_025__section__language", component: "StructuredContentSection", fields: ["language_policy_projection"] }, { id: "response", region: "state", testId: "pub_025__section__response", component: "KnownUnknownResponse", fields: ["right_of_reply_projection"] }, { id: "correction", region: "next_action", testId: "pub_025__section__correction", component: "StatusAndRevisionHeader", fields: ["correction_route"] }, { id: "privacy", region: "unknown", testId: "pub_025__section__privacy", component: "StructuredContentSection", fields: ["privacy_and_response_limits"] }, { id: "history", region: "state", testId: "pub_025__section__history", component: "LongFormArticle", fields: ["policy_history", "policy_status", "updated_at"] }],
  },
  "PUB-026": {
    route: "/contact",
    objectLabel: "문의",
    persona: "공개 독자·연구자",
    primaryActionId: "submit-contact",
    primaryActionLabel: "문의 보내기",
    sections: [{ id: "routing", region: "object", testId: "pub_026__section__routing", component: "KnownUnknownResponse", fields: ["channel_requirements", "contact_policy_revision", "contact_title", "privacy_limits", "routing_guidance"] }, { id: "channels", region: "state", testId: "pub_026__section__channels", component: "StatusAndRevisionHeader", fields: ["channel_status", "updated_at"] }, { id: "form", region: "next_action", testId: "pub_026__section__form", component: "GuidedFormSection", fields: ["contact_form_route"] }, { id: "security", region: "evidence", testId: "pub_026__section__security", component: "GuidedFormSection", fields: ["security_and_support"] }],
  },
  "PUB-027": {
    route: "/correction-request",
    objectLabel: "정정 요청",
    persona: "공개 독자·연구자",
    primaryActionId: "save-draft",
    primaryActionLabel: "임시 저장",
    sections: [{ id: "intro", region: "object", testId: "pub_027__section__intro", component: "StatusAndRevisionHeader", fields: ["safe_draft_identity"] }, { id: "target", region: "answer", testId: "pub_027__section__target", component: "StatusAndRevisionHeader", fields: ["review_summary"] }, { id: "issue", region: "state", testId: "pub_027__section__issue", component: "StructuredContentSection", fields: ["draft_version", "requested_changes"] }, { id: "evidence", region: "evidence", testId: "pub_027__section__evidence", component: "EvidenceLedger", fields: ["verified_attachments"] }, { id: "privacy", region: "unknown", testId: "pub_027__section__privacy", component: "StructuredContentSection", fields: ["blocking_warnings"] }, { id: "review", region: "state", testId: "pub_027__section__review", component: "CheckAnswers", fields: ["next_submission_digest", "submission_digest"] }],
  },
  "PUB-028": {
    route: "/correction-request/receipt",
    objectLabel: "정정 요청 접수",
    persona: "공개 독자·연구자",
    primaryActionId: "download-receipt",
    primaryActionLabel: "영수증 저장",
    sections: [{ id: "receipt", region: "object", testId: "pub_028__section__receipt", component: "StatusAndRevisionHeader", fields: ["receipt_id", "receipt_records", "receipt_status", "receipt_title", "receipt_version"] }, { id: "summary", region: "answer", testId: "pub_028__section__summary", component: "LongFormArticle", fields: ["submitted_items", "submitted_scope"] }, { id: "next", region: "unknown", testId: "pub_028__section__next", component: "StructuredContentSection", fields: ["next_step_uncertainty"] }, { id: "manage", region: "next_action", testId: "pub_028__section__manage", component: "StatusAndRevisionHeader", fields: ["management_routes"] }],
  },
  "PUB-029": {
    route: "/subscribe",
    objectLabel: "업데이트 구독",
    persona: "공개 독자·연구자",
    primaryActionId: "request-verification",
    primaryActionLabel: "검증 이메일 보내기",
    sections: [{ id: "topic", region: "object", testId: "pub_029__section__topic", component: "RevisionAndCorrectionPanel", fields: ["accepted_at", "request_id", "selected_topic", "subscription_id"] }, { id: "events", region: "state", testId: "pub_029__section__events", component: "KnownUnknownResponse", fields: ["subscription_status", "verification_dispatched"] }, { id: "frequency", region: "state", testId: "pub_029__section__frequency", component: "StructuredContentSection", fields: ["frequency_choice_projection"] }, { id: "email", region: "next_action", testId: "pub_029__section__email", component: "CheckAnswers", fields: ["verification_route"] }, { id: "privacy", region: "evidence", testId: "pub_029__section__privacy", component: "StructuredContentSection", fields: ["audit_event_id", "verification_delivery_unknowns"] }],
  },
  "PUB-030": {
    route: "/subscription/manage",
    objectLabel: "구독 관리",
    persona: "공개 독자·연구자",
    primaryActionId: "save-preferences",
    primaryActionLabel: "구독 설정 저장",
    sections: [{ id: "identity", region: "object", testId: "pub_030__section__identity", component: "KnownUnknownResponse", fields: ["subscription_id", "subscription_title"] }, { id: "topics", region: "state", testId: "pub_030__section__topics", component: "StructuredContentSection", fields: ["topic_projection"] }, { id: "preferences", region: "answer", testId: "pub_030__section__preferences", component: "StructuredContentSection", fields: ["delivery_preferences", "preference_actions", "preferences_summary"] }, { id: "delivery", region: "state", testId: "pub_030__section__delivery", component: "StatusAndRevisionHeader", fields: ["delivery_receipts", "delivery_unknowns", "subscription_status", "subscription_version"] }, { id: "unsubscribe", region: "state", testId: "pub_030__section__unsubscribe", component: "DataCollection", fields: ["subscription_id", "subscription_status"] }],
  },
  "PUB-031": {
    route: "/privacy",
    objectLabel: "개인정보 처리방침",
    persona: "공개 독자·연구자",
    primaryActionId: "privacy-contact",
    primaryActionLabel: "개인정보 문의",
    sections: [{ id: "controller", region: "object", testId: "pub_031__section__controller", component: "StructuredContentSection", fields: ["controller_name", "policy_revision"] }, { id: "categories", region: "state", testId: "pub_031__section__categories", component: "StructuredContentSection", fields: ["data_category_projection"] }, { id: "purposes", region: "state", testId: "pub_031__section__purposes", component: "EvidenceLedger", fields: ["processing_purpose_projection"] }, { id: "retention", region: "unknown", testId: "pub_031__section__retention", component: "StructuredContentSection", fields: ["retention_and_limitations"] }, { id: "processors", region: "state", testId: "pub_031__section__processors", component: "StructuredContentSection", fields: ["processor_projection"] }, { id: "rights", region: "answer", testId: "pub_031__section__rights", component: "StructuredContentSection", fields: ["processing_contract", "rights_request_route", "rights_summary"] }, { id: "security", region: "evidence", testId: "pub_031__section__security", component: "StructuredContentSection", fields: ["security_and_processor_records"] }, { id: "history", region: "state", testId: "pub_031__section__history", component: "RevisionTimeline", fields: ["policy_status", "updated_at"] }],
  },
  "PUB-032": {
    route: "/terms",
    objectLabel: "이용약관",
    persona: "공개 독자·연구자",
    primaryActionId: "view-data",
    primaryActionLabel: "데이터 안내",
    sections: [{ id: "service", region: "object", testId: "pub_032__section__service", component: "LongFormArticle", fields: ["terms_revision", "terms_title"] }, { id: "content", region: "answer", testId: "pub_032__section__content", component: "StatusAndRevisionHeader", fields: ["content_and_data_terms", "service_terms"] }, { id: "data", region: "evidence", testId: "pub_032__section__data", component: "StructuredContentSection", fields: ["data_route", "supporting_policies"] }, { id: "prohibited", region: "state", testId: "pub_032__section__prohibited", component: "StructuredContentSection", fields: ["prohibited_use_projection"] }, { id: "liability", region: "unknown", testId: "pub_032__section__liability", component: "LongFormArticle", fields: ["liability_and_prohibitions"] }, { id: "changes", region: "state", testId: "pub_032__section__changes", component: "StructuredContentSection", fields: ["terms_status", "updated_at"] }],
  },
  "PUB-033": {
    route: "/accessibility",
    objectLabel: "접근성 안내",
    persona: "공개 독자·연구자",
    primaryActionId: "report-accessibility",
    primaryActionLabel: "접근성 문제 신고",
    sections: [{ id: "commitment", region: "object", testId: "pub_033__section__commitment", component: "StructuredContentSection", fields: ["commitment", "conformance_detail", "statement_revision", "statement_title"] }, { id: "conformance", region: "state", testId: "pub_033__section__conformance", component: "StatusAndRevisionHeader", fields: ["conformance_status", "updated_at"] }, { id: "limitations", region: "unknown", testId: "pub_033__section__limitations", component: "StructuredContentSection", fields: ["known_limitations"] }, { id: "contact", region: "next_action", testId: "pub_033__section__contact", component: "StructuredContentSection", fields: ["support_route"] }, { id: "roadmap", region: "evidence", testId: "pub_033__section__roadmap", component: "StructuredContentSection", fields: ["audit_and_roadmap"] }],
  },
  "PUB-034": {
    route: "/{systemPath}",
    objectLabel: "오류·시스템 상태",
    persona: "공개 독자·연구자",
    primaryActionId: "retry",
    primaryActionLabel: "다시 시도",
    sections: [{ id: "message", region: "object", testId: "pub_034__section__message", component: "StructuredContentSection", fields: ["answer_first_message", "as_of", "system_status"] }, { id: "impact", region: "state", testId: "pub_034__section__impact", component: "CoverageStatement", fields: ["affected_capabilities", "unknown_impact"] }, { id: "actions", region: "next_action", testId: "pub_034__section__actions", component: "StatusAndRevisionHeader", fields: ["safe_actions"] }, { id: "reference", region: "evidence", testId: "pub_034__section__reference", component: "StructuredContentSection", fields: ["status_evidence"] }],
  },
  "REV-001": {
    route: "/internal/review",
    objectLabel: "검토 Queue",
    persona: "조사 담당자",
    primaryActionId: "assign-reviewer",
    primaryActionLabel: "검토자 배정",
    sections: [{ id: "views", region: "object", testId: "rev_001__section__views", component: "DecisionReviewPanel", fields: ["views_object"] }, { id: "filters", region: "state", testId: "rev_001__section__filters", component: "UnifiedSearch", fields: ["review_filters"] }, { id: "queue", region: "answer", testId: "rev_001__section__queue", component: "KnownUnknownResponse", fields: ["queue_answer", "queue_next_action"] }, { id: "independence", region: "state", testId: "rev_001__section__independence", component: "StructuredContentSection", fields: ["independence_evidence", "independence_state", "independence_unknown"] }],
  },
  "REV-002": {
    route: "/internal/review/{snapshotId}",
    objectLabel: "독립 Snapshot 검토",
    persona: "조사 담당자",
    primaryActionId: "request-changes",
    primaryActionLabel: "변경 요청",
    sections: [{ id: "identity", region: "object", testId: "rev_002__section__identity", component: "StructuredContentSection", fields: ["snapshot_hash", "snapshot_id"] }, { id: "preview", region: "evidence", testId: "rev_002__section__preview", component: "DecisionReviewPanel", fields: ["evidence", "gate_evidence"] }, { id: "matrix", region: "answer", testId: "rev_002__section__matrix", component: "EvidenceLedger", fields: ["claims", "responses"] }, { id: "diff", region: "state", testId: "rev_002__section__diff", component: "DecisionReviewPanel", fields: ["readable_diff_projection"] }, { id: "risks", region: "state", testId: "rev_002__section__risks", component: "GateChecklist", fields: ["blocking_state", "case_version", "independence_risks", "unresolved_blockers"] }, { id: "decision", region: "next_action", testId: "rev_002__section__decision", component: "DecisionReviewPanel", fields: ["decision_receipt"] }],
  },
  "REV-003": {
    route: "/internal/review/{snapshotId}/publish",
    objectLabel: "게시 확인·영수증",
    persona: "조사 담당자",
    primaryActionId: "publish",
    primaryActionLabel: "최신 snapshot 게시",
    sections: [{ id: "target", region: "object", testId: "rev_003__section__target", component: "StructuredContentSection", fields: ["snapshot_id", "snapshot_version"] }, { id: "gates", region: "state", testId: "rev_003__section__gates", component: "KnownUnknownResponse", fields: ["blocking_gates", "evaluated_at", "gate_evidence", "gate_state", "publication_receipt_links"] }, { id: "impact", region: "answer", testId: "rev_003__section__impact", component: "StructuredContentSection", fields: ["affected_routes", "publication_impact"] }, { id: "reauth", region: "next_action", testId: "rev_003__section__reauth", component: "StructuredContentSection", fields: ["public_smoke_receipt"] }, { id: "receipt", region: "state", testId: "rev_003__section__receipt", component: "StatusAndRevisionHeader", fields: ["publication_receipt_projection"] }],
  },
  "RSP-001": {
    route: "/respond/access",
    objectLabel: "소명 요청 확인",
    persona: "소명 대상자",
    primaryActionId: "continue",
    primaryActionLabel: "요청 내용 보기",
    sections: [{ id: "identity", region: "object", testId: "rsp_001__section__identity", component: "PageHeader", fields: ["request_reference", "request_title"] }, { id: "security", region: "evidence", testId: "rsp_001__section__security", component: "SensitiveDataNotice", fields: ["security_support"] }, { id: "deadline", region: "unknown", testId: "rsp_001__section__deadline", component: "StructuredContentSection", fields: ["access_unknowns"] }, { id: "process", region: "answer", testId: "rsp_001__section__process", component: "GuidedFormSection", fields: ["deadline_and_sender", "request_process"] }, { id: "verification", region: "state", testId: "rsp_001__section__verification", component: "StructuredContentSection", fields: ["access_status", "access_version", "verification_action"] }],
  },
  "RSP-002": {
    route: "/respond/overview",
    objectLabel: "요청 내용",
    persona: "소명 대상자",
    primaryActionId: "start-answer",
    primaryActionLabel: "답변 작성",
    sections: [{ id: "questions", region: "object", testId: "rsp_002__section__questions", component: "GuidedFormSection", fields: ["party_name", "publication_scope", "questions", "request_id", "support_action"] }, { id: "references", region: "evidence", testId: "rsp_002__section__references", component: "StructuredContentSection", fields: ["attachment_policy", "verified_contact"] }, { id: "deadline", region: "state", testId: "rsp_002__section__deadline", component: "StructuredContentSection", fields: ["due_at", "request_status"] }, { id: "public-use", region: "unknown", testId: "rsp_002__section__public-use", component: "SensitiveDataNotice", fields: ["publication_uncertainty"] }, { id: "support", region: "state", testId: "rsp_002__section__support", component: "StructuredContentSection", fields: ["support_contact", "support_deadline"] }],
  },
  "RSP-003": {
    route: "/respond/answer",
    objectLabel: "답변 작성",
    persona: "소명 대상자",
    primaryActionId: "save-draft",
    primaryActionLabel: "답변 임시 저장",
    sections: [{ id: "progress", region: "object", testId: "rsp_003__section__progress", component: "StepIndicator", fields: ["draft_version", "request_id"] }, { id: "questions", region: "answer", testId: "rsp_003__section__questions", component: "GuidedFormSection", fields: ["answers"] }, { id: "statement", region: "evidence", testId: "rsp_003__section__statement", component: "StructuredContentSection", fields: ["attachments", "consent_evidence"] }, { id: "consent", region: "unknown", testId: "rsp_003__section__consent", component: "StructuredContentSection", fields: ["validation_unknowns"] }, { id: "save", region: "state", testId: "rsp_003__section__save", component: "SaveStatus", fields: ["expires_at", "save_action", "saved_at"] }],
  },
  "RSP-004": {
    route: "/respond/attachments",
    objectLabel: "첨부자료",
    persona: "소명 대상자",
    primaryActionId: "select-file",
    primaryActionLabel: "파일 선택",
    sections: [{ id: "guidance", region: "object", testId: "rsp_004__section__guidance", component: "SensitiveDataNotice", fields: ["request_id", "upload_id"] }, { id: "upload", region: "state", testId: "rsp_004__section__upload", component: "StructuredContentSection", fields: ["upload_target_projection"] }, { id: "metadata", region: "evidence", testId: "rsp_004__section__metadata", component: "StructuredContentSection", fields: ["scan_receipt"] }, { id: "scan", region: "state", testId: "rsp_004__section__scan", component: "NotificationBanner", fields: ["scan_unknowns", "upload_status", "upload_version"] }, { id: "files", region: "answer", testId: "rsp_004__section__files", component: "FileUploadQueue", fields: ["file_actions", "upload_guidance"] }],
  },
  "RSP-005": {
    route: "/respond/review",
    objectLabel: "제출 전 확인",
    persona: "소명 대상자",
    primaryActionId: "submit",
    primaryActionLabel: "답변 제출",
    sections: [{ id: "answers", region: "object", testId: "rsp_005__section__answers", component: "CheckAnswers", fields: ["answers", "request_summary", "submission_digest"] }, { id: "attachments", region: "evidence", testId: "rsp_005__section__attachments", component: "FileUploadQueue", fields: ["attachments", "publication_consent"] }, { id: "consent", region: "unknown", testId: "rsp_005__section__consent", component: "GuidedFormSection", fields: ["material_unknowns"] }, { id: "authority", region: "state", testId: "rsp_005__section__authority", component: "GuidedFormSection", fields: ["authority_attestation_projection"] }, { id: "consequence", region: "state", testId: "rsp_005__section__consequence", component: "GuidedFormSection", fields: ["blocking_state", "receipt_identity"] }],
  },
  "RSP-006": {
    route: "/respond/receipt",
    objectLabel: "소명 접수 영수증",
    persona: "소명 대상자",
    primaryActionId: "download-receipt",
    primaryActionLabel: "영수증 다운로드",
    sections: [{ id: "receipt", region: "object", testId: "rsp_006__section__receipt", component: "DecisionReceipt", fields: ["receipt_and_status_links", "receipt_id", "receipt_status", "receipt_title", "receipt_version"] }, { id: "summary", region: "answer", testId: "rsp_006__section__summary", component: "CheckAnswers", fields: ["submission_summary", "submitted_items"] }, { id: "next", region: "unknown", testId: "rsp_006__section__next", component: "GuidedFormSection", fields: ["appeal_and_download_actions", "next_step_unknowns"] }, { id: "download", region: "state", testId: "rsp_006__section__download", component: "StructuredContentSection", fields: ["receipt_download_projection"] }],
  },
  "RSP-007": {
    route: "/respond/extension",
    objectLabel: "기한 연장 요청",
    persona: "소명 대상자",
    primaryActionId: "submit-extension",
    primaryActionLabel: "연장 요청 제출",
    sections: [{ id: "current", region: "object", testId: "rsp_007__section__current", component: "StructuredContentSection", fields: ["extension_id", "request_id", "request_receipt"] }, { id: "request", region: "answer", testId: "rsp_007__section__request", component: "StructuredContentSection", fields: ["requested_at"] }, { id: "partial", region: "unknown", testId: "rsp_007__section__partial", component: "GuidedFormSection", fields: ["partial_answer_unknowns"] }, { id: "review", region: "state", testId: "rsp_007__section__review", component: "CheckAnswers", fields: ["extension_status", "extension_version", "status_action"] }],
  },
  "RSP-008": {
    route: "/respond/unavailable",
    objectLabel: "요청에 접근할 수 없음",
    persona: "소명 대상자",
    primaryActionId: "request-new-link",
    primaryActionLabel: "새 링크 요청 안내",
    sections: [{ id: "status", region: "object", testId: "rsp_008__section__status", component: "NotificationBanner", fields: ["access_status", "safe_request_reference", "status_version"] }, { id: "impact", region: "answer", testId: "rsp_008__section__impact", component: "StructuredContentSection", fields: ["impact_summary", "non_disclosing_reason"] }, { id: "actions", region: "next_action", testId: "rsp_008__section__actions", component: "StructuredContentSection", fields: ["safe_actions"] }, { id: "security", region: "evidence", testId: "rsp_008__section__security", component: "StructuredContentSection", fields: ["support_reference"] }],
  },
  "RULE-001": {
    route: "/internal/rules",
    objectLabel: "탐지 규칙 Registry",
    persona: "조사 담당자",
    primaryActionId: "open-rule",
    primaryActionLabel: "규칙 보기",
    sections: [{ id: "status", region: "object", testId: "rule_001__section__status", component: "StatusAndRevisionHeader", fields: ["status_object", "status_state"] }, { id: "filters", region: "state", testId: "rule_001__section__filters", component: "UnifiedSearch", fields: ["rule_filters"] }, { id: "registry", region: "answer", testId: "rule_001__section__registry", component: "DataCollection", fields: ["registry_answer", "registry_next_action"] }, { id: "changes", region: "evidence", testId: "rule_001__section__changes", component: "StructuredContentSection", fields: ["changes_evidence", "changes_unknown"] }],
  },
  "RULE-002": {
    route: "/internal/rules/{ruleId}/versions/{version}",
    objectLabel: "규칙 Version 상세",
    persona: "조사 담당자",
    primaryActionId: "create-draft",
    primaryActionLabel: "다음 version 초안",
    sections: [{ id: "identity", region: "object", testId: "rule_002__section__identity", component: "StatusAndRevisionHeader", fields: ["rule_id", "rule_version"] }, { id: "definition", region: "answer", testId: "rule_002__section__definition", component: "GuidedFormSection", fields: ["cohort_and_formula", "definition_summary"] }, { id: "cohort", region: "state", testId: "rule_002__section__cohort", component: "ComparisonWorkbench", fields: ["cohort_projection"] }, { id: "blockers", region: "unknown", testId: "rule_002__section__blockers", component: "StructuredContentSection", fields: ["blockers"] }, { id: "diff", region: "state", testId: "rule_002__section__diff", component: "StructuredContentSection", fields: ["diff_projection"] }, { id: "usage", region: "evidence", testId: "rule_002__section__usage", component: "SignalTriagePanel", fields: ["usage_and_change_evidence"] }, { id: "approval", region: "state", testId: "rule_002__section__approval", component: "RevisionTimeline", fields: ["approval_state", "draft_and_approval_actions", "updated_at"] }],
  },
  "RULE-003": {
    route: "/internal/rules/{ruleId}/versions/{version}/evaluation",
    objectLabel: "규칙 평가·Shadow",
    persona: "조사 담당자",
    primaryActionId: "run-evaluation",
    primaryActionLabel: "평가 실행",
    sections: [{ id: "dataset", region: "object", testId: "rule_003__section__dataset", component: "CoverageStatement", fields: ["evaluation_id", "evaluation_version"] }, { id: "metrics", region: "answer", testId: "rule_003__section__metrics", component: "StructuredContentSection", fields: ["metric_summary", "threshold_results"] }, { id: "errors", region: "evidence", testId: "rule_003__section__errors", component: "StructuredContentSection", fields: ["dataset_and_error_evidence"] }, { id: "threshold", region: "state", testId: "rule_003__section__threshold", component: "StructuredContentSection", fields: ["threshold_projection"] }, { id: "shadow", region: "state", testId: "rule_003__section__shadow", component: "StructuredContentSection", fields: ["shadow_projection"] }, { id: "limitations", region: "unknown", testId: "rule_003__section__limitations", component: "StructuredContentSection", fields: ["limitations"] }, { id: "signoff", region: "state", testId: "rule_003__section__signoff", component: "DecisionReviewPanel", fields: ["evaluated_at", "signoff_actions", "signoff_state"] }],
  },
  "RULE-004": {
    route: "/internal/rules/{ruleId}/versions/{version}/activation",
    objectLabel: "규칙 활성화",
    persona: "조사 담당자",
    primaryActionId: "activate",
    primaryActionLabel: "규칙 활성화",
    sections: [{ id: "target", region: "object", testId: "rule_004__section__target", component: "StructuredContentSection", fields: ["rule_id", "rule_version"] }, { id: "gates", region: "state", testId: "rule_004__section__gates", component: "DecisionReviewPanel", fields: ["blocking_gates", "evaluated_at", "gate_state"] }, { id: "impact", region: "answer", testId: "rule_004__section__impact", component: "SignalTriagePanel", fields: ["activation_plan", "impact_summary"] }, { id: "schedule", region: "state", testId: "rule_004__section__schedule", component: "StructuredContentSection", fields: ["schedule_projection"] }, { id: "rollback", region: "evidence", testId: "rule_004__section__rollback", component: "StructuredContentSection", fields: ["rollback_and_evaluation_evidence"] }, { id: "approval", region: "next_action", testId: "rule_004__section__approval", component: "DecisionReviewPanel", fields: ["approval_actions"] }, { id: "receipt", region: "state", testId: "rule_004__section__receipt", component: "DataCollection", fields: ["activation_receipt_projection"] }],
  },
  "SIG-001": {
    route: "/internal/signals",
    objectLabel: "Signal Queue",
    persona: "조사 담당자",
    primaryActionId: "assign",
    primaryActionLabel: "담당자 지정",
    sections: [{ id: "scope", region: "object", testId: "sig_001__section__scope", component: "StatusAndRevisionHeader", fields: ["scope_evidence", "scope_object"] }, { id: "filters", region: "state", testId: "sig_001__section__filters", component: "UnifiedSearch", fields: ["signal_filters"] }, { id: "table", region: "state", testId: "sig_001__section__table", component: "ComparisonWorkbench", fields: ["table_answer", "table_next_action", "table_state", "table_unknown"] }, { id: "bulk", region: "state", testId: "sig_001__section__bulk", component: "StructuredContentSection", fields: ["bulk_selection_projection"] }],
  },
  "SIG-002": {
    route: "/internal/signals/{signalId}",
    objectLabel: "Signal 검토",
    persona: "조사 담당자",
    primaryActionId: "promote",
    primaryActionLabel: "사건으로 승격",
    sections: [{ id: "identity", region: "object", testId: "sig_002__section__identity", component: "CoverageStatement", fields: ["signal_identity"] }, { id: "calculation", region: "answer", testId: "sig_002__section__calculation", component: "ComparisonWorkbench", fields: ["calculation_answer", "comparison"] }, { id: "quality", region: "state", testId: "sig_002__section__quality", component: "StructuredContentSection", fields: ["quality_state"] }, { id: "cohort", region: "unknown", testId: "sig_002__section__cohort", component: "ComparisonWorkbench", fields: ["duplicate_unknowns", "quality_unknowns"] }, { id: "provenance", region: "evidence", testId: "sig_002__section__provenance", component: "EvidenceLedger", fields: ["audit_evidence", "calculation_evidence"] }, { id: "related", region: "state", testId: "sig_002__section__related", component: "SignalTriagePanel", fields: ["related_case_projection"] }, { id: "ai", region: "state", testId: "sig_002__section__ai", component: "AgentSuggestionPanel", fields: ["ai_assistance_projection"] }, { id: "decision", region: "next_action", testId: "sig_002__section__decision", component: "DecisionReviewPanel", fields: ["triage_action"] }],
  },
  "SRC-001": {
    route: "/internal/sources",
    objectLabel: "Source Registry",
    persona: "조사 담당자",
    primaryActionId: "ack-incident",
    primaryActionLabel: "incident 확인",
    sections: [{ id: "health", region: "state", testId: "src_001__section__health", component: "StatusAndRevisionHeader", fields: ["health_state", "health_unknown"] }, { id: "filters", region: "state", testId: "src_001__section__filters", component: "UnifiedSearch", fields: ["source_filters"] }, { id: "registry", region: "answer", testId: "src_001__section__registry", component: "DataCollection", fields: ["registry_answer", "registry_next_action"] }, { id: "impact", region: "evidence", testId: "src_001__section__impact", component: "CoverageStatement", fields: ["impact_evidence"] }, { id: "ownership", region: "object", testId: "src_001__section__ownership", component: "StructuredContentSection", fields: ["ownership_object"] }],
  },
  "SRC-002": {
    route: "/internal/sources/{sourceId}",
    objectLabel: "Source 상세",
    persona: "조사 담당자",
    primaryActionId: "start-manual-run",
    primaryActionLabel: "수동 실행 요청",
    sections: [{ id: "identity", region: "object", testId: "src_002__section__identity", component: "StructuredContentSection", fields: ["source_id", "source_version"] }, { id: "status", region: "state", testId: "src_002__section__status", component: "StatusAndRevisionHeader", fields: ["source_status", "updated_at"] }, { id: "checkpoint", region: "state", testId: "src_002__section__checkpoint", component: "StructuredContentSection", fields: ["checkpoint_projection"] }, { id: "quality", region: "answer", testId: "src_002__section__quality", component: "StructuredContentSection", fields: ["checkpoint_and_schema", "quality_summary"] }, { id: "schema", region: "evidence", testId: "src_002__section__schema", component: "StructuredContentSection", fields: ["runbook_and_schema_evidence"] }, { id: "downstream", region: "unknown", testId: "src_002__section__downstream", component: "StructuredContentSection", fields: ["downstream_unknowns"] }, { id: "runbook", region: "next_action", testId: "src_002__section__runbook", component: "StructuredContentSection", fields: ["source_actions"] }],
  },
  "SRC-003": {
    route: "/internal/sources/{sourceId}/runs",
    objectLabel: "Source 실행 기록",
    persona: "조사 담당자",
    primaryActionId: "retry-run",
    primaryActionLabel: "안전한 재시도",
    sections: [{ id: "summary", region: "object", testId: "src_003__section__summary", component: "OperationsStatusPanel", fields: ["summary_object"] }, { id: "filters", region: "state", testId: "src_003__section__filters", component: "UnifiedSearch", fields: ["source_run_filters"] }, { id: "runs", region: "state", testId: "src_003__section__runs", component: "DataCollection", fields: ["runs_answer", "runs_next_action", "runs_state", "runs_unknown"] }, { id: "schedule", region: "evidence", testId: "src_003__section__schedule", component: "StructuredContentSection", fields: ["schedule_evidence"] }],
  },
  "SRC-004": {
    route: "/internal/sources/{sourceId}/runs/{runId}",
    objectLabel: "Source 실행 상세",
    persona: "조사 담당자",
    primaryActionId: "retry-failed",
    primaryActionLabel: "실패 구간 재시도",
    sections: [{ id: "identity", region: "object", testId: "src_004__section__identity", component: "StructuredContentSection", fields: ["run_id", "run_version"] }, { id: "scope", region: "state", testId: "src_004__section__scope", component: "StructuredContentSection", fields: ["run_scope_projection"] }, { id: "counts", region: "state", testId: "src_004__section__counts", component: "StructuredContentSection", fields: ["run_status", "updated_at"] }, { id: "errors", region: "answer", testId: "src_004__section__errors", component: "StructuredContentSection", fields: ["errors", "record_flow_summary"] }, { id: "artifacts", region: "evidence", testId: "src_004__section__artifacts", component: "StructuredContentSection", fields: ["artifacts_and_audit"] }, { id: "impact", region: "unknown", testId: "src_004__section__impact", component: "StructuredContentSection", fields: ["impact_and_unknowns"] }, { id: "actions", region: "next_action", testId: "src_004__section__actions", component: "StructuredContentSection", fields: ["recovery_actions"] }],
  },
  "SRC-005": {
    route: "/internal/sources/{sourceId}/schema-drift",
    objectLabel: "Schema Drift",
    persona: "조사 담당자",
    primaryActionId: "reject-mapping",
    primaryActionLabel: "변경 요청",
    sections: [{ id: "alert", region: "object", testId: "src_005__section__alert", component: "StructuredContentSection", fields: ["drift_id", "drift_version"] }, { id: "diff", region: "answer", testId: "src_005__section__diff", component: "StructuredContentSection", fields: ["mapping_impact", "schema_diff_summary"] }, { id: "samples", region: "evidence", testId: "src_005__section__samples", component: "StructuredContentSection", fields: ["samples_and_shadow_evidence"] }, { id: "impact", region: "unknown", testId: "src_005__section__impact", component: "StructuredContentSection", fields: ["impact_unknowns"] }, { id: "mapping", region: "state", testId: "src_005__section__mapping", component: "StructuredContentSection", fields: ["mapping_projection"] }, { id: "shadow", region: "state", testId: "src_005__section__shadow", component: "DataCollection", fields: ["shadow_result_projection"] }, { id: "decision", region: "state", testId: "src_005__section__decision", component: "DecisionReviewPanel", fields: ["decision_state", "detected_at", "mapping_decision_actions"] }],
  },
  "SRC-006": {
    route: "/internal/sources/{sourceId}/backfill",
    objectLabel: "Backfill·Replay",
    persona: "조사 담당자",
    primaryActionId: "estimate",
    primaryActionLabel: "영향 계산",
    sections: [{ id: "scope", region: "object", testId: "src_006__section__scope", component: "CoverageStatement", fields: ["backfill_plan_id", "plan_version"] }, { id: "estimate", region: "answer", testId: "src_006__section__estimate", component: "DataCollection", fields: ["downstream_impact", "estimate_summary"] }, { id: "dedupe", region: "evidence", testId: "src_006__section__dedupe", component: "StructuredContentSection", fields: ["dedupe_and_checkpoint_evidence"] }, { id: "downstream", region: "state", testId: "src_006__section__downstream", component: "StructuredContentSection", fields: ["downstream_impact_projection"] }, { id: "safety", region: "unknown", testId: "src_006__section__safety", component: "StructuredContentSection", fields: ["safety_unknowns"] }, { id: "approval", region: "next_action", testId: "src_006__section__approval", component: "DecisionReviewPanel", fields: ["approval_and_start_actions"] }, { id: "progress", region: "state", testId: "src_006__section__progress", component: "StatusAndRevisionHeader", fields: ["estimated_at", "progress_state"] }],
  },
} as const;
