import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-002",
  title: "사건 개요",
  route: "/internal/cases/{caseId}/overview",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "header",
      title: "식별 정보·상태·버전",
      component: "StructuredContentSection",
      purpose: "assignment·due.",
      test_id: "cas_002__section__header",
    },
    {
      order: 2,
      id: "known-unknown",
      title: "확인·미확인·소명",
      component: "KnownUnknownResponse",
      purpose: "핵심 요약.",
      test_id: "cas_002__section__known-unknown",
    },
    {
      order: 3,
      id: "readiness",
      title: "진행·통과 조건",
      component: "StructuredContentSection",
      purpose: "blocking task.",
      test_id: "cas_002__section__readiness",
    },
    {
      order: 4,
      id: "next",
      title: "다음 작업",
      component: "AccessManagementPanel",
      purpose: "role-aware.",
      test_id: "cas_002__section__next",
    },
    {
      order: 5,
      id: "activity",
      title: "최근 변경",
      component: "StructuredContentSection",
      purpose: "audit-linked.",
      test_id: "cas_002__section__activity",
    },
  ],
  actions: [
    {
      id: "start-next",
      label: "다음 작업 수행",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "transition",
      label: "상태 전이",
      capability: "cases.investigate",
      operation_id: "transitionCase",
      guard: "allowed transition + reason",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "assign",
      label: "담당자 변경",
      capability: "cases.assign",
      operation_id: "assignCase",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getInternalCase",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-internal-case",
      blocking: true,
      response_schema: "InternalCaseResponse",
    },
    {
      operation_id: "getCaseWorkspaceOverview",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-case-workspace-overview",
      blocking: true,
      response_schema: "CaseWorkspaceOverviewResponse",
    },
    {
      operation_id: "transitionCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/transition-case",
      blocking: true,
      response_schema: "transitionCaseReceipt",
    },
    {
      operation_id: "assignCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/assign-case",
      blocking: false,
      response_schema: "assignCaseReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
