import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SIG-001",
  title: "Signal Queue",
  route: "/internal/signals",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "queue 상태",
      component: "StatusAndRevisionHeader",
      purpose: "SLA·count.",
      test_id: "sig_001__section__scope",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "rule/source/quality/state.",
      test_id: "sig_001__section__filters",
    },
    {
      order: 3,
      id: "table",
      title: "신호",
      component: "ComparisonWorkbench",
      purpose: "metric·cohort·freshness·assignment.",
      test_id: "sig_001__section__table",
    },
    {
      order: 4,
      id: "bulk",
      title: "제한된 bulk",
      component: "StructuredContentSection",
      purpose: "assign/label.",
      test_id: "sig_001__section__bulk",
    },
  ],
  actions: [
    {
      id: "open-signal",
      label: "신호 검토",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "assign",
      label: "담당자 지정",
      capability: "signals.triage",
      operation_id: "assignSignal",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "save-view",
      label: "보기 저장",
      capability: "none",
      operation_id: "createSavedView",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listSignals",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-signals",
      blocking: true,
      response_schema: "SignalsPage",
    },
    {
      operation_id: "assignSignal",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/assign-signal",
      blocking: false,
      response_schema: "assignSignalReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
