import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-026",
  title: "문의",
  route: "/contact",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "routing",
      title: "문의 유형",
      component: "KnownUnknownResponse",
      purpose: "정정/소명/보안/언론/일반.",
      test_id: "pub_026__section__routing",
    },
    {
      order: 2,
      id: "channels",
      title: "연락 방법",
      component: "StatusAndRevisionHeader",
      purpose: "각 SLA와 안전 안내.",
      test_id: "pub_026__section__channels",
    },
    {
      order: 3,
      id: "form",
      title: "일반 문의",
      component: "GuidedFormSection",
      purpose: "최소 field.",
      test_id: "pub_026__section__form",
    },
    {
      order: 4,
      id: "security",
      title: "민감자료",
      component: "GuidedFormSection",
      purpose: "이메일 첨부 금지와 보안 채널.",
      test_id: "pub_026__section__security",
    },
  ],
  actions: [
    {
      id: "submit-contact",
      label: "문의 보내기",
      capability: "none",
      operation_id: "createContactRequest",
      interaction_kind: "COMMAND",
      assurance_level: "ANONYMOUS_PROOF",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-correction",
      label: "정정 요청",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "security-report",
      label: "보안 신고 안내",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "createContactRequest",
      api: "submission-api",
      method: "POST",
      path: "/v1/contact-requests",
      blocking: false,
      response_schema: "createContactRequestReceipt",
    },
    {
      operation_id: "getContactContent",
      api: "public-api",
      method: "GET",
      path: "/v1/content/contact",
      blocking: false,
      response_schema: "ContactContentResponse",
    },
  ],
} as const satisfies ScreenViewModel;
