import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-009",
  title: "소명 요청 작성",
  route: "/internal/cases/{caseId}/responses/new",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "target",
      title: "대상·연락처",
      component: "StructuredContentSection",
      purpose: "source·latest verification.",
      test_id: "cas_009__section__target",
    },
    {
      order: 2,
      id: "questions",
      title: "질문",
      component: "EvidenceLedger",
      purpose: "claim/evidence reference.",
      test_id: "cas_009__section__questions",
    },
    {
      order: 3,
      id: "deadline",
      title: "기한",
      component: "StructuredContentSection",
      purpose: "timezone·extension.",
      test_id: "cas_009__section__deadline",
    },
    {
      order: 4,
      id: "disclosure",
      title: "공개·개인정보 안내",
      component: "StatusAndRevisionHeader",
      purpose: "template.",
      test_id: "cas_009__section__disclosure",
    },
    {
      order: 5,
      id: "preview",
      title: "이메일·포털 미리보기",
      component: "DecisionReviewPanel",
      purpose: "phishing guidance.",
      test_id: "cas_009__section__preview",
    },
    {
      order: 6,
      id: "gate",
      title: "발송 조건",
      component: "StructuredContentSection",
      purpose: "duplicate/legal.",
      test_id: "cas_009__section__gate",
    },
  ],
  actions: [
    {
      id: "save-draft",
      label: "요청 임시 저장",
      capability: "responses.request",
      operation_id: "saveResponseRequestDraft",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "send-request",
      label: "소명 요청 발송",
      capability: "responses.request",
      operation_id: "createResponseRequest",
      guard: "review + reason + idempotency",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getResponseRequestComposer",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-response-request-composer",
      blocking: true,
      response_schema: "ResponseRequestComposerResponse",
    },
    {
      operation_id: "saveResponseRequestDraft",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/save-response-request-draft",
      blocking: false,
      response_schema: "saveResponseRequestDraftReceipt",
    },
    {
      operation_id: "createResponseRequest",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-response-request",
      blocking: true,
      response_schema: "createResponseRequestReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
