import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-015",
  title: "사건 정정·철회",
  route: "/internal/cases/{caseId}/corrections",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "history",
      title: "revision·정정 이력",
      component: "StatusAndRevisionHeader",
      purpose: "immutable.",
      test_id: "cas_015__section__history",
    },
    {
      order: 2,
      id: "requests",
      title: "외부·내부 요청",
      component: "StatusAndRevisionHeader",
      purpose: "status/SLA.",
      test_id: "cas_015__section__requests",
    },
    {
      order: 3,
      id: "proposal",
      title: "정정 초안",
      component: "RevisionAndCorrectionPanel",
      purpose: "before/after/reason.",
      test_id: "cas_015__section__proposal",
    },
    {
      order: 4,
      id: "impact",
      title: "영향 분석",
      component: "StructuredContentSection",
      purpose: "API/download/notification.",
      test_id: "cas_015__section__impact",
    },
    {
      order: 5,
      id: "reviews",
      title: "검토",
      component: "DecisionReviewPanel",
      purpose: "editorial/legal/publish.",
      test_id: "cas_015__section__reviews",
    },
  ],
  actions: [
    {
      id: "start-correction",
      label: "정정 작업 시작",
      capability: "publication.correct",
      operation_id: "createCorrection",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "start-retraction",
      label: "철회 검토 시작",
      capability: "publication.retract",
      operation_id: "createRetractionDraft",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "open-request",
      label: "정정 요청 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseCorrections",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-corrections",
      blocking: true,
      response_schema: "CaseCorrectionsPage",
    },
    {
      operation_id: "createCorrection",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-correction",
      blocking: true,
      response_schema: "createCorrectionReceipt",
    },
    {
      operation_id: "createRetractionDraft",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-retraction-draft",
      blocking: false,
      response_schema: "createRetractionDraftReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
