import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SIG-002",
  title: "신호 검토",
  route: "/internal/signals/{signalId}",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "출처·규칙·최신성",
      component: "CoverageStatement",
      purpose: "입력 version.",
      test_id: "sig_002__section__identity",
    },
    {
      order: 2,
      id: "calculation",
      title: "결정적 계산",
      component: "ComparisonWorkbench",
      purpose: "input/formula/result.",
      test_id: "sig_002__section__calculation",
    },
    {
      order: 3,
      id: "quality",
      title: "차단 요인·품질",
      component: "StructuredContentSection",
      purpose: "unit/VAT/bundle.",
      test_id: "sig_002__section__quality",
    },
    {
      order: 4,
      id: "cohort",
      title: "비교군",
      component: "ComparisonWorkbench",
      purpose: "분포·제외.",
      test_id: "sig_002__section__cohort",
    },
    {
      order: 5,
      id: "provenance",
      title: "원본",
      component: "EvidenceLedger",
      purpose: "field locator.",
      test_id: "sig_002__section__provenance",
    },
    {
      order: 6,
      id: "related",
      title: "관련 신호·사건",
      component: "SignalTriagePanel",
      purpose: "duplicate.",
      test_id: "sig_002__section__related",
    },
    {
      order: 7,
      id: "ai",
      title: "인공지능 제안",
      component: "AgentSuggestionPanel",
      purpose: "보조.",
      test_id: "sig_002__section__ai",
    },
    {
      order: 8,
      id: "decision",
      title: "분류 결정",
      component: "DecisionReviewPanel",
      purpose: "reason code.",
      test_id: "sig_002__section__decision",
    },
  ],
  actions: [
    {
      id: "promote",
      label: "사건으로 승격",
      capability: "signals.triage",
      operation_id: "triageSignal",
      guard: "reason + expected version",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "link",
      label: "기존 사건 연결",
      capability: "signals.triage",
      operation_id: "triageSignal",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "mark-duplicate",
      label: "중복 신호로 표시",
      capability: "signals.triage",
      operation_id: "triageSignal",
      guard: "duplicate target + reason + expected version",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: true,
      preset: { decision: "duplicate" },
    },
    {
      id: "needs-data",
      label: "추가 자료 필요",
      capability: "signals.triage",
      operation_id: "triageSignal",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "dismiss",
      label: "신호 제외",
      capability: "signals.triage",
      operation_id: "triageSignal",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getSignalTriageView",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-signal-triage-view",
      blocking: true,
      response_schema: "SignalTriageViewResponse",
    },
    {
      operation_id: "triageSignal",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/triage-signal",
      blocking: true,
      response_schema: "triageSignalReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
