from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path


SCRIPTS = Path(__file__).resolve().parents[1]
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from validation.evidence import (
    CODEGEN_OUTPUT_DIRECTORIES,
    _validate_codegen_tree,
)
from validation.models import Validation
from verify_release_archives import tree_digest


class CodegenTreeEvidenceTests(unittest.TestCase):
    def _fixture(self, root: Path) -> tuple[Path, dict[str, int | str]]:
        relative = CODEGEN_OUTPUT_DIRECTORIES['public']
        output = root / relative
        nested = output / 'core'
        nested.mkdir(parents=True)
        (output / 'index.ts').write_text('export const value = 1;\n', encoding='utf-8')
        (nested / 'types.ts').write_text('export type Value = number;\n', encoding='utf-8')
        digest, file_count = tree_digest(output)
        generated_bytes = sum(
            path.stat().st_size for path in output.rglob('*') if path.is_file()
        )
        return output, {
            'generated_files': file_count,
            'generated_bytes': generated_bytes,
            'tree_sha256': digest,
        }

    def test_output_directories_cover_exactly_five_generation_targets(self) -> None:
        self.assertEqual(
            CODEGEN_OUTPUT_DIRECTORIES,
            {
                'public': 'packages/api-client-public/src/generated',
                'control': 'packages/api-client-control/src/generated',
                'submission': 'packages/api-client-submission/src/generated',
                'identity-internal': 'packages/api-client-identity-internal/src/generated',
                'identity-api': 'packages/api-client-identity-internal/src/generated-procurement',
            },
        )

    def test_exact_tree_evidence_passes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _, evidence = self._fixture(root)
            result = Validation()

            _validate_codegen_tree(root, result, 'public', evidence)

        self.assertEqual(result.errors, [])

    def test_stale_tree_hash_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _, evidence = self._fixture(root)
            evidence['tree_sha256'] = '0' * 64
            result = Validation()

            _validate_codegen_tree(root, result, 'public', evidence)

        self.assertEqual(
            result.errors,
            ['public: generated tree hash differs from output tree'],
        )

    def test_stale_generated_byte_count_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _, evidence = self._fixture(root)
            evidence['generated_bytes'] = int(evidence['generated_bytes']) + 1
            result = Validation()

            _validate_codegen_tree(root, result, 'public', evidence)

        self.assertEqual(
            result.errors,
            ['public: generated byte count differs from output tree'],
        )

    def test_stale_generated_file_count_is_rejected(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            _, evidence = self._fixture(root)
            evidence['generated_files'] = int(evidence['generated_files']) + 1
            result = Validation()

            _validate_codegen_tree(root, result, 'public', evidence)

        self.assertEqual(
            result.errors,
            ['public: generated file count differs from output tree'],
        )


if __name__ == '__main__':
    unittest.main()
