import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RULE-001",
  title: "탐지 규칙 등록부",
  route: "/internal/rules",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "status",
      title: "규칙 상태",
      component: "StatusAndRevisionHeader",
      purpose: "active/shadow/retired.",
      test_id: "rule_001__section__status",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "type/owner/state.",
      test_id: "rule_001__section__filters",
    },
    {
      order: 3,
      id: "registry",
      title: "규칙 목록",
      component: "DataCollection",
      purpose: "version·eval·last run.",
      test_id: "rule_001__section__registry",
    },
    {
      order: 4,
      id: "changes",
      title: "최근 변경",
      component: "StructuredContentSection",
      purpose: "activation/rollback.",
      test_id: "rule_001__section__changes",
    },
  ],
  actions: [
    {
      id: "open-rule",
      label: "규칙 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "propose-version",
      label: "새 버전 제안",
      capability: "rules.propose",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listInternalRules",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-internal-rules",
      blocking: true,
      response_schema: "InternalRulesPage",
    },
  ],
} as const satisfies ScreenViewModel;
