import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-003",
  title: "연결된 신호",
  route: "/internal/cases/{caseId}/signals",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "연결 요약",
      component: "ComparisonWorkbench",
      purpose: "rule·source 분포.",
      test_id: "cas_003__section__summary",
    },
    {
      order: 2,
      id: "signals",
      title: "탐지 신호 목록",
      component: "DataCollection",
      purpose: "metric·state·link reason.",
      test_id: "cas_003__section__signals",
    },
    {
      order: 3,
      id: "relationships",
      title: "중복·연결",
      component: "StructuredContentSection",
      purpose: "merge/split context.",
      test_id: "cas_003__section__relationships",
    },
  ],
  actions: [
    {
      id: "open-signal",
      label: "신호 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "link-signal",
      label: "신호 연결",
      capability: "cases.investigate",
      operation_id: "linkSignalToCase",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "unlink-signal",
      label: "연결 해제",
      capability: "cases.investigate",
      operation_id: "unlinkSignalFromCase",
      guard: "reason + impact",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseSignals",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-signals",
      blocking: true,
      response_schema: "CaseSignalsPage",
    },
    {
      operation_id: "linkSignalToCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/link-signal-to-case",
      blocking: false,
      response_schema: "linkSignalToCaseReceipt",
    },
    {
      operation_id: "unlinkSignalFromCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/unlink-signal-from-case",
      blocking: false,
      response_schema: "unlinkSignalFromCaseReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
