import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "ADM-002",
  title: "사용자 상세·역할",
  route: "/internal/admin/users/{userId}",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "identity",
      component: "StatusAndRevisionHeader",
      purpose: "IdP·status.",
      test_id: "adm_002__section__identity",
    },
    {
      order: 2,
      id: "roles",
      title: "role·scope",
      component: "AccessManagementPanel",
      purpose: "grant/expiry.",
      test_id: "adm_002__section__roles",
    },
    {
      order: 3,
      id: "conflicts",
      title: "SoD",
      component: "AccessManagementPanel",
      purpose: "conflicting roles.",
      test_id: "adm_002__section__conflicts",
    },
    {
      order: 4,
      id: "sessions",
      title: "session",
      component: "StructuredContentSection",
      purpose: "active/revoke.",
      test_id: "adm_002__section__sessions",
    },
    {
      order: 5,
      id: "requests",
      title: "pending",
      component: "StructuredContentSection",
      purpose: "reason/approver.",
      test_id: "adm_002__section__requests",
    },
    {
      order: 6,
      id: "activity",
      title: "고위험 audit",
      component: "CoverageStatement",
      purpose: "최소 범위.",
      test_id: "adm_002__section__activity",
    },
    {
      order: 7,
      id: "offboarding",
      title: "offboarding",
      component: "StructuredContentSection",
      purpose: "revoke plan.",
      test_id: "adm_002__section__offboarding",
    },
  ],
  actions: [
    {
      id: "grant-role",
      label: "역할 부여",
      capability: "roles.grant",
      operation_id: "grantRole",
      guard: "reauth + approver + expiry + SoD",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "revoke-role",
      label: "역할 회수",
      capability: "roles.grant",
      operation_id: "revokeRole",
      guard: "impact + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "revoke-sessions",
      label: "세션 종료",
      capability: "users.manage",
      operation_id: "revokeUserSessions",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "disable-user",
      label: "사용자 비활성화",
      capability: "users.manage",
      operation_id: "disableUser",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getUserAccessDetail",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-user-access-detail",
      blocking: true,
      response_schema: "UserAccessDetailResponse",
    },
    {
      operation_id: "grantRole",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/grant-role",
      blocking: true,
      response_schema: "grantRoleReceipt",
    },
    {
      operation_id: "revokeRole",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/revoke-role",
      blocking: true,
      response_schema: "revokeRoleReceipt",
    },
    {
      operation_id: "revokeUserSessions",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/revoke-user-sessions",
      blocking: false,
      response_schema: "revokeUserSessionsReceipt",
    },
    {
      operation_id: "disableUser",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/disable-user",
      blocking: false,
      response_schema: "disableUserReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
