import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-002",
  title: "작업 대기열·DLQ",
  route: "/internal/operations/jobs",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "대기열 상태",
      component: "DataCollection",
      purpose: "backlog/oldest/DLQ.",
      test_id: "ops_002__section__summary",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "type/state/fingerprint.",
      test_id: "ops_002__section__filters",
    },
    {
      order: 3,
      id: "jobs",
      title: "작업 목록",
      component: "DataCollection",
      purpose: "attempt/lease/next retry.",
      test_id: "ops_002__section__jobs",
    },
    {
      order: 4,
      id: "bulk",
      title: "제한된 일괄 처리",
      component: "StructuredContentSection",
      purpose: "pause/assign category.",
      test_id: "ops_002__section__bulk",
    },
    {
      order: 5,
      id: "runbook",
      title: "복구",
      component: "StructuredContentSection",
      purpose: "safe retry.",
      test_id: "ops_002__section__runbook",
    },
  ],
  actions: [
    {
      id: "open-job",
      label: "작업 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "retry-selected",
      label: "선택 작업 재시도",
      capability: "jobs.operate",
      operation_id: "retryJobs",
      guard: "idempotent + bounded",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "pause-queue",
      label: "대기열 일시 중지",
      capability: "jobs.operate",
      operation_id: "pauseJobQueue",
      guard: "impact + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listJobs",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-jobs",
      blocking: true,
      response_schema: "JobsPage",
    },
    {
      operation_id: "retryJobs",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/retry-jobs",
      blocking: false,
      response_schema: "retryJobsReceipt",
    },
    {
      operation_id: "pauseJobQueue",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/pause-job-queue",
      blocking: false,
      response_schema: "pauseJobQueueReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
