FROM rust:1.97.0-bookworm@sha256:7d0723df719e7f213b69dc7c8c595985c3f4b060cfbee4f7bc0e347a86fe3b6a
RUN curl -fsSL https://bun.sh/install | bash -s "bun-v1.3.14"
ENV PATH="/root/.bun/bin:${PATH}"
WORKDIR /workspace
