import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SRC-001",
  title: "Source Registry",
  route: "/internal/sources",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "health",
      title: "상태 요약",
      component: "StatusAndRevisionHeader",
      purpose: "healthy/stale/incident.",
      test_id: "src_001__section__health",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "owner/type/status.",
      test_id: "src_001__section__filters",
    },
    {
      order: 3,
      id: "registry",
      title: "source 목록",
      component: "DataCollection",
      purpose: "sync·schema·lag·quarantine.",
      test_id: "src_001__section__registry",
    },
    {
      order: 4,
      id: "impact",
      title: "영향",
      component: "CoverageStatement",
      purpose: "rules/public freshness.",
      test_id: "src_001__section__impact",
    },
    {
      order: 5,
      id: "ownership",
      title: "owner/runbook",
      component: "StructuredContentSection",
      purpose: "연락·SLA.",
      test_id: "src_001__section__ownership",
    },
  ],
  actions: [
    {
      id: "open-source",
      label: "source 운영 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "ack-incident",
      label: "incident 확인",
      capability: "sources.operate",
      operation_id: "acknowledgeSourceIncident",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "pause-source",
      label: "source 일시 중지",
      capability: "sources.operate",
      operation_id: "pauseSource",
      guard: "reason + impact",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listInternalSources",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-internal-sources",
      blocking: true,
      response_schema: "InternalSourcesPage",
    },
    {
      operation_id: "acknowledgeSourceIncident",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/acknowledge-source-incident",
      blocking: false,
      response_schema: "acknowledgeSourceIncidentReceipt",
    },
    {
      operation_id: "pauseSource",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/pause-source",
      blocking: false,
      response_schema: "pauseSourceReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
