import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RSP-001",
  title: "소명 요청 확인",
  route: "/respond/access",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "요청 identity",
      component: "CoverageStatement",
      purpose: "요청 ID·조직·사건 공개 범위.",
      test_id: "rsp_001__section__identity",
    },
    {
      order: 2,
      id: "security",
      title: "보안 확인",
      component: "KnownUnknownResponse",
      purpose: "phishing·token 공유 금지.",
      test_id: "rsp_001__section__security",
    },
    {
      order: 3,
      id: "deadline",
      title: "기한",
      component: "StructuredContentSection",
      purpose: "timezone·연장.",
      test_id: "rsp_001__section__deadline",
    },
    {
      order: 4,
      id: "process",
      title: "절차",
      component: "GuidedFormSection",
      purpose: "답변·첨부·검토·제출.",
      test_id: "rsp_001__section__process",
    },
    {
      order: 5,
      id: "verification",
      title: "추가 검증",
      component: "StructuredContentSection",
      purpose: "필요 시 OTP.",
      test_id: "rsp_001__section__verification",
    },
  ],
  actions: [
    {
      id: "continue",
      label: "요청 내용 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "verify",
      label: "추가 검증",
      capability: "none",
      operation_id: "verifyResponseAccess",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "report-problem",
      label: "문제 신고",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "exchangeResponseAccessToken",
      api: "submission-api",
      method: "POST",
      path: "/v1/submission-session/response:exchange",
      blocking: true,
      response_schema: "ExchangeSubmissionSessionResult",
    },
    {
      operation_id: "getResponseAccessStatus",
      api: "submission-api",
      method: "GET",
      path: "/v1/response-session/access-status",
      blocking: true,
      response_schema: "ResponseAccessStatusResponse",
    },
    {
      operation_id: "verifyResponseAccess",
      api: "submission-api",
      method: "POST",
      path: "/v1/response-session:verify",
      blocking: true,
      response_schema: "verifyResponseAccessResult",
    },
  ],
} as const satisfies ScreenViewModel;
