import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-016",
  title: "사건 Audit",
  route: "/internal/cases/{caseId}/audit",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "audit scope",
      component: "StructuredContentSection",
      purpose: "case-linked.",
      test_id: "cas_016__section__scope",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "actor/action/time/risk.",
      test_id: "cas_016__section__filters",
    },
    {
      order: 3,
      id: "events",
      title: "이벤트",
      component: "StructuredContentSection",
      purpose: "before/after·policy decision.",
      test_id: "cas_016__section__events",
    },
    {
      order: 4,
      id: "exports",
      title: "export",
      component: "StructuredContentSection",
      purpose: "watermark·audit.",
      test_id: "cas_016__section__exports",
    },
  ],
  actions: [
    {
      id: "open-event",
      label: "이벤트 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "create-audit-export",
      label: "감사 export 요청",
      capability: "audit.export",
      operation_id: "createAuditExport",
      guard:
        "bounded range + exact scope + reason + watermark policy + expiry + step-up",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseAuditEvents",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-audit-events",
      blocking: true,
      response_schema: "CaseAuditEventsPage",
    },
    {
      operation_id: "createAuditExport",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-audit-export",
      blocking: false,
      response_schema: "createAuditExportReceipt",
    },
    {
      operation_id: "getAuditExport",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-audit-export",
      blocking: false,
      response_schema: "AuditExportResponse",
    },
  ],
} as const satisfies ScreenViewModel;
