import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-025",
  title: "편집·공개 정책",
  route: "/editorial-policy",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "states",
      title: "상태",
      component: "StatusAndRevisionHeader",
      purpose: "탐지·검토·공개·정정·철회 상태 기준.",
      test_id: "pub_025__section__states",
    },
    {
      order: 2,
      id: "publication-gate",
      title: "공개 조건",
      component: "KnownUnknownResponse",
      purpose: "evidence·response·human review.",
      test_id: "pub_025__section__publication-gate",
    },
    {
      order: 3,
      id: "language",
      title: "표현",
      component: "StructuredContentSection",
      purpose: "금지·허용.",
      test_id: "pub_025__section__language",
    },
    {
      order: 4,
      id: "response",
      title: "소명권",
      component: "KnownUnknownResponse",
      purpose: "요청·기한·반영.",
      test_id: "pub_025__section__response",
    },
    {
      order: 5,
      id: "correction",
      title: "정정·철회",
      component: "StatusAndRevisionHeader",
      purpose: "revision.",
      test_id: "pub_025__section__correction",
    },
    {
      order: 6,
      id: "privacy",
      title: "개인정보",
      component: "StructuredContentSection",
      purpose: "redaction.",
      test_id: "pub_025__section__privacy",
    },
    {
      order: 7,
      id: "history",
      title: "정책 변경",
      component: "LongFormArticle",
      purpose: "version/effective date.",
      test_id: "pub_025__section__history",
    },
  ],
  actions: [
    {
      id: "request-correction",
      label: "정정 요청",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-history",
      label: "정책 변경 이력",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getEditorialPolicy",
      api: "public-api",
      method: "GET",
      path: "/v1/content/editorial-policy",
      blocking: false,
      response_schema: "EditorialPolicyResponse",
    },
  ],
} as const satisfies ScreenViewModel;
