import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "ADM-001",
  title: "사용자·접근 관리",
  route: "/internal/admin/users",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "접근 상태",
      component: "StatusAndRevisionHeader",
      purpose: "active/disabled/pending.",
      test_id: "adm_001__section__summary",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "role/status/team.",
      test_id: "adm_001__section__filters",
    },
    {
      order: 3,
      id: "users",
      title: "사용자 목록",
      component: "DataCollection",
      purpose: "identity·roles·last access.",
      test_id: "adm_001__section__users",
    },
    {
      order: 4,
      id: "requests",
      title: "접근 요청",
      component: "StructuredContentSection",
      purpose: "pending.",
      test_id: "adm_001__section__requests",
    },
    {
      order: 5,
      id: "review",
      title: "정기 검토",
      component: "DecisionReviewPanel",
      purpose: "due grants.",
      test_id: "adm_001__section__review",
    },
  ],
  actions: [
    {
      id: "open-user",
      label: "사용자 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "review-access",
      label: "접근 검토 시작",
      capability: "roles.grant",
      operation_id: "startAccessReview",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "invite",
      label: "사용자 초대",
      capability: "users.manage",
      operation_id: "inviteUser",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listUsers",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-users",
      blocking: true,
      response_schema: "UsersPage",
    },
    {
      operation_id: "startAccessReview",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/start-access-review",
      blocking: false,
      response_schema: "startAccessReviewReceipt",
    },
    {
      operation_id: "inviteUser",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/invite-user",
      blocking: false,
      response_schema: "inviteUserReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
