import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "ACC-001",
  title: "내 계정·세션",
  route: "/internal/account",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "내 identity",
      component: "StructuredContentSection",
      purpose: "IdP·조직.",
      test_id: "acc_001__section__identity",
    },
    {
      order: 2,
      id: "roles",
      title: "역할·scope",
      component: "AccessManagementPanel",
      purpose: "read-only.",
      test_id: "acc_001__section__roles",
    },
    {
      order: 3,
      id: "sessions",
      title: "세션",
      component: "StructuredContentSection",
      purpose: "device·last active·revoke.",
      test_id: "acc_001__section__sessions",
    },
    {
      order: 4,
      id: "security",
      title: "보안",
      component: "StructuredContentSection",
      purpose: "MFA/WebAuthn.",
      test_id: "acc_001__section__security",
    },
    {
      order: 5,
      id: "notifications",
      title: "알림 설정",
      component: "StructuredContentSection",
      purpose: "업무 채널.",
      test_id: "acc_001__section__notifications",
    },
    {
      order: 6,
      id: "access-request",
      title: "접근 요청",
      component: "StatusAndRevisionHeader",
      purpose: "status.",
      test_id: "acc_001__section__access-request",
    },
  ],
  actions: [
    {
      id: "revoke-session",
      label: "다른 세션 종료",
      capability: "none",
      operation_id: "revokeOwnSession",
      guard: "reauth when current risk",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "manage-security",
      label: "보안 방법 관리",
      capability: "none",
      operation_id: "getSecurityManagementRedirect",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "request-access",
      label: "접근 권한 요청",
      capability: "none",
      operation_id: "createAccessRequest",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "sign-out",
      label: "로그아웃",
      capability: "none",
      operation_id: "logoutInternalSession",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getCurrentAccount",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-current-account",
      blocking: true,
      response_schema: "CurrentAccountResponse",
    },
    {
      operation_id: "revokeOwnSession",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/revoke-own-session",
      blocking: false,
      response_schema: "revokeOwnSessionReceipt",
    },
    {
      operation_id: "createAccessRequest",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-access-request",
      blocking: false,
      response_schema: "createAccessRequestReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
