import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-005",
  title: "외부 공급자 상태",
  route: "/internal/operations/providers",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "status",
      title: "provider health",
      component: "StatusAndRevisionHeader",
      purpose: "service/status/last checked.",
      test_id: "ops_005__section__status",
    },
    {
      order: 2,
      id: "quotas",
      title: "quota",
      component: "StructuredContentSection",
      purpose: "usage/reset.",
      test_id: "ops_005__section__quotas",
    },
    {
      order: 3,
      id: "latency",
      title: "latency/error",
      component: "StructuredContentSection",
      purpose: "SLO.",
      test_id: "ops_005__section__latency",
    },
    {
      order: 4,
      id: "privacy",
      title: "데이터 정책",
      component: "SensitiveDataNotice",
      purpose: "retention/region/mode.",
      test_id: "ops_005__section__privacy",
    },
    {
      order: 5,
      id: "fallback",
      title: "fallback",
      component: "StructuredContentSection",
      purpose: "allowed routing.",
      test_id: "ops_005__section__fallback",
    },
    {
      order: 6,
      id: "incidents",
      title: "incident",
      component: "OperationsStatusPanel",
      purpose: "impact/history.",
      test_id: "ops_005__section__incidents",
    },
  ],
  actions: [
    {
      id: "open-provider",
      label: "공급자 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "disable-routing",
      label: "Routing 중지",
      capability: "kill_switch.execute",
      operation_id: "disableProviderRouting",
      guard: "scope + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "test",
      label: "연결 테스트",
      capability: "jobs.operate",
      operation_id: "testProviderConnection",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listProviders",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-providers",
      blocking: true,
      response_schema: "ProvidersPage",
    },
    {
      operation_id: "disableProviderRouting",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/disable-provider-routing",
      blocking: false,
      response_schema: "disableProviderRoutingReceipt",
    },
    {
      operation_id: "testProviderConnection",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/test-provider-connection",
      blocking: false,
      response_schema: "testProviderConnectionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
