import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "OPS-005",
  title: "외부 공급자 상태",
  route: "/internal/operations/providers",
  archetype: "OPERATIONS",
  sections: [
    {
      order: 1,
      id: "status",
      title: "공급자 상태",
      component: "StatusAndRevisionHeader",
      purpose: "service/status/last checked.",
      test_id: "ops_005__section__status",
    },
    {
      order: 2,
      id: "quotas",
      title: "사용 한도",
      component: "StructuredContentSection",
      purpose: "usage/reset.",
      test_id: "ops_005__section__quotas",
    },
    {
      order: 3,
      id: "latency",
      title: "지연·오류",
      component: "StructuredContentSection",
      purpose: "SLO.",
      test_id: "ops_005__section__latency",
    },
    {
      order: 4,
      id: "privacy",
      title: "데이터 정책",
      component: "LongFormArticle",
      purpose: "retention/region/mode.",
      test_id: "ops_005__section__privacy",
    },
    {
      order: 5,
      id: "fallback",
      title: "대체 경로",
      component: "StructuredContentSection",
      purpose: "allowed routing.",
      test_id: "ops_005__section__fallback",
    },
    {
      order: 6,
      id: "incidents",
      title: "장애 이력",
      component: "OperationsStatusPanel",
      purpose: "impact/history.",
      test_id: "ops_005__section__incidents",
    },
    {
      order: 7,
      id: "model-catalog",
      title: "모델 카탈로그",
      component: "EvidenceLedger",
      purpose:
        "track prefix 내 relay created 최대. 단가 미설정: 비용 0으로 기록.",
      test_id: "ops_005__section__model-catalog",
    },
  ],
  actions: [
    {
      id: "open-provider",
      label: "공급자 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "disable-routing",
      label: "라우팅 중지 제안",
      capability: "actions.propose",
      operation_id: "disableProviderRouting",
      guard: "scope + reason",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "test",
      label: "연결 테스트 제안",
      capability: "actions.propose",
      operation_id: "testProviderConnection",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "upgrade-model",
      label: "모델 업그레이드 제안",
      capability: "actions.propose",
      operation_id: "upgradeProviderModel",
      expand_request_objects: ["dataPolicy"],
      guard: "connection test + expected version + data policy",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "auto-upgrade",
      label: "자동 업그레이드 설정 제안",
      capability: "actions.propose",
      operation_id: "setModelAutoUpgrade",
      guard: "expected version + track",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listProviders",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-providers",
      blocking: true,
      response_schema: "ProvidersPage",
    },
    {
      operation_id: "createActionProposal",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/action-proposals",
      blocking: false,
      response_schema: "ActionProposalReceiptV1",
      success_status: 201,
    },
    {
      operation_id: "listRelayModels",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-relay-models",
      blocking: true,
      response_schema: "RelayModelsPage",
    },
  ],
} as const satisfies ScreenViewModel;
