use super::{COMMAND_RECEIPT, OperationSpec, QUERY_BODY};

pub const SUBMISSION_OPERATIONS: &[OperationSpec] = &[
    operation!(
        "createResponseAppeal",
        "submission-api",
        "POST",
        "/v1/response-receipt/appeals",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "COMMAND",
        201,
        COMMAND_RECEIPT
    ),
    operation!(
        "getResponseAppeal",
        "submission-api",
        "GET",
        "/v1/response-receipt/appeals/{appealId}",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "QUERY",
        200,
        QUERY_BODY
    ),
    operation!(
        "requestCommunicationEndpointLink",
        "submission-api",
        "POST",
        "/v1/communication-profile-session/endpoints:link",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "verifyCommunicationEndpointLink",
        "submission-api",
        "POST",
        "/v1/submission-session/communication-endpoint-link:verify",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "COMMAND",
        200,
        COMMAND_RECEIPT
    ),
    operation!(
        "unlinkCommunicationEndpoint",
        "submission-api",
        "POST",
        "/v1/communication-profile-session/endpoints/{endpointId}:unlink",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "COMMAND",
        200,
        COMMAND_RECEIPT
    ),
    operation!(
        "createPrivacyRequest",
        "submission-api",
        "POST",
        "/v1/privacy-requests",
        "bff-service-assertion",
        "none",
        "ANONYMOUS_PROOF",
        "COMMAND",
        201,
        COMMAND_RECEIPT
    ),
    operation!(
        "exchangePrivacyRequestReceiptToken",
        "submission-api",
        "POST",
        "/v1/submission-session/privacy-request-receipt:exchange",
        "bff-service-assertion",
        "none",
        "SCOPED_TOKEN",
        "COMMAND",
        200,
        COMMAND_RECEIPT
    ),
    operation!(
        "getPrivacyRequest",
        "submission-api",
        "GET",
        "/v1/privacy-request-receipt",
        "bff-service-assertion-and-scoped-submission-session",
        "none",
        "SCOPED_TOKEN",
        "QUERY",
        200,
        QUERY_BODY
    ),
];

/// Procurement/identity commands are exposed by the identity-api service and
/// kept separate from the BFF-facing control and submission arrays.
pub const IDENTITY_OPERATIONS: &[OperationSpec] = &[
    operation!(
        "recordSupplierIdentityResolution",
        "identity-api",
        "POST",
        "/v1/internal/supplier-identity/resolutions",
        "actor-assertion-and-capability",
        "cases.evidence.manage",
        "ACTIVE_SESSION",
        "COMMAND",
        201,
        COMMAND_RECEIPT
    ),
    operation!(
        "recordSupplierRelationshipAssertion",
        "identity-api",
        "POST",
        "/v1/internal/supplier-relationships/assertions",
        "actor-assertion-and-capability",
        "cases.evidence.manage",
        "ACTIVE_SESSION",
        "COMMAND",
        201,
        COMMAND_RECEIPT
    ),
    operation!(
        "decideSupplierRelationshipAssertion",
        "identity-api",
        "POST",
        "/v1/internal/supplier-relationships/assertions/{assertionId}:decide",
        "actor-assertion-and-capability",
        "cases.evidence.manage",
        "ACTIVE_SESSION",
        "COMMAND",
        200,
        COMMAND_RECEIPT
    ),
];

pub const PRIVATE_COMMUNICATION_OPERATIONS: &[OperationSpec] = &[
    operation!(
        "acceptSmtpDsn",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/smtp-dsn",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "receiveTelegramWebhook",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/telegram/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "verifyWhatsAppWebhook",
        "communication-gateway",
        "GET",
        "/private/v1/callbacks/whatsapp/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "QUERY",
        200,
        QUERY_BODY
    ),
    operation!(
        "receiveWhatsAppWebhook",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/whatsapp/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "receiveLineWebhook",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/line/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "receiveSolapiSmsCallback",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/solapi/sms/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "receiveSolapiKakaoCallback",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/solapi/kakao/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
    operation!(
        "receiveTwilioVoiceCallback",
        "communication-gateway",
        "POST",
        "/private/v1/callbacks/twilio/voice/{integrationId}",
        "provider-signature",
        "communications.callback",
        "PROVIDER_ASSERTION",
        "COMMAND",
        202,
        COMMAND_RECEIPT
    ),
];

#[cfg(test)]
mod tests {
    use super::SUBMISSION_OPERATIONS;

    #[test]
    fn privacy_receipt_exchange_uses_the_one_time_token_not_a_prior_session() {
        let operation = SUBMISSION_OPERATIONS
            .iter()
            .find(|operation| operation.id == "exchangePrivacyRequestReceiptToken");
        assert_eq!(
            operation.map(|value| value.auth),
            Some("bff-service-assertion")
        );
    }

    #[test]
    fn privacy_status_remains_scoped_to_the_derived_session() {
        let operation = SUBMISSION_OPERATIONS
            .iter()
            .find(|operation| operation.id == "getPrivacyRequest");
        assert_eq!(
            operation.map(|value| value.auth),
            Some("bff-service-assertion-and-scoped-submission-session")
        );
    }
}
