import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RSP-005",
  title: "제출 전 확인",
  route: "/respond/review",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "answers",
      title: "답변 확인",
      component: "KnownUnknownResponse",
      purpose: "질문별 summary와 change link.",
      test_id: "rsp_005__section__answers",
    },
    {
      order: 2,
      id: "attachments",
      title: "첨부 확인",
      component: "KnownUnknownResponse",
      purpose: "scan·분류.",
      test_id: "rsp_005__section__attachments",
    },
    {
      order: 3,
      id: "consent",
      title: "공개 동의 확인",
      component: "KnownUnknownResponse",
      purpose: "정확한 선택.",
      test_id: "rsp_005__section__consent",
    },
    {
      order: 4,
      id: "authority",
      title: "권한 확인",
      component: "KnownUnknownResponse",
      purpose: "조직을 대신해 제출할 권한.",
      test_id: "rsp_005__section__authority",
    },
    {
      order: 5,
      id: "consequence",
      title: "제출 후",
      component: "GuidedFormSection",
      purpose: "immutable submission·추가자료 방식.",
      test_id: "rsp_005__section__consequence",
    },
  ],
  actions: [
    {
      id: "change-answer",
      label: "답변 수정",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "change-files",
      label: "첨부 수정",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "submit",
      label: "답변 제출",
      capability: "none",
      operation_id: "submitResponse",
      guard: "final validation + idempotency",
      interaction_kind: "FORM_SUBMIT",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getResponseSubmissionPreview",
      api: "submission-api",
      method: "GET",
      path: "/v1/response-session/preview",
      blocking: true,
      response_schema: "ResponseSubmissionPreviewResponse",
    },
    {
      operation_id: "submitResponse",
      api: "submission-api",
      method: "POST",
      path: "/v1/response-session:submit",
      blocking: true,
      response_schema: "submitResponseReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
