import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-010",
  title: "Agent 실행",
  route: "/internal/cases/{caseId}/agent-runs",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "runs",
      title: "실행 목록",
      component: "StatusAndRevisionHeader",
      purpose: "purpose·model·status·cost.",
      test_id: "cas_010__section__runs",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "type/status.",
      test_id: "cas_010__section__filters",
    },
    {
      order: 3,
      id: "suggestions",
      title: "채택 상태",
      component: "StatusAndRevisionHeader",
      purpose: "accepted/rejected.",
      test_id: "cas_010__section__suggestions",
    },
    {
      order: 4,
      id: "budget",
      title: "비용",
      component: "StructuredContentSection",
      purpose: "case budget.",
      test_id: "cas_010__section__budget",
    },
  ],
  actions: [
    {
      id: "open-run",
      label: "실행 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "start-run",
      label: "새 조사 실행",
      capability: "cases.investigate",
      operation_id: "startAgentRun",
      guard: "allowed template + budget",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseAgentRuns",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-agent-runs",
      blocking: true,
      response_schema: "CaseAgentRunsPage",
    },
    {
      operation_id: "startAgentRun",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/start-agent-run",
      blocking: false,
      response_schema: "startAgentRunReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
