import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-014",
  title: "공개 미리보기",
  route: "/internal/cases/{caseId}/preview",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "watermark",
      title: "미리보기 상태",
      component: "StatusAndRevisionHeader",
      purpose: "초안·미리보기 무결성 식별값.",
      test_id: "cas_014__section__watermark",
    },
    {
      order: 2,
      id: "render",
      title: "공개 렌더링",
      component: "StructuredContentSection",
      purpose: "public component.",
      test_id: "cas_014__section__render",
    },
    {
      order: 3,
      id: "checks",
      title: "자동 검사",
      component: "EvidenceLedger",
      purpose: "PII·prohibited copy·broken evidence.",
      test_id: "cas_014__section__checks",
    },
    {
      order: 4,
      id: "variants",
      title: "화면 유형·인쇄",
      component: "StructuredContentSection",
      purpose: "compact/wide/print.",
      test_id: "cas_014__section__variants",
    },
    {
      order: 5,
      id: "diff",
      title: "이전 공개와 차이",
      component: "RevisionAndCorrectionPanel",
      purpose: "if correction.",
      test_id: "cas_014__section__diff",
    },
  ],
  actions: [
    {
      id: "refresh-preview",
      label: "미리보기 재생성",
      capability: "publication.preview",
      operation_id: "previewPublication",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-review",
      label: "검토로 이동",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-compact",
      label: "모바일 미리보기",
      capability: "none",
      local_only: true,
      persistence: "browser_session",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "previewPublication",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/preview-publication",
      blocking: true,
      response_schema: "previewPublicationReceipt",
    },
    {
      operation_id: "getPublicationPreview",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-publication-preview",
      blocking: true,
      response_schema: "PublicationPreviewResponse",
    },
  ],
} as const satisfies ScreenViewModel;
