import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-024",
  title: "운영·거버넌스",
  route: "/about/governance",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "structure",
      title: "운영 구조",
      component: "OperationsStatusPanel",
      purpose: "책임과 위원회.",
      test_id: "pub_024__section__structure",
    },
    {
      order: 2,
      id: "independence",
      title: "독립성",
      component: "StructuredContentSection",
      purpose: "commercial/political separation.",
      test_id: "pub_024__section__independence",
    },
    {
      order: 3,
      id: "conflicts",
      title: "이해상충",
      component: "StructuredContentSection",
      purpose: "declare/recuse.",
      test_id: "pub_024__section__conflicts",
    },
    {
      order: 4,
      id: "oversight",
      title: "감독",
      component: "StructuredContentSection",
      purpose: "외부 자문·감사.",
      test_id: "pub_024__section__oversight",
    },
    {
      order: 5,
      id: "appeal",
      title: "이의 제기",
      component: "RevisionAndCorrectionPanel",
      purpose: "정정·appeal.",
      test_id: "pub_024__section__appeal",
    },
    {
      order: 6,
      id: "records",
      title: "회의·정책 기록",
      component: "RevisionTimeline",
      purpose: "공개 가능한 범위.",
      test_id: "pub_024__section__records",
    },
  ],
  actions: [
    {
      id: "view-editorial-policy",
      label: "편집 정책",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "request-correction",
      label: "정정 요청",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getGovernanceContent",
      api: "public-api",
      method: "GET",
      path: "/v1/content/governance",
      blocking: false,
      response_schema: "GovernanceContentResponse",
    },
  ],
} as const satisfies ScreenViewModel;
