import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-006",
  title: "계산 재현",
  route: "/cases/{caseSlug}/reproduce",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "재현 요약",
      component: "StructuredContentSection",
      purpose: "적용 규칙·개정본·계산 결과 요약.",
      test_id: "pub_006__section__summary",
    },
    {
      order: 2,
      id: "inputs",
      title: "입력·무결성 요약값",
      component: "StructuredContentSection",
      purpose: "공개 가능한 normalized input.",
      test_id: "pub_006__section__inputs",
    },
    {
      order: 3,
      id: "cohort",
      title: "비교군",
      component: "ComparisonWorkbench",
      purpose: "포함·제외와 reason.",
      test_id: "pub_006__section__cohort",
    },
    {
      order: 4,
      id: "formula",
      title: "계산",
      component: "ComparisonWorkbench",
      purpose: "수식·rounding·unit.",
      test_id: "pub_006__section__formula",
    },
    {
      order: 5,
      id: "download",
      title: "다운로드",
      component: "StructuredContentSection",
      purpose: "CSV/JSON과 checksum.",
      test_id: "pub_006__section__download",
    },
    {
      order: 6,
      id: "limitations",
      title: "재현 한계",
      component: "StructuredContentSection",
      purpose: "비공개·license·source gap.",
      test_id: "pub_006__section__limitations",
    },
  ],
  actions: [
    {
      id: "download-json",
      label: "JSON 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "download-csv",
      label: "비교군 CSV 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-rule",
      label: "규칙 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getCaseReproducibility",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/reproducibility",
      blocking: true,
      response_schema: "CaseReproducibilityResponse",
    },
    {
      operation_id: "downloadCaseReproducibility",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/{caseSlug}/reproducibility/download",
      blocking: false,
      response_schema: "BinaryDownload",
    },
  ],
} as const satisfies ScreenViewModel;
