import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "REV-002",
  title: "독립 스냅샷 검토",
  route: "/internal/review/{snapshotId}",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "스냅샷 정보",
      component: "StructuredContentSection",
      purpose: "hash·version·author·stale.",
      test_id: "rev_002__section__identity",
    },
    {
      order: 2,
      id: "preview",
      title: "공개 미리보기",
      component: "DecisionReviewPanel",
      purpose: "exact content.",
      test_id: "rev_002__section__preview",
    },
    {
      order: 3,
      id: "matrix",
      title: "주장·증거·답변",
      component: "KnownUnknownResponse",
      purpose: "coverage.",
      test_id: "rev_002__section__matrix",
    },
    {
      order: 4,
      id: "diff",
      title: "변경",
      component: "DecisionReviewPanel",
      purpose: "previous review/publication.",
      test_id: "rev_002__section__diff",
    },
    {
      order: 5,
      id: "risks",
      title: "위험·차단 요인",
      component: "StructuredContentSection",
      purpose: "legal/privacy/source.",
      test_id: "rev_002__section__risks",
    },
    {
      order: 6,
      id: "decision",
      title: "결정",
      component: "DecisionReviewPanel",
      purpose: "approve/changes/reject/hold.",
      test_id: "rev_002__section__decision",
    },
  ],
  actions: [
    {
      id: "approve",
      label: "승인",
      capability: "review.editorial",
      operation_id: "submitReview",
      guard: "independence + latest snapshot + reauth when publish review",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
      fixed_request: {
        decision: "approve",
      },
      request_discriminator: {
        decision: "approve",
      },
    },
    {
      id: "request-changes",
      label: "변경 요청",
      capability: "review.editorial",
      operation_id: "submitReview",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
      fixed_request: {
        decision: "changes_required",
      },
      request_discriminator: {
        decision: "changes_required",
      },
    },
    {
      id: "temporary-restriction",
      label: "임시 공개 제한",
      capability: "review.legal",
      operation_id: "placeTemporaryRestriction",
      guard: "published revision + legal role + reason + expiry + step-up",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "legal-hold",
      label: "법적 보류 설정",
      capability: "review.legal",
      operation_id: "placeLegalHold",
      guard:
        "exact object + scope + authority reference + optional expiry + expected case version + step-up",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getReviewSnapshot",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-review-snapshot",
      blocking: true,
      response_schema: "ReviewSnapshotResponse",
    },
    {
      operation_id: "submitReview",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/submit-review",
      blocking: true,
      response_schema: "submitReviewReceipt",
    },
    {
      operation_id: "placeTemporaryRestriction",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/place-temporary-restriction",
      blocking: false,
      response_schema: "placeTemporaryRestrictionReceipt",
    },
    {
      operation_id: "placeLegalHold",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/place-legal-hold",
      blocking: false,
      response_schema: "placeLegalHoldReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
