import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "REV-003",
  title: "게시 확인·영수증",
  route: "/internal/review/{snapshotId}/publish",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "target",
      title: "게시 대상",
      component: "StructuredContentSection",
      purpose: "case·snapshot·slug·state.",
      test_id: "rev_003__section__target",
    },
    {
      order: 2,
      id: "gates",
      title: "최종 검증",
      component: "KnownUnknownResponse",
      purpose: "review·response·privacy·source.",
      test_id: "rev_003__section__gates",
    },
    {
      order: 3,
      id: "impact",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "public route·notifications·cache.",
      test_id: "rev_003__section__impact",
    },
    {
      order: 4,
      id: "reauth",
      title: "재인증",
      component: "StructuredContentSection",
      purpose: "assurance.",
      test_id: "rev_003__section__reauth",
    },
    {
      order: 5,
      id: "receipt",
      title: "게시 결과",
      component: "StatusAndRevisionHeader",
      purpose: "publication ID·projection status.",
      test_id: "rev_003__section__receipt",
    },
  ],
  actions: [
    {
      id: "publish",
      label: "최신 스냅샷 게시",
      capability: "publication.publish",
      operation_id: "publishCase",
      guard: "recent reauth + exact snapshot + idempotency",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
    {
      id: "cancel",
      label: "검토로 돌아가기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "open-public",
      label: "공개 페이지 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getPublishConfirmation",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-publish-confirmation",
      blocking: true,
      response_schema: "PublishConfirmationResponse",
    },
    {
      operation_id: "publishCase",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/publish-case",
      blocking: true,
      response_schema: "publishCaseReceipt",
    },
    {
      operation_id: "getPublicationReceipt",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-publication-receipt",
      blocking: true,
      response_schema: "PublicationReceiptResponse",
    },
  ],
} as const satisfies ScreenViewModel;
