import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-031",
  title: "개인정보 처리방침",
  route: "/privacy",
  archetype: "POLICY",
  sections: [
    {
      order: 1,
      id: "controller",
      title: "처리자",
      component: "StructuredContentSection",
      purpose: "개인정보 처리 주체와 연락처.",
      test_id: "pub_031__section__controller",
    },
    {
      order: 2,
      id: "categories",
      title: "정보 범주",
      component: "StructuredContentSection",
      purpose: "surface별.",
      test_id: "pub_031__section__categories",
    },
    {
      order: 3,
      id: "purposes",
      title: "목적·법적 근거",
      component: "EvidenceLedger",
      purpose: "명확한 매핑.",
      test_id: "pub_031__section__purposes",
    },
    {
      order: 4,
      id: "retention",
      title: "보존",
      component: "StructuredContentSection",
      purpose: "record type별.",
      test_id: "pub_031__section__retention",
    },
    {
      order: 5,
      id: "processors",
      title: "처리위탁·국외",
      component: "StructuredContentSection",
      purpose: "provider.",
      test_id: "pub_031__section__processors",
    },
    {
      order: 6,
      id: "rights",
      title: "권리",
      component: "StructuredContentSection",
      purpose: "요청 방법.",
      test_id: "pub_031__section__rights",
    },
    {
      order: 7,
      id: "security",
      title: "보호",
      component: "StructuredContentSection",
      purpose: "고수준.",
      test_id: "pub_031__section__security",
    },
    {
      order: 8,
      id: "history",
      title: "변경 이력",
      component: "RevisionTimeline",
      purpose: "effective date.",
      test_id: "pub_031__section__history",
    },
  ],
  actions: [
    {
      id: "privacy-contact",
      label: "개인정보 문의",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-history",
      label: "이전 버전",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getPrivacyPolicy",
      api: "public-api",
      method: "GET",
      path: "/v1/content/privacy",
      blocking: false,
      response_schema: "PrivacyPolicyResponse",
    },
  ],
} as const satisfies ScreenViewModel;
