import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "SRC-006",
  title: "Backfill·Replay",
  route: "/internal/sources/{sourceId}/backfill",
  archetype: "DECISION_REVIEW",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "범위",
      component: "CoverageStatement",
      purpose: "date/IDs/checkpoint.",
      test_id: "src_006__section__scope",
    },
    {
      order: 2,
      id: "estimate",
      title: "예상",
      component: "DataCollection",
      purpose: "records/jobs/cost/duration.",
      test_id: "src_006__section__estimate",
    },
    {
      order: 3,
      id: "dedupe",
      title: "중복 전략",
      component: "StructuredContentSection",
      purpose: "idempotency.",
      test_id: "src_006__section__dedupe",
    },
    {
      order: 4,
      id: "downstream",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "normalization/rules/public.",
      test_id: "src_006__section__downstream",
    },
    {
      order: 5,
      id: "safety",
      title: "safety",
      component: "StructuredContentSection",
      purpose: "rate/budget/kill.",
      test_id: "src_006__section__safety",
    },
    {
      order: 6,
      id: "approval",
      title: "승인",
      component: "DecisionReviewPanel",
      purpose: "reason·reauth.",
      test_id: "src_006__section__approval",
    },
    {
      order: 7,
      id: "progress",
      title: "실행 상태",
      component: "StatusAndRevisionHeader",
      purpose: "pause/cancel.",
      test_id: "src_006__section__progress",
    },
  ],
  actions: [
    {
      id: "estimate",
      label: "영향 계산",
      capability: "sources.operate",
      operation_id: "estimateBackfill",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "start",
      label: "Backfill 시작",
      capability: "sources.operate",
      operation_id: "startBackfill",
      guard: "estimate + approval + reauth",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "pause",
      label: "일시 중지",
      capability: "sources.operate",
      operation_id: "pauseBackfill",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "estimateBackfill",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/estimate-backfill",
      blocking: true,
      response_schema: "estimateBackfillReceipt",
    },
    {
      operation_id: "startBackfill",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/start-backfill",
      blocking: true,
      response_schema: "startBackfillReceipt",
    },
    {
      operation_id: "pauseBackfill",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/pause-backfill",
      blocking: false,
      response_schema: "pauseBackfillReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
