// Generated from the v13 operation catalog; do not edit by hand.
use crate::OperationSpec;

pub const OPERATIONS: &[OperationSpec] = &[
    OperationSpec {
        id: "completeOidcCallback",
        api: "identity-provider",
        method: "GET",
        path: "/auth/callback",
        auth: "oidc-transaction-cookie",
        capability: "none",
        idempotency_required: false,
        assurance_level: "ANONYMOUS_PROOF",
        step_up_required: false,
        operation_kind: "COMMAND",
        success_status: 303,
        media_type: "",
        response_json: "null",
    },
    OperationSpec {
        id: "completeStepUpAuthentication",
        api: "identity-provider",
        method: "GET",
        path: "/auth/step-up/callback",
        auth: "oidc-session-and-step-up-transaction-cookie",
        capability: "none",
        idempotency_required: false,
        assurance_level: "ACTIVE_SESSION",
        step_up_required: false,
        operation_kind: "COMMAND",
        success_status: 303,
        media_type: "",
        response_json: "null",
    },
    OperationSpec {
        id: "getSecurityManagementRedirect",
        api: "identity-provider",
        method: "GET",
        path: "/auth/security-management",
        auth: "oidc-session",
        capability: "none",
        idempotency_required: false,
        assurance_level: "ACTIVE_SESSION",
        step_up_required: false,
        operation_kind: "QUERY",
        success_status: 303,
        media_type: "",
        response_json: "null",
    },
    OperationSpec {
        id: "logoutInternalSession",
        api: "identity-provider",
        method: "POST",
        path: "/auth/logout",
        auth: "oidc-session",
        capability: "none",
        idempotency_required: true,
        assurance_level: "ACTIVE_SESSION",
        step_up_required: false,
        operation_kind: "COMMAND",
        success_status: 204,
        media_type: "",
        response_json: "null",
    },
    OperationSpec {
        id: "startOidcLogin",
        api: "identity-provider",
        method: "GET",
        path: "/auth/login",
        auth: "anonymous",
        capability: "none",
        idempotency_required: false,
        assurance_level: "ANONYMOUS_PROOF",
        step_up_required: false,
        operation_kind: "COMMAND",
        success_status: 303,
        media_type: "",
        response_json: "null",
    },
    OperationSpec {
        id: "startStepUpAuthentication",
        api: "identity-provider",
        method: "POST",
        path: "/auth/step-up/start",
        auth: "oidc-session",
        capability: "none",
        idempotency_required: true,
        assurance_level: "ACTIVE_SESSION",
        step_up_required: false,
        operation_kind: "COMMAND",
        success_status: 303,
        media_type: "",
        response_json: "null",
    },
];
