import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-006",
  title: "공개 Claim 작성",
  route: "/internal/cases/{caseId}/claims",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "claim readiness",
      component: "ClaimWorkbench",
      purpose: "invalid/blocking.",
      test_id: "cas_006__section__summary",
    },
    {
      order: 2,
      id: "claims",
      title: "claim 목록",
      component: "DataCollection",
      purpose: "type·visibility·review.",
      test_id: "cas_006__section__claims",
    },
    {
      order: 3,
      id: "editor",
      title: "작성",
      component: "StructuredContentSection",
      purpose: "text·citations·limitation.",
      test_id: "cas_006__section__editor",
    },
    {
      order: 4,
      id: "lint",
      title: "언어·정책 검사",
      component: "LongFormArticle",
      purpose: "prohibited wording.",
      test_id: "cas_006__section__lint",
    },
    {
      order: 5,
      id: "relationships",
      title: "근거·소명",
      component: "KnownUnknownResponse",
      purpose: "support/contradict.",
      test_id: "cas_006__section__relationships",
    },
  ],
  actions: [
    {
      id: "add-claim",
      label: "Claim 추가",
      capability: "claims.author",
      operation_id: "addClaim",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "save-claim",
      label: "Claim 저장",
      capability: "claims.author",
      operation_id: "updateClaim",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "validate",
      label: "공개 문구 검사",
      capability: "claims.author",
      operation_id: "validateClaims",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseClaims",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-claims",
      blocking: true,
      response_schema: "CaseClaimsPage",
    },
    {
      operation_id: "addClaim",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/add-claim",
      blocking: true,
      response_schema: "addClaimReceipt",
    },
    {
      operation_id: "updateClaim",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/update-claim",
      blocking: true,
      response_schema: "updateClaimReceipt",
    },
    {
      operation_id: "validateClaims",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/validate-claims",
      blocking: true,
      response_schema: "validateClaimsReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
