export const FIELD_LABELS_A_C = {
  abuseProof: "악용 방지 증빙",
  accepted: "수락 건수",
  acceptedAt: "접수 시각",
  access: "접근",
  "access-request": "접근 요청",
  accessReviewFindings: "접근 검토 결과",
  accessType: "접근 유형",
  accessibleRows: "접근 가능한 근거 행 목록",
  accessibleRowsSha256: "근거 행 목록 무결성 지문",
  action: "조치",
  actionDescriptor: "조치 설명",
  actionDetail: "조치 상세",
  actionDetailDigest: "조치 상세 무결성 지문",
  actionDetailKind: "조치 상세 유형",
  actionDigest: "조치 무결성 지문",
  actionId: "조치 식별자",
  actionItems: "조치 항목 목록",
  actionJourney: "조치 처리 이력",
  actionKind: "조치 종류",
  action_id: "조치 식별자",
  actions: "조치 목록",
  activationReceiptDigest: "활성화 확인서 무결성 지문",
  active: "활성 상태",
  activeHandoffGeneration: "활성 인계 차수",
  activeHandoffId: "활성 인계 식별자",
  activeHandoffState: "활성 인계 상태",
  activeHoldIds: "활성 법적 보존 식별자 목록",
  activeScopeAtoms: "활성 법적 보존 범위 항목 목록",
  activeSessions: "활성 세션 목록",
  activeVersion: "활성 버전",
  activity: "활동",
  actor: "행위자",
  actorAssertion: "행위자 인증 정보",
  actorId: "행위자 식별자",
  actorKind: "행위자 종류",
  actorType: "행위자 유형",
  actualCost: "실제 비용",
  addCapabilities: "추가 기능 권한 목록",
  addedFields: "추가 항목 목록",
  affectedCapabilities: "영향받은 기능 권한 목록",
  affectedClaimIds: "영향받은 주장 식별자 목록",
  affectedClaims: "영향받은 주장 목록",
  affectedIds: "영향받은 식별자 목록",
  affectedProviderTurnId: "잠재 영향 제공자 턴 식별자",
  affectedRecordClasses: "영향받은 기록 분류 목록",
  affectedSetDigest: "영향 대상 집합 무결성 지문",
  affectedToolCallId: "잠재 영향 도구 호출 시도 식별자",
  after: "변경 후",
  agencies: "기관 목록",
  agency: "기관",
  agencyId: "기관 식별자",
  agencyName: "기관명",
  agencyType: "기관 유형",
  agentRunId: "에이전트 실행 식별자",
  agentType: "에이전트 유형",
  agentTypeLabel: "에이전트 유형 표기",
  agentTypes: "에이전트 유형 목록",
  aggregate: "업무 단위",
  aggregateId: "업무 단위 식별자",
  aggregateVersion: "업무 단위 버전",
  ai: "인공지능",
  alert: "경보",
  alertThreshold: "경보 기준값",
  alerts: "경보 목록",
  allowedMediaTypes: "허용 매체 유형 목록",
  alternativesConsidered: "검토한 대안 목록",
  amount: "금액",
  amountMax: "최대 금액",
  amountMin: "최소 금액",
  analysisVm: "분석 표시 정보",
  answer: "답변",
  answers: "답변 목록",
  appeal: "이의 신청",
  appealId: "이의 신청 식별자",
  appliedFilters: "적용된 필터",
  appliedRecordClasses: "적용된 기록 분류 목록",
  appliedStates: "적용된 상태 목록",
  approval: "승인",
  approvalBinding: "승인 연결 정보",
  approvalDigest: "승인 무결성 지문",
  approvalSubject: "승인 대상",
  approvalSubjectDigest: "승인 대상 무결성 지문",
  approveConsequence: "승인 결과",
  approveLabel: "승인 표기",
  approverConflict: "승인자 이해충돌",
  archived: "보관 여부",
  artifacts: "산출물",
  asOf: "기준 시각",
  assertionExpiresAt: "행위자 인증 정보 만료 시각",
  assertionOperations: "행위자 인증 처리 내역",
  assignedTo: "배정 대상",
  assignedUserId: "배정 사용자 식별자",
  assigneeUserId: "담당 사용자 식별자",
  assignment: "배정",
  assignmentGeneration: "배정 차수",
  assignmentHistory: "배정 이력",
  assignmentId: "배정 식별자",
  assignmentState: "배정 상태",
  assignmentVersion: "배정 버전",
  assignments: "배정 목록",
  assurance: "인증 수준",
  assuranceLevel: "인증 수준",
  at: "시각",
  attachment: "첨부 파일",
  attachmentCount: "첨부 파일 건수",
  attachmentId: "첨부 파일 식별자",
  attachmentIds: "첨부 파일 식별자 목록",
  attachmentUploads: "첨부 파일 등록 내역",
  attachments: "첨부 파일 목록",
  attachmentsPolicy: "첨부 파일 정책",
  attemptCount: "시도 횟수",
  attemptId: "시도 식별자",
  attempts: "시도 내역",
  attestation: "확인 진술",
  audit: "감사",
  auditEventId: "감사 기록 식별자",
  auditExportId: "감사 내보내기 식별자",
  auditSummary: "감사 요약",
  authorIds: "작성자 식별자 목록",
  authority: "제출 권한",
  authorityReference: "법적 보존 근거",
  authorityReferenceDigest: "법적 보존 근거 무결성 지문",
  authorization: "인가",
  authorizationCloseCount: "인가 종료 횟수",
  authorizationCookieDomainMode: "인가 쿠키 도메인 방식",
  authorizationCookiePath: "인가 쿠키 경로",
  authorizationCookieSameSite: "인가 쿠키 사이트 일치 정책",
  authorizationEventId: "인가 기록 식별자",
  authorizationPurpose: "인가 목적",
  authorizationSnapshotDigest: "인가 시점 정보 무결성 지문",
  authorizationUrl: "인가 주소",
  automatedGates: "자동 검증 항목 목록",
  autoUpgrade: "자동 업그레이드",
  autoUpgradeConflict: "자동 업그레이드 충돌",
  awaitingResponse: "응답 대기",
  backfillRunId: "이력 보완 실행 식별자",
  baseVersion: "기준 버전",
  before: "변경 전",
  "before-after": "변경 전후",
  benchmarkType: "비교 기준 유형",
  benchmarkValue: "비교 기준값",
  binary: "이진 데이터",
  binding: "연결 정보",
  bindingDigest: "연결 정보 무결성 지문",
  blockedReasons: "차단 사유 목록",
  blockers: "차단 요인 목록",
  blockingConditions: "차단 조건 목록",
  blockingSlots: "미충족 검토 역할 목록",
  board: "가설 현황",
  body: "본문",
  bodyConsent: "본문 공개 동의",
  bodyPlainText: "평문 본문",
  budget: "예산",
  budgetDisposition: "예산 처리 상태",
  budgetReservationDigest: "예산 예약 무결성 지문",
  budgetReservationId: "예산 예약 식별자",
  budgetResolutionSetSha256: "예산 결정 집합 SHA-256 해시값",
  bulk: "일괄 처리",
  bundleStatus: "자료 묶음 상태",
  bundleSummary: "자료 묶음 요약",
  businessStatus: "사업자 상태",
  byteLength: "바이트 길이",
  calculation: "계산",
  calculationSummary: "계산 요약",
  calendarDigest: "달력 무결성 지문",
  calendarVersionId: "달력 버전 식별자",
  cancellationGeneration: "취소 차수",
  canonicalUrl: "표준 주소",
  capabilities: "기능 권한 목록",
  capability: "기능 권한",
  caption: "표 설명",
  case: "사건",
  caseCount: "사건 수",
  caseCounts: "사건 수 집계",
  caseCountsByState: "상태별 사건 수",
  caseId: "사건 식별자",
  caseLabel: "사건 표기",
  casePublicTitle: "사건 공개 제목",
  caseSlug: "사건 경로명",
  caseTitle: "사건 제목",
  caseVersion: "사건 버전",
  case_id: "사건 식별자",
  cases: "사건 목록",
  catalog: "분류 목록",
  categories: "범주 목록",
  category: "범주",
  challengeId: "확인 요청 식별자",
  challengeKind: "확인 방식",
  changedFields: "변경 항목 목록",
  changes: "변경 사항 목록",
  changesRequiredConsequence: "변경 요구 결과",
  channel: "채널",
  channels: "채널 목록",
  checkedAt: "확인 시각",
  checkpoint: "수집 기준점",
  checks: "점검 항목 목록",
  citation: "인용 근거",
  citations: "인용 근거 목록",
  claimId: "주장 식별자",
  claimIds: "주장 식별자 목록",
  claimType: "주장 유형",
  claims: "주장 목록",
  classification: "분류",
  classificationState: "분류 상태",
  closed: "종결 여부",
  closedAt: "종결 시각",
  code: "오류 코드",
  codeDigest: "코드 무결성 지문",
  cohort: "대상 집단",
  command: "명령",
  commandAttempts: "명령 시도 내역",
  commandBinding: "명령 연결 정보",
  commanderUserId: "명령자 식별자",
  commitment: "접근성 약속",
  comparison: "비교",
  compatibility: "호환성",
  complete: "완료 여부",
  completedAt: "완료 시각",
  completeness: "완전성",
  completionReceiptId: "완료 확인서 식별자",
  completionSummary: "완료 요약",
  configuration: "구성",
  connectionTestId: "연결 테스트 식별자",
  confirmedFacts: "확인된 사실 목록",
  conflictSnapshotDigest: "충돌 스냅샷 무결성 지문",
  conflictStatus: "충돌 상태",
  conflictType: "충돌 유형",
  conflicts: "충돌 목록",
  conformance: "준수 상태",
  connectorType: "연계 유형",
  consent: "동의",
  consentAndSuppressionStatus: "동의 및 제한 상태",
  consentEvidenceReceiptIds: "동의 근거 확인서 식별자 목록",
  consentSnapshotDigest: "동의 스냅샷 무결성 지문",
  consequence: "결과",
  contact: "연락처",
  contactEmail: "연락 이메일 주소",
  containmentActions: "영향 제한 조치",
  content: "내용",
  contentBase64: "Base64 인코딩 내용",
  contentDigest: "내용 무결성 지문",
  contentHash: "내용 해시값",
  contentSha256: "내용 SHA-256 해시값",
  contractId: "계약 식별자",
  contractLineItems: "계약 세부 항목",
  contractMethod: "계약 방식",
  contractName: "계약명",
  contractNumber: "계약 번호",
  contractStatus: "계약 상태",
  contracts: "계약 목록",
  contradictingEvidenceIds: "상충 근거 식별자 목록",
  contrary: "반대 근거",
  contraryEvidenceSetDigest: "반대 근거 집합 무결성 지문",
  controlState: "제어 상태",
  controller: "개인정보처리자",
  cookieName: "쿠키명",
  corrected: "정정 여부",
  correction: "정정",
  correctionId: "정정 식별자",
  correctionStatus: "정정 상태",
  corrections: "정정 목록",
  cost: "비용",
  costEstimate: "예상 비용",
  costLedgerState: "비용 장부 상태",
  costMicrosKrw: "비용(마이크로 원화)",
  count: "건수",
  countedDecisionReceiptDigests: "반영된 결정 확인서 무결성 지문 목록",
  counterEvidence: "반증 근거",
  counts: "건수 집계",
  coverage: "적용 범위",
  coverageDigest: "적용 범위 무결성 지문",
  createdAt: "생성 시각",
  createdBy: "생성자",
  creator: "생성자",
  criteria: "기준",
  critical: "중대 여부",
  criticalUnknowns: "중대한 미확인 사항",
  csrfRotatedAt: "요청 위조 방지 토큰 교체 시각",
  csrfStorage: "요청 위조 방지 토큰 저장소",
  csrfToken: "요청 위조 방지 토큰",
  csrfTokenReturned: "요청 위조 방지 토큰 반환 여부",
  currency: "통화",
  current: "현재 값",
  currentAmount: "현재 금액",
  currentCaseVersion: "현재 사건 버전",
  currentModel: "현재 모델",
  currentOwnerBindingDigest: "현재 담당자 연결 무결성 지문",
  currentProviders: "현재 공급자 목록",
  currentState: "현재 상태",
  cursor: "조회 위치",
} as const satisfies Readonly<Record<string, string>>;
