export const FIELD_LABELS_D_G = {
  dailyLimit: "일일 한도",
  dailySeries: "일별 추이",
  dailyUsed: "일일 사용량",
  data: "데이터",
  dataError: "데이터 오류",
  dataQuality: "데이터 품질",
  dataSha256: "데이터 무결성 지문",
  dataset: "데이터 집합",
  datasetDigest: "데이터 집합 무결성 지문",
  datasetId: "데이터 집합 식별자",
  datasetSnapshotId: "데이터 집합 스냅샷 식별자",
  datasets: "데이터 집합 목록",
  dateFrom: "시작일",
  dateRange: "날짜 범위",
  dateTo: "종료일",
  deadLetterTotal: "격리 메시지 총건수",
  deadline: "마감 시각",
  decidedAt: "결정 시각",
  decision: "결정",
  decisionDigest: "결정 무결성 지문",
  decisionHelp: "결정 안내",
  decisionHistory: "결정 이력",
  decisionId: "결정 식별자",
  decisionKind: "결정 유형",
  decisionReason: "결정 사유",
  decisionReceipt: "결정 확인서",
  decisionReceipts: "결정 확인서 목록",
  decisionSequence: "결정 순번",
  decisionVersion: "결정 버전",
  decisions: "결정 목록",
  declaration: "선언",
  declarationDigest: "선언 무결성 지문",
  declarationId: "선언 식별자",
  declarationSequence: "선언 순번",
  dedupe: "중복 제거",
  dedupeStrategy: "중복 제거 기준",
  defaultDecision: "기본 결정",
  defaultDueAt: "기본 기한 시각",
  defaultPublicationScope: "기본 공개 범위",
  definition: "정의",
  delivery: "송달",
  deliveryEvidenceReceiptIds: "송달 근거 확인서 식별자 목록",
  deliveryId: "송달 식별자",
  deliveryKeySha256: "송달 키 SHA-256 지문",
  description: "설명",
  destination: "전달 대상",
  destinationIdentitySha256: "전달 대상 식별 정보 SHA-256 지문",
  details: "세부 정보",
  detectedAt: "감지 시각",
  diff: "변경 내역",
  diffFromCurrent: "현행 대비 변경 내역",
  diffFromPrevious: "직전 대비 변경 내역",
  digest: "무결성 지문",
  disclosure: "공개 내역",
  displayName: "표시 이름",
  domainMode: "쿠키 도메인 범위 방식",
  donors: "기부자 목록",
  download: "다운로드",
  downloadUrl: "다운로드 주소",
  downstream: "후속 처리",
  downstreamEffects: "후속 영향",
  draft: "초안",
  draftToken: "초안 토큰",
  due: "기한",
  dueAt: "기한 시각",
  dueBefore: "기한 이전",
  duplicate: "중복 항목",
  duplicateRelationship: "중복 관계",
  duplicateSignalId: "중복 신호 식별자",
  duplicates: "중복 항목 목록",
  durableSuccessDefinition: "영속 성공 기준",
  editor: "편집자",
  editorialReview: "편집 검토",
  editorialStatus: "편집 상태",
  effect: "효과",
  effectClass: "효과 분류",
  effectDigest: "효과 무결성 지문",
  effectIdempotencyKeySha256: "효과 멱등성 키 SHA-256 지문",
  effectiveAt: "효력 발생 시각",
  effectiveCapabilities: "유효 기능 권한 목록",
  effects: "효과 목록",
  eligibleParties: "적격 당사자 목록",
  email: "이메일 주소",
  emailMasked: "마스킹된 이메일 주소",
  emailOtp: "이메일 일회용 인증번호",
  emittedEventIds: "발행 이벤트 식별자 목록",
  enabled: "사용 여부",
  endpoint: "연락 수단",
  endpointId: "연락 수단 식별자",
  endpointVersion: "연락 수단 버전",
  entityType: "개체 유형",
  envelope: "예산 한도 체계",
  environment: "운영 환경",
  error: "오류",
  errors: "오류 목록",
  escalationState: "상향 검토 상태",
  estimate: "추정치",
  estimatedCostKrw: "예상 비용(원)",
  estimatedDurationSeconds: "예상 소요 시간(초)",
  estimatedJobs: "예상 작업 수",
  estimatedRecords: "예상 기록 수",
  evaluatedAt: "평가 시각",
  evaluation: "평가",
  evaluationDigest: "평가 무결성 지문",
  evaluationProfile: "평가 프로필",
  evaluationRunId: "평가 실행 식별자",
  event: "이벤트",
  eventId: "이벤트 식별자",
  eventType: "이벤트 유형",
  events: "이벤트 목록",
  evidence: "근거",
  evidenceDescription: "근거 설명",
  evidenceDigest: "근거 무결성 지문",
  evidenceId: "근거 식별자",
  evidenceIds: "근거 식별자 목록",
  evidenceScopeIds: "근거 범위 식별자 목록",
  evidenceSegmentBindings: "근거 구간 연결 목록",
  evidenceSegmentIds: "근거 구간 식별자 목록",
  evidenceSegmentSetDigest: "근거 구간 집합 무결성 지문",
  evidenceSetDigest: "근거 집합 무결성 지문",
  evidenceType: "근거 유형",
  evidenceVersion: "근거 버전",
  exactContent: "원문 내용",
  excerpt: "발췌문",
  excerptHash: "발췌문 해시",
  excluded: "제외 여부",
  excludedCohort: "제외 대상군",
  excludedCount: "제외 건수",
  exclusions: "제외 항목 목록",
  executionAuthorization: "실행 인가",
  executionDigest: "실행 무결성 지문",
  executionId: "실행 식별자",
  executorId: "실행자 식별자",
  expectedApprovalDigest: "기준 승인 무결성 지문",
  expectedAssignmentVersion: "기준 배정 버전",
  expectedBindingDigest: "기준 연결 무결성 지문",
  expectedCaseVersion: "기준 사건 버전",
  expectedChainHead: "기준 체인 최종값",
  expectedContentDigest: "기준 내용 무결성 지문",
  expectedDuplicateSignalVersion: "기준 중복 신호 버전",
  expectedEffectDigest: "기준 효과 무결성 지문",
  expectedHandoffVersion: "기준 인계 버전",
  expectedOutcome: "예상 결과",
  expectedProposalVersion: "기준 제안 버전",
  expectedResponseDays: "예상 응답 일수",
  expectedRunVersion: "기준 실행 버전",
  expectedState: "기준 상태",
  expectedVersion: "기준 버전",
  expenses: "지출 목록",
  expired: "만료 건수",
  expiresAt: "만료 시각",
  expiresInSeconds: "남은 유효 시간(초)",
  expirySummary: "만료 요약",
  explained: "소명 완료 여부",
  explanation: "설명",
  export: "내보내기",
  exports: "내보내기 목록",
  exposure: "노출도",
  extension: "연장",
  extensionRequestId: "연장 요청 식별자",
  externalId: "외부 식별자",
  externalSideEffect: "외부 영향 발생 여부",
  factSha256: "사실 무결성 지문",
  failedLastHour: "최근 1시간 실패 건수",
  failureCode: "실패 코드",
  fallback: "대체 처리",
  fallbackAction: "대체 조치",
  "false-positive": "오탐",
  falsePositiveCount: "오탐 건수",
  feed: "자료 피드",
  fencingToken: "펜싱 토큰",
  fieldMappings: "필드 매핑 목록",
  filename: "파일 이름",
  files: "파일 목록",
  filters: "필터",
  finalParent: "최종 상위 항목",
  finishedAt: "완료 시각",
  forecast: "예측",
  forecastAssumption: "예측 전제",
  forecastConfidence: "예측 신뢰도",
  form: "양식",
  format: "형식",
  formattedValue: "표시 값",
  formula: "산식",
  frequency: "주기",
  freshness: "최신성",
  from: "시작",
  fromEventId: "시작 이벤트 식별자",
  fromLabel: "출발",
  fromState: "이전 상태",
  gaps: "누락 구간",
  gate: "검증 관문",
  gateResults: "검증 관문 결과",
  gates: "검증 관문 목록",
  generation: "생성 차수",
  "getting-started": "시작 안내",
  governance: "거버넌스",
  governanceDigest: "거버넌스 무결성 지문",
  grants: "권한 부여 목록",
  graphSha256: "근거 그래프 무결성 지문",
  groupBy: "집계 기준",
  guidance: "안내",
} as const satisfies Readonly<Record<string, string>>;
