export const FIELD_LABELS_H_L = {
  handoff: "인계",
  handoffId: "인계 식별자",
  handoffKind: "인계 유형",
  handoffState: "인계 상태",
  handoffVersion: "인계 버전",
  hardExpiryAt: "절대 만료 시각",
  hardLimit: "절대 한도",
  hasCorrection: "정정 여부",
  hasResponse: "소명 여부",
  headReceiptDigest: "최신 확인서 무결성 지문",
  headReceiptId: "최신 확인서 식별자",
  header: "사건 개요",
  headers: "표 머리글 목록",
  heading: "제목",
  health: "운영 상태",
  history: "이력",
  holdCoverageDigest: "법적 보존 범위 무결성 지문",
  holdId: "법적 보존 식별자",
  href: "연결 주소",
  httpOnly: "스크립트 접근 차단 여부",
  hypothesis: "가설",
  hypothesisId: "가설 식별자",
  id: "식별자",
  idempotencyKeySha256: "멱등성 키 SHA-256 지문",
  idempotencyReplay: "멱등 응답 재사용 여부",
  identifiers: "식별자 목록",
  identity: "식별 정보",
  "identity-note": "식별 한계",
  identityStatus: "식별 상태",
  identityVerificationReceiptId: "신원 확인서 식별자",
  identityWarnings: "식별 주의사항",
  impact: "영향",
  impactSummary: "영향 요약",
  implementationDigest: "구현 무결성 지문",
  incident: "사고",
  incidentId: "사고 식별자",
  incidents: "사고 목록",
  includeReason: "포함 사유",
  included: "포함 여부",
  includedCohort: "포함 대상군",
  includedCount: "포함 건수",
  income: "수입",
  independence: "독립성",
  input: "입력",
  inputDigest: "입력 무결성 지문",
  inputs: "입력 목록",
  insufficientEvidence: "근거 부족 여부",
  integrity: "무결성",
  intentId: "의도 식별자",
  intro: "절차·긴급 안내",
  inventorySnapshotDigest: "자료 목록 스냅샷 무결성 지문",
  investigating: "조사 중 건수",
  investigation: "조사",
  investigationState: "조사 상태",
  investigationSummary: "조사 요약",
  isDefault: "기본값 여부",
  isEstimate: "추정치 여부",
  isLatest: "최신 여부",
  issue: "문제",
  items: "항목 목록",
  jobHealth: "작업 처리 상태",
  jobId: "작업 식별자",
  jobIds: "작업 식별자 목록",
  jobStatus: "작업 상태",
  jobType: "작업 유형",
  jobs: "작업 목록",
  journeyInstanceId: "여정 실행 식별자",
  journeyInstanceVersion: "여정 실행 버전",
  jurisdiction: "관할권",
  killSwitchId: "비상 중지 식별자",
  kind: "유형",
  "known-unknown": "확인·미확인·소명",
  knownGaps: "알려진 수집 공백",
  knownIssues: "알려진 문제",
  label: "표시 문구",
  language: "언어",
  lastChangeReason: "마지막 변경 사유",
  lastChangedBy: "마지막 변경자",
  lastEditor: "마지막 편집자",
  latency: "지연 시간",
  latestPreview: "최신 미리보기",
  latestProviderEvidenceDigest: "최신 제공자 근거 무결성 지문",
  latestReceipt: "최신 확인서",
  leaseExpiryIncidents: "작업 점유권 만료 건수",
  ledgerEntryCount: "장부 항목 수",
  legalHoldBlocked: "법적 보존에 따른 차단 여부",
  legalReview: "법무 검토",
  legalReviewRequired: "법무 검토 필요 여부",
  liability: "책임",
  license: "이용 허가",
  limit: "한도",
  limitMicrosKrw: "한도(마이크로 원화)",
  limitations: "한계",
  limits: "한도 목록",
  lineItems: "세부 항목 목록",
  linkedClaims: "연결된 주장 목록",
  links: "관련 링크",
  lint: "정적 검사",
  list: "목록",
  locale: "언어·지역 설정",
  locationReceipts: "위치별 처리 확인서 목록",
  locator: "정확한 위치",
} as const satisfies Readonly<Record<string, string>>;
