export const FIELD_LABELS_M_R = {
  manage: "관리",
  managementToken: "관리 토큰",
  mapping: "항목 대응표",
  mappingDigest: "항목 대응표 무결성 지문",
  mappingVersion: "항목 대응표 버전",
  maskedDestination: "가림 처리된 수신처",
  materialConsequence: "중대 영향",
  materialUnknowns: "중대한 미확인 사항",
  materiality: "중대성",
  matrix: "근거 관계표",
  maxAssertionIssues: "행위자 인증 정보 발급 한도",
  maxAttempts: "최대 시도 횟수",
  maxBytes: "최대 파일 용량",
  maxCost: "최대 비용",
  maxCount: "최대 건수",
  maximumCost: "최대 비용",
  mediaType: "미디어 유형",
  message: "안내 내용",
  metadata: "부가 정보",
  method: "방법",
  methodologyVersion: "방법론 버전",
  methods: "방법 목록",
  metric: "지표",
  metrics: "지표 목록",
  mission: "운영 목적",
  mode: "처리 방식",
  model: "모델 정보",
  modelId: "모델 식별자",
  monthlyLimit: "월 한도액",
  monthlyUsed: "월 사용액",
  "my-work": "내 작업",
  myTasks: "내 작업 목록",
  name: "명칭",
  narrativeAlternative: "서술형 대체 설명",
  neverPublished: "미공개 건수",
  new: "신규 여부",
  newDueAt: "변경 후 기한",
  next: "다음 절차",
  nextAction: "다음 조치",
  nextActions: "다음 조치 목록",
  nextControlState: "다음 통제 상태",
  nextCursor: "다음 조회 위치",
  nextOwnerBindingDigest: "다음 담당자 연결 무결성 지문",
  nextRequiredActions: "다음 필수 조치",
  nextStatus: "다음 상태",
  nextUpdateAt: "다음 갱신 시각",
  nextUpdateExpectation: "다음 갱신 안내",
  next_action: "다음 조치",
  "non-goals": "하지 않는 일",
  none: "없음",
  nonwaivable: "포기 불가 여부",
  normalizationVersion: "정규화 버전",
  normalizationWarnings: "정규화 경고 목록",
  notBefore: "최초 실행 가능 시각",
  notes: "비고",
  notificationId: "알림 식별자",
  notificationType: "알림 유형",
  notifications: "알림 목록",
  objectEtag: "객체 변경 태그",
  objectId: "객체 식별자",
  objectLabel: "객체 명칭",
  objectScopeDigest: "객체 범위 무결성 지문",
  objectType: "객체 유형",
  objective: "목표",
  observedAt: "관측 시각",
  occurredAt: "발생 시각",
  offboarding: "사용 종료 절차",
  officeHours: "문의 가능 시간",
  officialUrl: "공식 주소",
  officiallyConfirmed: "공식 확인 건수",
  oneTimeToken: "일회용 토큰",
  opaqueSessionToken: "불투명 세션 토큰",
  operationId: "연산 식별자",
  optOutReceiptId: "수신 거부 확인서 식별자",
  order: "순서",
  ordinal: "순번",
  organizationId: "조직 식별자",
  organization_id: "조직 식별자",
  origin: "발생 출처",
  originDigest: "발생 출처 무결성 지문",
  original: "원본",
  outboxEventId: "발신함 이벤트 식별자",
  outcome: "처리 결과",
  output: "산출물",
  overdueOnly: "기한 초과 항목 한정",
  overdueTasks: "기한 초과 작업",
  oversight: "감독",
  overview: "개요",
  owner: "담당자",
  ownerUserId: "담당자 식별자",
  ownership: "담당 체계",
  owningTeam: "담당 팀",
  pageDigest: "페이지 무결성 지문",
  pagination: "페이지 정보",
  parserVersion: "구문 분석기 버전",
  partial: "부분 답변",
  partialOrAmbiguousMeaning: "부분 처리 또는 모호한 경우의 의미",
  party: "당사자",
  partyName: "당사자명",
  partyResponses: "당사자 소명",
  partyType: "당사자 유형",
  path: "경로",
  paused: "일시 정지 여부",
  payload: "전송 내용",
  payloadSha256: "전송 내용 무결성 지문",
  pending: "대기 건수",
  pendingSession: "대기 중인 세션",
  pendingVerificationCount: "검증 대기 건수",
  periodFrom: "기간 시작",
  periodLabel: "기간 표기",
  periodTo: "기간 종료",
  personalDataState: "개인정보 처리 상태",
  pipeline: "처리 흐름",
  pipelines: "처리 흐름 목록",
  plainLanguageChange: "쉬운 말로 쓴 변경 내용",
  planDigest: "계획 무결성 지문",
  policyBlockers: "정책 차단 요인",
  policyDigest: "정책 무결성 지문",
  policySnapshotDigest: "정책 스냅샷 무결성 지문",
  policyStatus: "정책 상태",
  policySummary: "정책 요약",
  policyVersion: "정책 버전",
  preferences: "선호 설정",
  preview: "미리보기",
  previewDigest: "미리보기 무결성 지문",
  previewHash: "미리보기 무결성 지문",
  previewId: "미리보기 식별자",
  pricingVersion: "단가 정책 버전",
  principle: "원칙",
  principles: "원칙 목록",
  priorControlState: "이전 통제 상태",
  priorCoverageDigest: "이전 적용 범위 무결성 지문",
  priorDecisionId: "이전 결정 식별자",
  priorDeclarationDigest: "이전 선언 무결성 지문",
  priorDueAt: "이전 기한",
  priorReceiptDigest: "이전 확인서 무결성 지문",
  priorReceiptId: "이전 확인서 식별자",
  priorReceiptSha256: "이전 확인서 무결성 지문",
  priorState: "이전 진행 상태",
  priorStatus: "이전 상태",
  priority: "우선순위",
  privacy: "개인정보 보호",
  privacyConsent: "개인정보 처리 동의",
  privacyRequestId: "개인정보 요청 식별자",
  process: "절차",
  processingRegion: "처리 지역",
  processors: "처리 위탁·국외 이전",
  procurement: "조달",
  procurementMethod: "조달 방식",
  profileVersion: "프로필 버전",
  progress: "진행률",
  prohibited: "금지 사항",
  promotedAt: "승격 시각",
  promotionId: "승격 식별자",
  promptInjectionState: "프롬프트 주입 점검 상태",
  promptVersion: "프롬프트 버전",
  proofKind: "증명 유형",
  proofSha256: "증명 무결성 지문",
  proposal: "제안",
  proposalId: "제안 식별자",
  proposalState: "제안 상태",
  proposalStates: "제안 상태 목록",
  proposalSummary: "제안 현황",
  proposalVersion: "제안 버전",
  proposal_id: "제안 식별자",
  proposer: "제안자",
  provenance: "출처 이력",
  provenanceGraph: "출처 관계 그래프",
  provider: "제공자",
  providerAcknowledgementSha256: "제공자 접수 확인 무결성 지문",
  providerEvidenceDigest: "제공자 근거 무결성 지문",
  providerId: "제공자 식별자",
  providerIdempotencyKeySha256: "제공자 멱등성 키 무결성 지문",
  providerPolicy: "제공자 정책",
  providerType: "제공자 유형",
  providers: "제공자 목록",
  "public-copy": "공개 발췌문",
  "public-use": "공개 범위",
  "public-view": "공개 이력 미리보기",
  publicCases: "공개 사건 건수",
  publicExcerpt: "공개 발췌문",
  publicMessage: "공개 안내",
  publicPayload: "공개 내용",
  publicState: "공개 상태",
  publicUrl: "공개 주소",
  publicUrls: "공개 주소 목록",
  publication: "공개 상태별 건수",
  "publication-gate": "공개 조건",
  publicationConsent: "공개 동의",
  publicationExcerptEvidenceIds: "공개 발췌 근거 식별자 목록",
  publicationId: "공개 식별자",
  publicationRevision: "공개 개정본",
  publicationScope: "공개 범위",
  publicationState: "공개 상태",
  publishedAnomaly: "이상 징후 공개 건수",
  publishedAt: "공개 시각",
  publishedExplained: "설명 공개 건수",
  publishedFrom: "공개 시작 시각",
  publishedTo: "공개 종료 시각",
  purpose: "목적",
  purposes: "목적 목록",
  q: "검색어",
  quality: "품질",
  qualityWarnings: "품질 경고",
  quantity: "수량",
  query: "조회 조건",
  querySnapshotId: "조회 스냅샷 식별자",
  question: "질문",
  questionCount: "질문 수",
  questionId: "질문 식별자",
  questionLabel: "질문 문구",
  questions: "질문 목록",
  queue: "대기열",
  queueName: "대기열 이름",
  queues: "대기열 목록",
  quorum: "의결 정족수",
  quorumPlanDigest: "의결 정족수 계획 무결성 지문",
  quotas: "할당량",
  ranges: "텍스트 범위 목록",
  ratio: "비율",
  rationale: "판단 근거",
  rationaleDigest: "판단 근거 무결성 지문",
  readiness: "준비도",
  ready: "준비 여부",
  readyToPublish: "공개 준비 건수",
  reason: "사유",
  reasonCode: "사유 코드",
  reasonSha256: "사유 무결성 지문",
  reauth: "재인증",
  receipt: "확인서",
  receiptDigest: "확인서 무결성 지문",
  receiptId: "확인서 식별자",
  receiptSession: "확인 세션",
  receiptSha256: "확인서 무결성 지문",
  receiptToken: "확인서 토큰",
  receipts: "확인서 목록",
  receiverFunction: "수신 담당 기능",
  recent: "최근 항목",
  recentActions: "최근 조치 목록",
  recentCases: "최근 사건 목록",
  recentContracts: "최근 계약 목록",
  recipientEmail: "수신자 이메일 주소",
  recipients: "수신자 목록",
  recommendedActions: "권고 조치 목록",
  reconciliationEvidenceDigest: "정합화 근거 무결성 지문",
  reconciliationEvidenceId: "정합화 근거 식별자",
  reconciliationEvidenceSha256: "정합화 근거 무결성 지문",
  reconciliationRequired: "정합화 필요 여부",
  recordCount: "기록 수",
  recordCounts: "기록 수 집계",
  recordKind: "기록 유형",
  recordedAt: "기록 시각",
  records: "기록 목록",
  recordsChanged: "변경 기록 수",
  recordsSeen: "확인 기록 수",
  recovery: "복구",
  recoveryPlan: "복구 계획",
  recuseConsequence: "회피 시 결과",
  redactionAcknowledged: "민감정보 가림 원칙 확인 여부",
  redactionType: "가림 처리 유형",
  redactions: "가림 처리 목록",
  redirectUrl: "이동 주소",
  reference: "참조 정보",
  references: "참조 목록",
  referredConfidential: "비공개 이관 건수",
  registry: "등록부",
  regressions: "회귀 항목 목록",
  rejectConsequence: "거부 결과",
  rejectLabel: "거부 표기",
  rejected: "반려 건수",
  rel: "링크 관계",
  related: "관련 항목",
  relatedCases: "관련 사건 목록",
  relation: "관계",
  relationLabel: "관계",
  relationState: "관계 상태",
  relationships: "관계 목록",
  releaseSequence: "해제 순번",
  releasedScopeAtoms: "해제된 범위 단위 목록",
  remainingAssertionIssues: "남은 행위자 인증 정보 발급 횟수",
  remainingAttempts: "남은 시도 횟수",
  remainingMicrosKrw: "잔여액(마이크로 원화)",
  removeCapabilities: "제거할 기능 권한 목록",
  removedFields: "제거된 항목 목록",
  render: "공개 화면 생성",
  renderedRoutes: "생성 경로 목록",
  renderingDigest: "생성본 무결성 지문",
  replacement: "대체 항목",
  replacementContent: "대체 내용",
  replacementText: "대체 문구",
  reports: "보고서 목록",
  request: "요청",
  requestCount: "요청 수",
  requestId: "요청 식별자",
  requestReceiptDigest: "요청 확인서 무결성 지문",
  requestReceiptId: "요청 확인서 식별자",
  requestSha256: "요청 무결성 지문",
  requestType: "요청 유형",
  request_id: "요청 식별자",
  requestedChanges: "요청 변경 내역",
  requestedDueAt: "요청 기한",
  requestedEvidenceKinds: "요청 근거 유형 목록",
  requestedOutcome: "요청 결과",
  requestedPublicationScope: "요청 공개 범위",
  requestedRoleCodes: "요청 역할 코드 목록",
  requestedUntil: "요청 만료 시각",
  requesterType: "요청자 유형",
  requestingOrganization: "요청 기관",
  requests: "요청 목록",
  requiredAssurance: "필수 인증 수준",
  requiredCapability: "필수 기능 권한",
  requiredFields: "필수 입력 항목",
  requiredQuorum: "필수 정족수",
  requiredReauth: "재인증 필요 여부",
  requiredSlots: "필수 검토 구획 목록",
  requiresEmailProof: "이메일 소유 증명 필요 여부",
  researchArtifactId: "조사 자료 식별자",
  researchArtifactSha256: "조사 자료 무결성 지문",
  reservationSummary: "예약 요약",
  reserved: "예약액",
  reservedMicrosKrw: "예약액(마이크로 원화)",
  reset: "초기화",
  resolution: "처리 결과",
  resolutionCode: "처리 결과 코드",
  resourceId: "자원 식별자",
  resourceVersion: "자원 버전",
  resources: "자원 목록",
  response: "응답",
  responseId: "응답 식별자",
  responseIds: "응답 식별자 목록",
  responseRequestId: "응답 요청 식별자",
  responseRequestVersion: "응답 요청 버전",
  responseStatus: "응답 상태",
  responses: "응답 목록",
  restriction: "제한 사항",
  result: "결과",
  resultDigest: "결과 무결성 지문",
  resultingCoverageDigest: "변경 후 적용 범위 무결성 지문",
  resultingDueAt: "변경 후 기한",
  resultingHandoffState: "변경 후 인계 상태",
  resultingJourneyState: "변경 후 업무 여정 상태",
  results: "결과 목록",
  retention: "보존",
  retentionDays: "보존 일수",
  retentionNotice: "보존 안내",
  retentionRequestId: "보존 요청 식별자",
  retentionMode: "보존 방식",
  retracted: "철회 건수",
  retrievedAt: "수집 시각",
  returnTo: "복귀 경로",
  reversible: "되돌리기 가능 여부",
  review: "검토",
  reviewQueue: "검토 대기열",
  reviewSnapshotId: "검토 스냅샷 식별자",
  reviewStatus: "검토 상태",
  reviewType: "검토 유형",
  reviewer: "검토자",
  reviewerId: "검토자 식별자",
  reviewerUserId: "검토 담당 사용자 식별자",
  reviewerUserIds: "검토 담당 사용자 식별자 목록",
  reviews: "검토 목록",
  revision: "개정본",
  "revision-banner": "개정 안내",
  revoked: "취소 여부",
  revokedAt: "취소 시각",
  rights: "권리",
  rightsDecisionDigest: "권리 판단 무결성 지문",
  rightsDecisionId: "권리 판단 식별자",
  rightsState: "이용 권리 상태",
  rightsStatus: "권리 상태",
  risk: "위험",
  riskAssessmentDigest: "위험 평가 무결성 지문",
  riskClass: "위험 분류",
  riskLevel: "위험 수준",
  riskNote: "위험 비고",
  riskSummary: "위험 요약",
  risks: "위험 목록",
  roadmap: "개선 계획",
  robots: "검색 수집 정책",
  role: "역할",
  roleCodes: "역할 코드 목록",
  roleGrants: "역할 부여 목록",
  roleId: "역할 식별자",
  roleIds: "역할 식별자 목록",
  roles: "역할 목록",
  rollback: "되돌리기",
  rollbackOrCompensation: "되돌리기 또는 보상 방안",
  rollbackPlan: "되돌리기 계획",
  rollout: "배포",
  rootCause: "근본 원인",
  roundingPolicy: "반올림 정책",
  routing: "경로 배정",
  routingStatus: "경로 배정 상태",
  rowCount: "행 수",
  rows: "표 행 목록",
  rule: "규칙",
  ruleFamily: "규칙 계열",
  ruleId: "규칙 식별자",
  ruleVersion: "규칙 버전",
  ruleVersionId: "규칙 버전 식별자",
  rules: "규칙 목록",
  run: "실행",
  runAfter: "실행 가능 시각",
  runId: "실행 식별자",
  runbook: "운영 절차서",
  runningWorkers: "실행 중인 작업자 수",
  runs: "실행 목록",
} as const satisfies Readonly<Record<string, string>>;
