export const FIELD_LABELS_S_T = {
  safety: "안전 기준",
  sameSite: "동일 사이트 정책",
  sampleDocumentIds: "표본 문서 식별자 목록",
  samples: "표본 목록",
  satisfiedSlots: "충족된 검토 역할 목록",
  save: "저장",
  saveVersion: "저장 버전",
  savedAt: "저장 시각",
  scan: "악성 파일 검사",
  scanRequired: "악성 파일 검사 필요 여부",
  scanStatus: "악성 파일 검사 상태",
  schedule: "일정",
  schema: "스키마",
  schemaDriftId: "스키마 변동 식별자",
  schemaVersion: "스키마 버전",
  schemas: "스키마 목록",
  scope: "범위",
  scopeDigest: "범위 무결성 지문",
  scopeExplanation: "범위 설명",
  scopeId: "범위 식별자",
  scopeRef: "범위 참조",
  scopeType: "범위 유형",
  screenId: "화면 식별자",
  screenState: "화면 상태",
  screen_state: "화면 상태",
  search: "검색",
  sections: "구역 목록",
  secure: "보안 전송 여부",
  security: "보안 기준",
  selectedSegmentCount: "선택 구간 수",
  selectedSegmentSetSha256: "선택 구간 집합 SHA-256 해시값",
  senderConfigId: "발신 설정 식별자",
  sendingConstraints: "발송 제약 조건",
  sentCount: "발송 건수",
  seo: "검색 노출 정보",
  sequence: "순번",
  service: "서비스",
  services: "서비스 목록",
  session: "세션",
  sessionCookieDomainMode: "세션 쿠키 도메인 방식",
  sessionCookiePath: "세션 쿠키 경로",
  sessionCookieSameSite: "세션 쿠키 동일 사이트 정책",
  sessionExpiresAt: "세션 만료 시각",
  sessionId: "세션 식별자",
  sessionKind: "세션 종류",
  sessionResolveCount: "세션 확인 횟수",
  sessionRevokeCount: "세션 폐기 횟수",
  sessionRevoked: "세션 폐기 여부",
  sessions: "세션 목록",
  settled: "정산액",
  settledMicrosKrw: "정산액(마이크로 원화)",
  severity: "심각도",
  sha256: "SHA-256 해시값",
  shadow: "사전 실행 결과",
  signal: "탐지 신호",
  signalCount: "탐지 신호 수",
  signalDetected: "탐지 신호 감지 여부",
  signalId: "탐지 신호 식별자",
  signalStatus: "탐지 신호 상태",
  signals: "탐지 신호 목록",
  signedFrom: "계약 체결 시작일",
  signedTo: "계약 체결 종료일",
  signin: "로그인",
  signoff: "최종 승인",
  sizeBytes: "크기(바이트)",
  slo: "서비스 수준 목표",
  slotKind: "검토 역할 종류",
  slug: "경로명",
  snapshot: "스냅샷",
  snapshotAsOf: "스냅샷 기준 시각",
  snapshotHash: "스냅샷 해시값",
  snapshotId: "스냅샷 식별자",
  snapshots: "스냅샷 목록",
  softLimit: "권고 한도",
  sort: "정렬 기준",
  source: "출처",
  sourceAssetId: "출처 자산 식별자",
  sourceAssetRevision: "출처 자산 개정 번호",
  sourceClass: "출처 분류",
  sourceContentSha256: "출처 내용 SHA-256 해시값",
  sourceContext: "출처 맥락",
  sourceCount: "출처 수",
  sourceDocumentId: "출처 문서 식별자",
  sourceDocuments: "출처 문서 목록",
  sourceHealth: "출처 건전성",
  sourceHref: "출처 링크",
  sourceId: "출처 식별자",
  sourceIds: "출처 식별자 목록",
  sourceLinks: "출처 링크 목록",
  sourceLocator: "출처 내 위치",
  sourceRevision: "출처 개정 번호",
  sourceRunId: "출처 수집 실행 식별자",
  sourceStatus: "출처 상태",
  sourceUrl: "출처 주소",
  sourceVersion: "출처 버전",
  source_id: "출처 식별자",
  source_version: "출처 버전",
  sources: "출처 목록",
  spend: "지출액",
  startedAt: "시작 시각",
  state: "진행 상태",
  stateVersion: "상태 버전",
  statement: "진술",
  statementDigest: "진술 무결성 지문",
  states: "상태 목록",
  status: "현재 상태",
  statusLabel: "상태 표기",
  statuses: "상태 목록",
  stepUpAt: "추가 인증 시각",
  stepUpAuthorizationId: "추가 인증 인가 식별자",
  stepUpAuthorizationToken: "추가 인증 인가 토큰",
  stepUpCallbackCount: "추가 인증 회신 횟수",
  stepUpStartCount: "추가 인증 시작 횟수",
  strongestEvidence: "핵심 근거",
  structure: "구조",
  subject: "제목",
  subjectActorId: "대상 행위자 식별자",
  subjectId: "대상 식별자",
  submissionDigest: "제출 무결성 지문",
  submissionExchanges: "제출 토큰 교환 기록",
  submissionReads: "제출 조회 기록",
  submissionWrites: "제출 변경 기록",
  submissions: "제출 목록",
  submittedAt: "제출 시각",
  submittedCount: "제출 건수",
  subscriptionId: "구독 식별자",
  suggestedQuestions: "제안 질문 목록",
  suggestionId: "제안 식별자",
  suggestions: "제안 목록",
  summary: "요약",
  supersededByRevision: "대체 개정 번호",
  supersedesDeclarationId: "대체 대상 선언 식별자",
  supplierId: "업체 식별자",
  supplierName: "업체명",
  suppliers: "업체 목록",
  support: "지원 정보",
  supporting: "뒷받침 근거",
  supportingAttachmentIds: "뒷받침 첨부 파일 식별자 목록",
  supportingEvidenceIds: "뒷받침 근거 식별자 목록",
  supports: "뒷받침 내용",
  suppressionSnapshotDigest: "발송 억제 시점 정보 무결성 지문",
  surface: "화면 영역",
  systemRole: "시스템 역할",
  systemStatus: "시스템 상태",
  table: "표",
  tableAlternative: "표 형식 대체 설명",
  target: "대상",
  targetDigest: "대상 무결성 지문",
  targetId: "대상 식별자",
  targetRecord: "대상 기록",
  targetRequestDigest: "대상 요청 무결성 지문",
  targetRequestSha256: "대상 요청 SHA-256 해시값",
  targetState: "대상 상태",
  targetType: "대상 유형",
  targetValue: "대상 값",
  targetVersion: "대상 버전",
  targetVersionId: "대상 버전 식별자",
  task: "작업",
  taskId: "작업 식별자",
  taskStatus: "작업 상태",
  taskType: "작업 유형",
  tasks: "작업 목록",
  team: "담당 팀",
  telemetryGaps: "관측 공백",
  templateId: "서식 식별자",
  templateRevision: "서식 개정 번호",
  temporalState: "관계 시점",
  temporarilyRestricted: "일시 제한 여부",
  terminal: "종료 여부",
  terms: "이용 조건",
  testModel: "연결 테스트 모델",
  text: "내용",
  threshold: "기준값",
  thresholds: "기준값 목록",
  timeline: "조사·공개 이력",
  title: "제목",
  to: "종료",
  toEventId: "종료 이벤트 식별자",
  toLabel: "도착",
  toState: "다음 상태",
  tokenConsumedAt: "토큰 사용 시각",
  topCases: "비용 상위 사건",
  topic: "주제",
  topics: "주제 목록",
  total: "합계",
  totalApproximate: "추정 합계",
  transactionCookieValue: "인증 거래 쿠키 값",
  transformations: "변환 목록",
  transition: "상태 전이",
  triage: "초기 분류",
  triggerExplanation: "발동 사유",
  type: "유형",
  types: "유형 목록",
} as const satisfies Readonly<Record<string, string>>;
