export const FIELD_LABELS_U_Z = {
  uncertaintySetDigest: "불확실성 집합 무결성 지문",
  unit: "단위",
  unitCompatibility: "단위 호환성",
  unitPrice: "단가",
  unpriced: "단가 미설정 여부",
  unknownReason: "미확인 사유",
  unknownSetDigest: "미확인 집합 무결성 지문",
  unknowns: "미확인 사항",
  unreadOnly: "미열람만",
  unresolvedBlockers: "미해결 차단 요인",
  unsubscribe: "구독 해지",
  updatedAt: "갱신 시각",
  upload: "업로드",
  uploadStatus: "업로드 상태",
  uploadedSha256: "업로드 파일 SHA-256",
  uploadedSizeBytes: "업로드 크기(바이트)",
  urgent: "긴급 항목",
  usage: "사용량",
  user: "사용자",
  userId: "사용자 식별자",
  users: "사용자 목록",
  validation: "유효성 검증",
  validationState: "유효성 검증 상태",
  validationStatus: "유효성 검증 상태",
  value: "값",
  values: "값 목록",
  variants: "표시 형식",
  vatBasis: "부가가치세 기준",
  vatIncluded: "부가가치세 포함 여부",
  verification: "검증",
  verificationDispatched: "검증 안내 발송 여부",
  verificationStatus: "검증 상태",
  verificationToken: "검증 토큰",
  verifiedAt: "검증 완료 시각",
  version: "버전",
  versioning: "버전 관리",
  versions: "버전 목록",
  viewModelSha256: "표시 정보 무결성 지문",
  views: "보기",
  violations: "위반 사항",
  visualizationId: "시각화 식별자",
  visualizationSetSha256: "시각화 집합 무결성 지문",
  visualizations: "시각화 목록",
  warnings: "경고 사항",
  watermark: "워터마크",
  watermarkPolicy: "워터마크 정책",
  whyMaterial: "중요한 이유",
  whyNow: "현재 필요한 이유",
} as const satisfies Readonly<Record<string, string>>;
