[package]
name = "gurine-object-store"
version.workspace = true
edition.workspace = true

[dependencies]
object_store.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
