[package]
name = "gurine-application"
version.workspace = true
edition.workspace = true

[dependencies]
gurine-auth = { path = "../auth" }
gurine-domain = { path = "../domain" }
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[lints]
workspace = true
