import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-027",
  title: "정정 요청",
  route: "/correction-request",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "intro",
      title: "절차·긴급 안내",
      component: "StatusAndRevisionHeader",
      purpose: "일반/긴급 경로.",
      test_id: "pub_027__section__intro",
    },
    {
      order: 2,
      id: "target",
      title: "대상 선택",
      component: "StatusAndRevisionHeader",
      purpose: "URL·revision·claim.",
      test_id: "pub_027__section__target",
    },
    {
      order: 3,
      id: "issue",
      title: "오류 설명",
      component: "StructuredContentSection",
      purpose: "유형·설명·제안 수정.",
      test_id: "pub_027__section__issue",
    },
    {
      order: 4,
      id: "evidence",
      title: "근거",
      component: "EvidenceLedger",
      purpose: "링크·파일.",
      test_id: "pub_027__section__evidence",
    },
    {
      order: 5,
      id: "privacy",
      title: "연락·공개 동의",
      component: "StructuredContentSection",
      purpose: "최소화.",
      test_id: "pub_027__section__privacy",
    },
    {
      order: 6,
      id: "review",
      title: "검토",
      component: "DecisionReviewPanel",
      purpose: "check answers.",
      test_id: "pub_027__section__review",
    },
  ],
  actions: [
    {
      id: "save-draft",
      label: "임시 저장",
      capability: "none",
      operation_id: "saveCorrectionRequestDraft",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "submit-correction",
      label: "정정 요청 제출",
      capability: "none",
      operation_id: "createCorrectionRequest",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "createCorrectionRequestDraft",
      api: "submission-api",
      method: "POST",
      path: "/v1/correction-session",
      blocking: true,
      response_schema: "createCorrectionRequestDraftReceipt",
    },
    {
      operation_id: "getCorrectionRequestDraft",
      api: "submission-api",
      method: "GET",
      path: "/v1/correction-session",
      blocking: true,
      response_schema: "CorrectionRequestDraft",
    },
    {
      operation_id: "saveCorrectionRequestDraft",
      api: "submission-api",
      method: "PUT",
      path: "/v1/correction-session",
      blocking: true,
      response_schema: "saveCorrectionRequestDraftReceipt",
    },
    {
      operation_id: "createCorrectionAttachment",
      api: "submission-api",
      method: "POST",
      path: "/v1/correction-session/attachments",
      blocking: true,
      response_schema: "createCorrectionAttachmentReceipt",
    },
    {
      operation_id: "finalizeCorrectionAttachment",
      api: "submission-api",
      method: "POST",
      path: "/v1/correction-session/attachments/{attachmentId}:finalize",
      blocking: true,
      response_schema: "finalizeCorrectionAttachmentReceipt",
    },
    {
      operation_id: "deleteCorrectionAttachment",
      api: "submission-api",
      method: "DELETE",
      path: "/v1/correction-session/attachments/{attachmentId}",
      blocking: true,
      response_schema: "deleteCorrectionAttachmentReceipt",
    },
    {
      operation_id: "getCorrectionRequestDraftPreview",
      api: "submission-api",
      method: "GET",
      path: "/v1/correction-session/preview",
      blocking: true,
      response_schema: "CorrectionDraftPreviewResponse",
    },
    {
      operation_id: "createCorrectionRequest",
      api: "submission-api",
      method: "POST",
      path: "/v1/correction-session:submit",
      blocking: true,
      response_schema: "createCorrectionRequestReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
