import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-005",
  title: "근거 검증",
  route: "/internal/cases/{caseId}/evidence/{evidenceId}",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "source",
      title: "출처·원본",
      component: "EvidenceLedger",
      purpose: "owner·retrieval·hash.",
      test_id: "cas_005__section__source",
    },
    {
      order: 2,
      id: "locator",
      title: "정확한 위치",
      component: "StructuredContentSection",
      purpose: "page/row/field.",
      test_id: "cas_005__section__locator",
    },
    {
      order: 3,
      id: "content",
      title: "내용",
      component: "StructuredContentSection",
      purpose: "excerpt·sanitized derivative.",
      test_id: "cas_005__section__content",
    },
    {
      order: 4,
      id: "verification",
      title: "검증",
      component: "StatusAndRevisionHeader",
      purpose: "status·reviewer.",
      test_id: "cas_005__section__verification",
    },
    {
      order: 5,
      id: "relationships",
      title: "관계",
      component: "ClaimWorkbench",
      purpose: "claims/hypotheses.",
      test_id: "cas_005__section__relationships",
    },
    {
      order: 6,
      id: "access",
      title: "접근 분류",
      component: "StructuredContentSection",
      purpose: "privacy/license.",
      test_id: "cas_005__section__access",
    },
  ],
  actions: [
    {
      id: "verify",
      label: "근거 검증 완료",
      capability: "evidence.verify",
      operation_id: "verifyEvidence",
      guard: "independent where required",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "edit-metadata",
      label: "메타데이터 저장",
      capability: "evidence.create",
      operation_id: "updateEvidence",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "create-redaction",
      label: "공개용 가림 처리 생성",
      capability: "evidence.verify",
      operation_id: "createEvidenceRedaction",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getEvidenceWorkspace",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-evidence-workspace",
      blocking: true,
      response_schema: "EvidenceWorkspaceResponse",
    },
    {
      operation_id: "verifyEvidence",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/verify-evidence",
      blocking: true,
      response_schema: "verifyEvidenceResult",
    },
    {
      operation_id: "updateEvidence",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/update-evidence",
      blocking: false,
      response_schema: "updateEvidenceReceipt",
    },
    {
      operation_id: "createEvidenceRedaction",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-evidence-redaction",
      blocking: false,
      response_schema: "createEvidenceRedactionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
