from __future__ import annotations

import hashlib

from pathlib import Path

from verify_release_archives import tree_digest

from .api_support import _ops
from .http_operation_inventory import (
    derive_http_operation_inventory,
    operation_ids,
)
from .loaders import load_json, load_yaml
from .models import Validation


CODEGEN_OUTPUT_DIRECTORIES = {
    'public': 'packages/api-client-public/src/generated',
    'control': 'packages/api-client-control/src/generated',
    'submission': 'packages/api-client-submission/src/generated',
    'identity-internal': 'packages/api-client-identity-internal/src/generated',
    'identity-api': 'packages/api-client-identity-internal/src/generated-procurement',
}


def _validate_codegen_tree(
    root: Path,
    result: Validation,
    name: str,
    item: dict,
) -> None:
    relative = CODEGEN_OUTPUT_DIRECTORIES[name]
    directory = root / relative
    if not directory.is_dir():
        result.error(f'{name}: generated output directory missing: {relative}')
        return
    actual_sha256, actual_files = tree_digest(directory)
    actual_bytes = sum(
        path.stat().st_size for path in directory.rglob('*') if path.is_file()
    )
    result.require(
        item.get('generated_files') == actual_files,
        f'{name}: generated file count differs from output tree',
    )
    result.require(
        item.get('generated_bytes') == actual_bytes,
        f'{name}: generated byte count differs from output tree',
    )
    result.require(
        item.get('tree_sha256') == actual_sha256,
        f'{name}: generated tree hash differs from output tree',
    )


def validate(root: Path, result: Validation) -> None:
    python_evidence = load_yaml(root / 'verification/python-clean-environments.yaml')
    result.require(python_evidence.get('specification_version') == '13.0.0', 'clean Python evidence version mismatch')
    result.require(python_evidence.get('status') == 'PASS', 'clean Python environment evidence is not PASS')
    result.require(python_evidence.get('result') == 'PASS', 'clean Python environment result is not PASS')
    result.require(python_evidence.get('dependency_graph_identical') is True, 'clean Python dependency graphs differ')
    result.require(python_evidence.get('validator_output_identical') is True, 'clean Python validator outputs differ')
    result.require(python_evidence.get('python', {}).get('implementation') == 'CPython', 'clean Python implementation mismatch')
    result.require(python_evidence.get('python', {}).get('version') == '3.13.5', 'clean Python version mismatch')
    result.require(python_evidence.get('validation_command') == 'PYTHONDONTWRITEBYTECODE=1 python -B scripts/validate_final_spec.py --strict --exclude-evidence', 'clean Python validation command differs')

    def sha256(path: Path) -> str:
        return hashlib.sha256(path.read_bytes()).hexdigest()

    requirements = root / 'requirements-spec.txt'
    result.require(
        python_evidence.get('requirements_lock_sha256') == sha256(requirements),
        'requirements lock hash evidence is stale',
    )
    environments = python_evidence.get('environments', [])
    result.require(len(environments) == 2, 'two independent clean Python environments are required')
    freeze_hashes = {item.get('freeze_sha256') for item in environments}
    validator_hashes = {item.get('validator_sha256') for item in environments}
    result.require(len(freeze_hashes) == 1 and None not in freeze_hashes, 'clean Python freeze hashes differ or are missing')
    result.require(len(validator_hashes) == 1 and None not in validator_hashes, 'clean validator output hashes differ or are missing')
    for item in environments:
        for field, hash_field in [
            ('freeze_file', 'freeze_sha256'),
            ('install_log', 'install_log_sha256'),
            ('validator_log', 'validator_sha256'),
        ]:
            path = root / item[field]
            result.require(path.is_file(), f"clean Python evidence file missing: {item[field]}")
            if path.is_file():
                expected_hash = item.get(hash_field)
                result.require(
                    isinstance(expected_hash, str) and len(expected_hash) == 64 and 'provisional' not in expected_hash,
                    f"clean Python evidence hash is not final: {hash_field}",
                )
                result.require(sha256(path) == expected_hash, f"clean Python evidence hash differs: {item[field]}")
        validator_log = root / item['validator_log']
        if validator_log.is_file():
            text = validator_log.read_text(encoding='utf-8', errors='replace')
            result.require(text.rstrip().endswith('RESULT: PASS'), f"clean validator log did not PASS: {item['validator_log']}")

    codegen = load_json(root / 'verification/codegen-compatibility.json')
    result.require(codegen.get('result') == 'PASS', 'code generation evidence is not PASS')
    result.require(codegen.get('strict_typescript_compile') == 'PASS', 'generated clients did not pass strict TypeScript compile')
    result.require(codegen.get('deterministic_regeneration') == 'PASS', 'generated clients are not deterministic')
    inventory = derive_http_operation_inventory(root)
    base_operations = inventory.base_external
    base_ids = set(operation_ids(base_operations))
    additive_ids = set(operation_ids(inventory.additive_all))
    additive_external_ids = set(operation_ids(inventory.additive_external))
    private_identity_api_ids = set(operation_ids(inventory.private_identity_api))
    base_by_api = {
        api: sum(row.get('api') == api for row in base_operations)
        for api in ['public-api', 'submission-api', 'control-api']
    }
    internal_identity_ids = set(
        _ops(load_yaml(root / 'specs/api/identity-service-internal.openapi.yaml'))
    )
    expected_operations = {
        'public': base_by_api['public-api'],
        'submission': base_by_api['submission-api'],
        'control': base_by_api['control-api'],
        'identity-internal': len(internal_identity_ids),
        'identity-api': len(private_identity_api_ids),
    }
    openapi_sources = {
        'public': 'specs/api/public-api.openapi.yaml',
        'submission': 'specs/api/submission-api.openapi.yaml',
        'control': 'specs/api/control-api.openapi.yaml',
        'identity-internal': 'specs/api/identity-service-internal.openapi.yaml',
        'identity-api': 'specs/api/identity-api.openapi.yaml',
    }
    generated_operation_ids = {
        name: set(_ops(load_yaml(root / relative)))
        for name, relative in openapi_sources.items()
    }
    result.require(
        len(base_operations) == 217
        and expected_operations
        == {
            'public': 43,
            'submission': 34,
            'control': 134,
            'identity-internal': 9,
            'identity-api': 3,
        },
        'codegen frozen base operation layer differs',
    )
    result.require(
        len(additive_ids) == 54
        and len(additive_external_ids) == 51
        and len(private_identity_api_ids) == 3
        and not (base_ids & additive_ids)
        and additive_external_ids | private_identity_api_ids == additive_ids
        and not (additive_external_ids & private_identity_api_ids)
        and additive_external_ids
        == inventory.declared_additive_external_ids
        == inventory.binding_additive_external_ids
        and private_identity_api_ids
        == inventory.declared_private_identity_api_ids
        == inventory.binding_private_identity_api_ids,
        'codegen additive external/private Identity API partitions differ',
    )
    identity_provider_ids = set(
        _ops(load_yaml(root / 'specs/api/identity-provider.openapi.yaml'))
    )
    generated_final_external_ids = (
        generated_operation_ids['public']
        | generated_operation_ids['submission']
        | generated_operation_ids['control']
        | identity_provider_ids
    )
    result.require(
        generated_final_external_ids
        == base_ids | additive_external_ids
        and len(generated_final_external_ids) == 268,
        'generated final external OpenAPI operation set differs',
    )
    result.require(
        generated_operation_ids['identity-api'] == private_identity_api_ids
        and not (generated_operation_ids['identity-api'] & internal_identity_ids),
        'generated private Identity API must be exact and disjoint from the nine-operation Identity service',
    )
    codegen_contracts = codegen.get('contracts', {})
    result.require(
        set(codegen_contracts) == set(expected_operations),
        'code generation evidence does not cover five generation targets',
    )
    for name, operation_count in expected_operations.items():
        item = codegen_contracts.get(name, {})
        result.require(item.get('operations') == operation_count, f'{name}: codegen operation count differs')
        result.require(
            item.get('generated_sdk_exports') == len(generated_operation_ids[name]),
            f'{name}: generated SDK export count differs from the effective OpenAPI source',
        )
        result.require(item.get('generation') == 'PASS', f'{name}: code generation did not pass')
        result.require(item.get('second_generation_diff') == '0 bytes', f'{name}: regeneration diff is not empty')
        _validate_codegen_tree(root, result, name, item)

    parser = load_json(root / 'verification/sql-openapi-parser.json')
    result.require(parser.get('result') == 'PASS', 'SQL/OpenAPI parser evidence is not PASS')
    base_migration_count = load_yaml(
        root / 'specs/database/schema-catalog.yaml'
    )['migration_count']
    result.require(
        parser['postgresql'].get('migrations') == base_migration_count == 24
        and parser['postgresql'].get('errors') == 0
        and str(parser['postgresql'].get('scope', '')).startswith('Frozen 24-migration base'),
        'frozen base SQL parser evidence differs',
    )
    result.require(parser['openapi'].get('documents') == 6 and parser['openapi'].get('errors') == 0, 'OpenAPI validator evidence differs')
    expected_openapi_counts = {
        relative: len(generated_operation_ids[name])
        for name, relative in openapi_sources.items()
    }
    expected_openapi_counts['specs/api/identity-provider.openapi.yaml'] = len(
        identity_provider_ids
    )
    result.require(
        parser['openapi'].get('operation_counts') == expected_openapi_counts,
        'OpenAPI parser evidence operation counts differ from current source documents',
    )

    parser_reference = load_json(root / 'verification/parser-reference.json')
    result.require(parser_reference.get('result') == 'PASS' and parser_reference.get('caseCount') == 15 and parser_reference.get('goldenCount') == 15, 'parser reference evidence differs')
    crypto_reference = load_json(root / 'verification/cryptography-reference.json')
    result.require(crypto_reference.get('result') == 'PASS', 'cryptography reference evidence is not PASS')
    result.require(crypto_reference.get('stats') == {'cryptographic_envelope_vectors': 5, 'cryptographic_negative_cases': 8}, 'cryptography reference evidence differs')

    renders = load_json(root / 'verification/final-reference/render-results.json')
    result.require(len(renders) == 10, f'expected 10 visual reference renders, found {len(renders)}')
    result.require(all(not item.get('page_errors') for item in renders), 'visual reference render contains page errors')
    for item in renders:
        result.require((root / item['file']).is_file(), f"visual render missing: {item['file']}")

    result.stats.update({
        'clean_python_environments': len(environments),
        'generated_client_packages': 4,
        'generated_client_targets_verified': len(expected_operations),
        'base_external_codegen_operations': len(base_operations),
        'final_external_codegen_operations': len(generated_final_external_ids),
        'private_identity_api_codegen_operations': len(
            generated_operation_ids['identity-api']
        ),
        'openapi_documents_verified': parser['openapi']['documents'],
        'sql_migrations_parsed': parser['postgresql']['migrations'],
        'visual_reference_renders': len(renders),
        'parser_reference_cases': parser_reference['caseCount'],
        'cryptography_reference_vectors': crypto_reference['stats']['cryptographic_envelope_vectors'],
    })
