from __future__ import annotations
from pathlib import Path
from .loaders import load_yaml
from .models import Validation
REQUIRED=['README.md','AGENTS.md','CODEX_START_HERE.md','FINAL_BUILD_CONTRACT.md','SPECIFICATION_VERSION','requirements-spec.in','requirements-spec.txt','.python-version','specs/verification/python-toolchain.yaml','specs/product/final-product-contract.yaml','specs/domain/state-machines.yaml','specs/domain/state-transition-tests.yaml','specs/api/operation-contracts.yaml','specs/api/error-code-catalog.yaml','specs/application/command-semantics.yaml','specs/application/optimistic-concurrency.yaml','specs/application/optimistic-concurrency.runtime.json','specs/auth/assurance-policy.yaml','specs/auth/assertion-contract.yaml','specs/auth/service-assertion.schema.json','specs/auth/actor-assertion.schema.json','specs/auth/test-vectors/service-assertion.json','specs/auth/test-vectors/actor-assertion.json','specs/auth/test-vectors/negative-cases.json','specs/api/operation-persistence.yaml','specs/events/event-catalog.yaml','specs/events/consumer-catalog.yaml','specs/database/operation-table-matrix.yaml','specs/database/privilege-matrix.yaml','specs/database/runtime-security-tests.yaml','specs/deployment/egress-allowlist.yaml','specs/deployment/service-config-map.yaml','specs/agents/agent-catalog.yaml','specs/agents/eval-manifest.yaml','specs/connectors/connector-catalog.yaml','specs/detection/rule-evaluation-catalog.yaml','specs/traceability/final-traceability.yaml','specs/traceability/internal-identity-traceability.yaml','specs/engineering/code-quality-contract.yaml','tests/acceptance/executable-mapping.yaml','verification/python-clean-environments.yaml','verification/postgres-runtime-baseline.json','scripts/compare_postgres_runtime.py','specs/cryptography/session-cookie-envelope.yaml','specs/cryptography/field-encryption-envelope.yaml','specs/cryptography/step-up-transaction-envelope.yaml','specs/cryptography/step-up-authorization-envelope.yaml','specs/cryptography/session-cookie-payload.schema.json','specs/cryptography/step-up-transaction-payload.schema.json','specs/cryptography/step-up-authorization-payload.schema.json','specs/parsers/parser-catalog.yaml','specs/parsers/sandbox-contract.yaml','specs/parsers/extraction-result.schema.json','specs/parsers/fixture-manifest.yaml','specs/parsers/reference_harness.py','verification/postgres-runtime/package.json','verification/postgres-runtime/package-lock.json','verification/postgres-runtime/verify.mjs','verification/codegen-compatibility.json','verification/sql-openapi-parser.json','verification/parser-reference.json','verification/cryptography-reference.json','docs/61-v12-assurance-legal-audit-parser-closure.md','verification/final-reference/render-results.json','tasks/FINAL-IMPLEMENTATION.md','tasks/FINAL-VERIFICATION.md']
IGNORED={'.venv','venv','node_modules','target','.git','.pytest_cache'}
def ignored(path:Path,root:Path)->bool: return any(part in IGNORED for part in path.relative_to(root).parts)
def validate(root:Path,result:Validation,version:str)->None:
 for relative in REQUIRED: result.require((root/relative).is_file(),f'missing required authority file: {relative}')
 actual=(root/'SPECIFICATION_VERSION').read_text(encoding='utf-8').strip(); result.require(actual==version,f'SPECIFICATION_VERSION={actual!r}, expected {version!r}')
 caches=[p.relative_to(root).as_posix() for p in root.rglob('__pycache__') if not ignored(p,root)]; pyc=[p.relative_to(root).as_posix() for p in root.rglob('*.pyc') if not ignored(p,root)]; result.require(not caches,f'Python cache directories forbidden: {caches[:5]}'); result.require(not pyc,f'Python bytecode forbidden: {pyc[:5]}')
 product=load_yaml(root/'specs/product/final-product-contract.yaml'); expected={'screens':94,'operations':215,'query_operations':108,'command_operations':107,'http_write_operations':104,'database_migrations':24,'database_tables':107,'domain_and_integration_events':99,'acceptance_features':35,'acceptance_scenarios':271,'agent_eval_cases':50}
 for key,value in expected.items(): result.require(product['counts'].get(key)==value,f'product contract {key}={product["counts"].get(key)}, expected {value}')
 toolchain=load_yaml(root/'specs/verification/python-toolchain.yaml'); result.require(toolchain['status']=='FINAL' and toolchain['installer']['hashes_required'] is True,'Python verifier lock contract incomplete'); result.require((root/'.python-version').read_text(encoding='utf-8').strip()==str(toolchain['python']['verified_patch']),'Python patch pin differs from verifier contract'); result.stats['required_authority_files']=len(REQUIRED)
