import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RULE-002",
  title: "규칙 Version 상세",
  route: "/internal/rules/{ruleId}/versions/{version}",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "version identity",
      component: "StatusAndRevisionHeader",
      purpose: "status·owner·hash.",
      test_id: "rule_002__section__identity",
    },
    {
      order: 2,
      id: "definition",
      title: "정의",
      component: "GuidedFormSection",
      purpose: "input/formula/trigger.",
      test_id: "rule_002__section__definition",
    },
    {
      order: 3,
      id: "cohort",
      title: "cohort",
      component: "ComparisonWorkbench",
      purpose: "include/exclude.",
      test_id: "rule_002__section__cohort",
    },
    {
      order: 4,
      id: "blockers",
      title: "blocker",
      component: "StructuredContentSection",
      purpose: "quality guard.",
      test_id: "rule_002__section__blockers",
    },
    {
      order: 5,
      id: "diff",
      title: "version diff",
      component: "StructuredContentSection",
      purpose: "previous.",
      test_id: "rule_002__section__diff",
    },
    {
      order: 6,
      id: "usage",
      title: "사용",
      component: "SignalTriagePanel",
      purpose: "runs/signals/public cases.",
      test_id: "rule_002__section__usage",
    },
    {
      order: 7,
      id: "approval",
      title: "승인 이력",
      component: "RevisionTimeline",
      purpose: "reviewers.",
      test_id: "rule_002__section__approval",
    },
  ],
  actions: [
    {
      id: "open-evaluation",
      label: "평가 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "create-draft",
      label: "다음 version 초안",
      capability: "rules.propose",
      operation_id: "createRuleVersionDraft",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "download-definition",
      label: "정의 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getInternalRuleVersion",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-internal-rule-version",
      blocking: true,
      response_schema: "InternalRuleVersionResponse",
    },
    {
      operation_id: "createRuleVersionDraft",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-rule-version-draft",
      blocking: false,
      response_schema: "createRuleVersionDraftReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
