import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "COR-002",
  title: "정정 작업공간",
  route: "/internal/corrections/{correctionId}",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "request",
      title: "요청",
      component: "EvidenceLedger",
      purpose: "target·issue·evidence.",
      test_id: "cor_002__section__request",
    },
    {
      order: 2,
      id: "original",
      title: "원본",
      component: "StatusAndRevisionHeader",
      purpose: "claim/revision/context.",
      test_id: "cor_002__section__original",
    },
    {
      order: 3,
      id: "investigation",
      title: "검증",
      component: "StructuredContentSection",
      purpose: "source·calculation.",
      test_id: "cor_002__section__investigation",
    },
    {
      order: 4,
      id: "proposal",
      title: "변경 전후",
      component: "StructuredContentSection",
      purpose: "reason·root cause.",
      test_id: "cor_002__section__proposal",
    },
    {
      order: 5,
      id: "impact",
      title: "영향",
      component: "StructuredContentSection",
      purpose: "API/download/notification/search.",
      test_id: "cor_002__section__impact",
    },
    {
      order: 6,
      id: "review",
      title: "검토·결정",
      component: "DecisionReviewPanel",
      purpose: "editorial/legal/publish.",
      test_id: "cor_002__section__review",
    },
    {
      order: 7,
      id: "receipt",
      title: "요청자 회신",
      component: "StatusAndRevisionHeader",
      purpose: "public-safe status.",
      test_id: "cor_002__section__receipt",
    },
  ],
  actions: [
    {
      id: "save-proposal",
      label: "정정 초안 저장",
      capability: "publication.correct",
      operation_id: "updateCorrectionDraft",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "create-revision",
      label: "정정 개정본 생성",
      capability: "publication.correct",
      operation_id: "createCorrection",
      guard: "reviews + reason",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
    {
      id: "reject-request",
      label: "정정하지 않음 결정",
      capability: "publication.correct",
      operation_id: "resolveCorrectionRequest",
      guard: "reason + review",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "temporary-limit",
      label: "임시 공개 제한",
      capability: "review.legal",
      operation_id: "placeTemporaryRestriction",
      guard: "urgent criteria + expiry",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "STEP_UP",
      step_up_required: true,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getCorrectionWorkspace",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-correction-workspace",
      blocking: true,
      response_schema: "CorrectionWorkspaceResponse",
    },
    {
      operation_id: "updateCorrectionDraft",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/update-correction-draft",
      blocking: true,
      response_schema: "updateCorrectionDraftReceipt",
    },
    {
      operation_id: "createCorrection",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-correction",
      blocking: true,
      response_schema: "createCorrectionReceipt",
    },
    {
      operation_id: "resolveCorrectionRequest",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/resolve-correction-request",
      blocking: true,
      response_schema: "resolveCorrectionRequestReceipt",
    },
    {
      operation_id: "placeTemporaryRestriction",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/place-temporary-restriction",
      blocking: false,
      response_schema: "placeTemporaryRestrictionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
