import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-012",
  title: "사건 타임라인",
  route: "/internal/cases/{caseId}/timeline",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "filters",
      title: "이벤트 필터",
      component: "UnifiedSearch",
      purpose: "domain/type/actor.",
      test_id: "cas_012__section__filters",
    },
    {
      order: 2,
      id: "timeline",
      title: "시간순 이벤트",
      component: "RevisionTimeline",
      purpose: "absolute timestamp.",
      test_id: "cas_012__section__timeline",
    },
    {
      order: 3,
      id: "public-view",
      title: "공개 이력 미리보기",
      component: "RevisionTimeline",
      purpose: "승인된 항목.",
      test_id: "cas_012__section__public-view",
    },
    {
      order: 4,
      id: "related",
      title: "관련 확인서",
      component: "StructuredContentSection",
      purpose: "event link.",
      test_id: "cas_012__section__related",
    },
  ],
  actions: [
    {
      id: "filter",
      label: "이벤트 필터",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-event",
      label: "이벤트 상세",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "export",
      label: "타임라인 내보내기",
      capability: "audit.read",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCaseTimeline",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-case-timeline",
      blocking: true,
      response_schema: "CaseTimelinePage",
    },
  ],
} as const satisfies ScreenViewModel;
