import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "INT-003",
  title: "내부 검색",
  route: "/internal/search",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "query",
      title: "검색",
      component: "UnifiedSearch",
      purpose: "ID·텍스트·locator.",
      test_id: "int_003__section__query",
    },
    {
      order: 2,
      id: "types",
      title: "객체 유형",
      component: "EvidenceLedger",
      purpose: "case/signal/evidence/run.",
      test_id: "int_003__section__types",
    },
    {
      order: 3,
      id: "results",
      title: "결과",
      component: "UnifiedSearch",
      purpose: "permission-filtered.",
      test_id: "int_003__section__results",
    },
    {
      order: 4,
      id: "recent",
      title: "최근 기록",
      component: "RevisionTimeline",
      purpose: "개인 편의, 민감정보 최소.",
      test_id: "int_003__section__recent",
    },
  ],
  actions: [
    {
      id: "submit-search",
      label: "검색",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "filter-type",
      label: "유형 필터",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-result",
      label: "결과 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "searchInternalRecords",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/search-internal-records",
      blocking: true,
      response_schema: "InternalRecordsSearchResultPage",
    },
  ],
} as const satisfies ScreenViewModel;
