// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DecideSupplierRelationshipAssertionData, DecideSupplierRelationshipAssertionErrors, DecideSupplierRelationshipAssertionResponses, RecordSupplierIdentityResolutionData, RecordSupplierIdentityResolutionErrors, RecordSupplierIdentityResolutionResponses, RecordSupplierRelationshipAssertionData, RecordSupplierRelationshipAssertionErrors, RecordSupplierRelationshipAssertionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * recordSupplierIdentityResolution
 */
export const recordSupplierIdentityResolution = <ThrowOnError extends boolean = false>(options: Options<RecordSupplierIdentityResolutionData, ThrowOnError>): RequestResult<RecordSupplierIdentityResolutionResponses, RecordSupplierIdentityResolutionErrors, ThrowOnError> => (options.client ?? client).post<RecordSupplierIdentityResolutionResponses, RecordSupplierIdentityResolutionErrors, ThrowOnError>({
    security: [{ name: 'X-Gurine-Service-Assertion', type: 'apiKey' }],
    url: '/v1/internal/supplier-identity/resolutions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * recordSupplierRelationshipAssertion
 */
export const recordSupplierRelationshipAssertion = <ThrowOnError extends boolean = false>(options: Options<RecordSupplierRelationshipAssertionData, ThrowOnError>): RequestResult<RecordSupplierRelationshipAssertionResponses, RecordSupplierRelationshipAssertionErrors, ThrowOnError> => (options.client ?? client).post<RecordSupplierRelationshipAssertionResponses, RecordSupplierRelationshipAssertionErrors, ThrowOnError>({
    security: [{ name: 'X-Gurine-Service-Assertion', type: 'apiKey' }],
    url: '/v1/internal/supplier-relationships/assertions',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * decideSupplierRelationshipAssertion
 */
export const decideSupplierRelationshipAssertion = <ThrowOnError extends boolean = false>(options: Options<DecideSupplierRelationshipAssertionData, ThrowOnError>): RequestResult<DecideSupplierRelationshipAssertionResponses, DecideSupplierRelationshipAssertionErrors, ThrowOnError> => (options.client ?? client).post<DecideSupplierRelationshipAssertionResponses, DecideSupplierRelationshipAssertionErrors, ThrowOnError>({
    security: [{ name: 'X-Gurine-Service-Assertion', type: 'apiKey' }],
    url: '/v1/internal/supplier-relationships/assertions/{assertionId}:decide',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
