// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://identity-api:8085' | (string & {});
};

export type AddendumProblemDetailsV1 = {
    code: string;
    title: string;
    status: number;
    requestId: string;
};

export type SupplierIdentityResolutionRequestV1 = {
    action: string;
    candidateRefs: Array<string>;
    expectedCandidateSetDigest: string;
    expectedPriorDecisionDigest: string;
    fromCanonicalSupplierIds: Array<string>;
    toCanonicalSupplierIds: Array<string>;
    evidenceLocators: Array<string>;
    expectedEvidenceLocatorSetDigest: string;
    expectedPublicImpactSetDigest: string;
    impactOwnerUserId: string;
    impactDueAt: string;
    reasonCode: string;
    reason: string;
};

export type SupplierIdentityResolutionReceiptV1 = {
    decisionId: string;
    decisionSequence: number;
    action: string;
    candidateSetDigest: string;
    evidenceLocatorSetDigest: string;
    publicImpactSetDigest: string;
    decisionDigest: string;
    actorUserId: string;
    auditEventId: string;
    emittedEventIds: Array<string>;
    acceptedAt: string;
};

export type AssertionPartyV1 = {
    partyKind: string;
    supplierCandidateId: string;
    supplierCandidateRevision: number;
    supplierCandidateDigest: string;
    canonicalSupplierId: string;
    identityKeyDigest: string;
    identityStatus: string;
};

export type CreateSupplierRelationshipAssertionRequestV1 = {
    relationshipKind: string;
    subject: AssertionPartyV1;
    object: AssertionPartyV1;
    ownershipPercent: number;
    managementRole: string | null;
    validFrom: string;
    validTo: string;
    validityCoverageStatus: string;
    evidenceLocators: Array<string>;
    expectedEvidenceLocatorSetDigest: string;
    reason: string;
};

export type SupplierRelationshipAssertionReceiptV1 = {
    assertionId: string;
    assertionRevision: number;
    assertionDigest: string;
    verificationStatus: string;
    evidenceLocatorSetDigest: string;
    verifiedBy: string;
    verifiedAt: string;
    auditEventId: string;
    emittedEventIds: Array<string>;
    acceptedAt: string;
};

export type DecideSupplierRelationshipAssertionRequestV1 = {
    assertionId: string;
    expectedAssertionRevision: number;
    expectedAssertionDigest: string;
    expectedEvidenceLocatorSetDigest: string;
    decision: string;
    counterAssertionIds: Array<string>;
    reasonCode: string;
    reason: string;
};

export type RecordSupplierIdentityResolutionData = {
    body: SupplierIdentityResolutionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/internal/supplier-identity/resolutions';
};

export type RecordSupplierIdentityResolutionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type RecordSupplierIdentityResolutionError = RecordSupplierIdentityResolutionErrors[keyof RecordSupplierIdentityResolutionErrors];

export type RecordSupplierIdentityResolutionResponses = {
    /**
     * Successful response
     */
    201: SupplierIdentityResolutionReceiptV1;
};

export type RecordSupplierIdentityResolutionResponse = RecordSupplierIdentityResolutionResponses[keyof RecordSupplierIdentityResolutionResponses];

export type RecordSupplierRelationshipAssertionData = {
    body: CreateSupplierRelationshipAssertionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/internal/supplier-relationships/assertions';
};

export type RecordSupplierRelationshipAssertionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type RecordSupplierRelationshipAssertionError = RecordSupplierRelationshipAssertionErrors[keyof RecordSupplierRelationshipAssertionErrors];

export type RecordSupplierRelationshipAssertionResponses = {
    /**
     * Successful response
     */
    201: SupplierRelationshipAssertionReceiptV1;
};

export type RecordSupplierRelationshipAssertionResponse = RecordSupplierRelationshipAssertionResponses[keyof RecordSupplierRelationshipAssertionResponses];

export type DecideSupplierRelationshipAssertionData = {
    body: DecideSupplierRelationshipAssertionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        assertionId: string;
    };
    query?: never;
    url: '/v1/internal/supplier-relationships/assertions/{assertionId}:decide';
};

export type DecideSupplierRelationshipAssertionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type DecideSupplierRelationshipAssertionError = DecideSupplierRelationshipAssertionErrors[keyof DecideSupplierRelationshipAssertionErrors];

export type DecideSupplierRelationshipAssertionResponses = {
    /**
     * Successful response
     */
    200: SupplierRelationshipAssertionReceiptV1;
};

export type DecideSupplierRelationshipAssertionResponse = DecideSupplierRelationshipAssertionResponses[keyof DecideSupplierRelationshipAssertionResponses];
