// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://identity-api:8085' | (string & {});
};

export type AddendumProblemDetailsV1 = {
    code: string;
    title: string;
    status: number;
    requestId: string;
};

export type SupplierPartyRefV1 = {
    candidateId: string;
    candidateRevision: number;
    candidateDigest: string;
    identityStatus: 'UNVERIFIED' | 'CANDIDATE' | 'VERIFIED' | 'AMBIGUOUS' | 'CONFLICTED' | 'REJECTED';
    valueHmac: string | null;
};

export type EvidenceLocatorRefV1 = {
    evidenceId: string;
    evidenceVersion: number;
    evidenceDigest: string;
    sourceDocumentId: string;
    sourceAssetId: string;
    sourceAssetRevision: number;
    locatorDigest: string;
};

export type SupplierIdentityResolutionRequestV1 = {
    action: 'MERGE' | 'SPLIT' | 'KEEP_SEPARATE' | 'MARK_AMBIGUOUS';
    candidateRefs: Array<SupplierPartyRefV1>;
    expectedCandidateSetDigest: string;
    expectedPriorDecisionDigest: string | null;
    fromCanonicalSupplierIds: Array<string>;
    toCanonicalSupplierIds: Array<string>;
    evidenceLocators: Array<EvidenceLocatorRefV1>;
    expectedEvidenceLocatorSetDigest: string;
    expectedPublicImpactSetDigest: string;
    impactOwnerUserId: string | null;
    impactDueAt: string | null;
    reasonCode: 'AUTHORITATIVE_IDENTIFIER_MATCH' | 'AUTHORITATIVE_IDENTIFIER_CONFLICT' | 'SOURCE_CORRECTION' | 'FALSE_MERGE' | 'INSUFFICIENT_EVIDENCE';
    reason: string;
};

export type SupplierIdentityResolutionReceiptV1 = {
    decisionId: string;
    decisionSequence: number;
    action: 'MERGE' | 'SPLIT' | 'KEEP_SEPARATE' | 'MARK_AMBIGUOUS';
    candidateSetDigest: string;
    evidenceLocatorSetDigest: string;
    publicImpactSetDigest: string;
    decisionDigest: string;
    actorUserId: string;
    auditEventId: string;
    emittedEventIds: Array<string>;
    acceptedAt: string;
};

export type AssertionPartyV1 = {
    partyKind: 'SUPPLIER' | 'ORGANIZATION' | 'NATURAL_PERSON';
    supplierCandidateId: string | null;
    supplierCandidateRevision: number | null;
    supplierCandidateDigest: string | null;
    canonicalSupplierId: string | null;
    identityKeyDigest: string;
    identityStatus: 'UNVERIFIED' | 'CANDIDATE' | 'VERIFIED' | 'AMBIGUOUS' | 'CONFLICTED' | 'REJECTED';
};

export type CreateSupplierRelationshipAssertionRequestV1 = {
    relationshipKind: 'OWNERSHIP' | 'BENEFICIAL_OWNERSHIP' | 'CONTROL' | 'MANAGEMENT_ROLE' | 'LEGAL_REPRESENTATIVE' | 'CONTRACTUAL_RELATIONSHIP';
    subject: AssertionPartyV1;
    object: AssertionPartyV1;
    ownershipPercent: number | null;
    managementRole: string | null;
    validFrom: string | null;
    validTo: string | null;
    validityCoverageStatus: 'COMPLETE' | 'PARTIAL' | 'UNKNOWN' | 'NOT_AVAILABLE';
    evidenceLocators: Array<EvidenceLocatorRefV1>;
    expectedEvidenceLocatorSetDigest: string;
    reason: string;
};

export type SupplierRelationshipAssertionReceiptV1 = {
    assertionId: string;
    assertionRevision: number;
    assertionDigest: string;
    verificationStatus: 'PENDING' | 'VERIFIED' | 'REJECTED' | 'CONFLICTED' | 'SUPERSEDED';
    evidenceLocatorSetDigest: string;
    verifiedBy: string | null;
    verifiedAt: string | null;
    auditEventId: string;
    emittedEventIds: Array<string>;
    acceptedAt: string;
};

export type DecideSupplierRelationshipAssertionRequestV1 = {
    assertionId: string;
    expectedAssertionRevision: number;
    expectedAssertionDigest: string;
    expectedEvidenceLocatorSetDigest: string;
    decision: 'VERIFY' | 'REJECT' | 'MARK_CONFLICT' | 'SUPERSEDE';
    counterAssertionIds: Array<string>;
    reasonCode: 'EVIDENCE_CONFIRMED' | 'EVIDENCE_INSUFFICIENT' | 'EVIDENCE_CONTRADICTED' | 'SOURCE_CORRECTED' | 'ASSERTION_SUPERSEDED';
    reason: string;
};

export type RecordSupplierIdentityResolutionData = {
    body: SupplierIdentityResolutionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/internal/supplier-identity/resolutions';
};

export type RecordSupplierIdentityResolutionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type RecordSupplierIdentityResolutionError = RecordSupplierIdentityResolutionErrors[keyof RecordSupplierIdentityResolutionErrors];

export type RecordSupplierIdentityResolutionResponses = {
    /**
     * Successful response
     */
    201: SupplierIdentityResolutionReceiptV1;
};

export type RecordSupplierIdentityResolutionResponse = RecordSupplierIdentityResolutionResponses[keyof RecordSupplierIdentityResolutionResponses];

export type RecordSupplierRelationshipAssertionData = {
    body: CreateSupplierRelationshipAssertionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/internal/supplier-relationships/assertions';
};

export type RecordSupplierRelationshipAssertionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type RecordSupplierRelationshipAssertionError = RecordSupplierRelationshipAssertionErrors[keyof RecordSupplierRelationshipAssertionErrors];

export type RecordSupplierRelationshipAssertionResponses = {
    /**
     * Successful response
     */
    201: SupplierRelationshipAssertionReceiptV1;
};

export type RecordSupplierRelationshipAssertionResponse = RecordSupplierRelationshipAssertionResponses[keyof RecordSupplierRelationshipAssertionResponses];

export type DecideSupplierRelationshipAssertionData = {
    body: DecideSupplierRelationshipAssertionRequestV1;
    headers: {
        'Idempotency-Key': string;
    };
    path: {
        assertionId: string;
    };
    query?: never;
    url: '/v1/internal/supplier-relationships/assertions/{assertionId}:decide';
};

export type DecideSupplierRelationshipAssertionErrors = {
    /**
     * Problem response: INVALID_PARAMETER
     */
    400: AddendumProblemDetailsV1;
    /**
     * Problem response: CAPABILITY_DENIED
     */
    403: AddendumProblemDetailsV1;
    /**
     * Problem response: RESOURCE_NOT_FOUND
     */
    404: AddendumProblemDetailsV1;
    /**
     * Problem response: VERSION_CONFLICT, IDEMPOTENCY_CONFLICT
     */
    409: AddendumProblemDetailsV1;
    /**
     * Problem response: INTERNAL_ERROR
     */
    500: AddendumProblemDetailsV1;
};

export type DecideSupplierRelationshipAssertionError = DecideSupplierRelationshipAssertionErrors[keyof DecideSupplierRelationshipAssertionErrors];

export type DecideSupplierRelationshipAssertionResponses = {
    /**
     * Successful response
     */
    200: SupplierRelationshipAssertionReceiptV1;
};

export type DecideSupplierRelationshipAssertionResponse = DecideSupplierRelationshipAssertionResponses[keyof DecideSupplierRelationshipAssertionResponses];
