import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-014",
  title: "탐지 규칙 상세",
  route: "/methodology/rules/{ruleId}",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "purpose",
      title: "목적",
      component: "StructuredContentSection",
      purpose: "찾는 패턴과 비목표.",
      test_id: "pub_014__section__purpose",
    },
    {
      order: 2,
      id: "inputs",
      title: "필요 데이터",
      component: "StructuredContentSection",
      purpose: "필수 field와 quality.",
      test_id: "pub_014__section__inputs",
    },
    {
      order: 3,
      id: "calculation",
      title: "계산",
      component: "ComparisonWorkbench",
      purpose: "formula·cohort·threshold.",
      test_id: "pub_014__section__calculation",
    },
    {
      order: 4,
      id: "blockers",
      title: "차단 조건",
      component: "StructuredContentSection",
      purpose: "unit·VAT·bundle 등.",
      test_id: "pub_014__section__blockers",
    },
    {
      order: 5,
      id: "false-positive",
      title: "오탐",
      component: "StructuredContentSection",
      purpose: "known alternatives.",
      test_id: "pub_014__section__false-positive",
    },
    {
      order: 6,
      id: "evaluation",
      title: "평가",
      component: "DataCollection",
      purpose: "sample·precision 관련 공개 가능 결과.",
      test_id: "pub_014__section__evaluation",
    },
    {
      order: 7,
      id: "versions",
      title: "버전 이력",
      component: "StructuredContentSection",
      purpose: "변경·retired.",
      test_id: "pub_014__section__versions",
    },
  ],
  actions: [
    {
      id: "view-related-cases",
      label: "관련 공개 사례",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "download-rule",
      label: "규칙 정의 다운로드",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getRule",
      api: "public-api",
      method: "GET",
      path: "/v1/rules/{ruleId}",
      blocking: true,
      response_schema: "RuleResponse",
    },
    {
      operation_id: "listRuleCases",
      api: "public-api",
      method: "GET",
      path: "/v1/rules/{ruleId}/cases",
      blocking: false,
      response_schema: "RuleCasesPage",
    },
  ],
} as const satisfies ScreenViewModel;
