import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-035",
  title: "후원",
  route: "/donate",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "mode",
      title: "운영 상태",
      component: "StatusAndRevisionHeader",
      purpose:
        "테스트 전용 제안만 제공하며 운영 기준이 없으면 후원을 접수하지 않습니다.",
      test_id: "pub_035__section__mode",
    },
    {
      order: 2,
      id: "independence",
      title: "후원 독립성",
      component: "KnownUnknownResponse",
      purpose: "후원은 접근권이 아니며 조사 대상 면제가 아닙니다",
      test_id: "pub_035__section__independence",
    },
    {
      order: 3,
      id: "donation",
      title: "후원 의향",
      component: "GuidedFormSection",
      purpose: "테스트 전용 금액대와 일회·정기 후원, 결제사 선택을 확인합니다.",
      test_id: "pub_035__section__donation",
    },
    {
      order: 4,
      id: "receipt",
      title: "접수 상태",
      component: "DecisionReceipt",
      purpose: "접수 대기 영수증만 표시하며 결제·청구 성공을 뜻하지 않습니다.",
      test_id: "pub_035__section__receipt",
    },
  ],
  actions: [
    {
      id: "queue-donation",
      label: "후원 의향 접수",
      capability: "none",
      operation_id: "private.QueueDonationIntent",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      server_only: true,
      browser_direct: false,
      availability: {
        default: "DISABLED",
        production: {
          state: "UNAVAILABLE",
          reason: "TEST_FIXTURE_ONLY_NO_PRODUCTION_AUTHORITY",
          enabled: false,
        },
        test_only: {
          authority: "TEST_FIXTURE_ONLY_NO_PRODUCTION_AUTHORITY",
          tier: "TEST_FIXTURE",
          lifecycle: "EPHEMERAL",
          enabled: true,
        },
      },
      request_contract: {
        cadence: ["ONE_TIME", "RECURRING"],
        provider: ["TOSS_PAYMENTS", "KAKAO_PAY", "STRIPE"],
        tier_source: "private.GetDonationFixtureOffer.tiers[].tierId",
        offer_binding: ["offerVersionId", "offerDigest"],
        secret_boundary:
          "paymentAuthorizationToken is server-consumed and never enters browser projection, persistence, logs, errors or receipts",
      },
      response_contract: {
        schema: "DonationIntentQueuedReceiptV1",
        status: "QUEUED",
        means_payment_success: false,
      },
    },
    {
      id: "contact",
      label: "문의",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "method-unavailable",
    "receipt",
  ],
  dataOperations: [
    {
      operation_id: "private.GetDonationFixtureOffer",
      api: "billing-gateway-private",
      method: "GET",
      path: "/internal/v1/donation-offers",
      blocking: true,
      request_schema: "GetDonationFixtureOfferRequestV1",
      response_schema: "DonationFixtureOfferV1",
      success_status: 200,
      server_only: true,
      availability: "TEST_ONLY",
      production_status: 503,
      production_service_state: "DISABLED",
      production_state: "UNAVAILABLE",
    },
    {
      operation_id: "private.QueueDonationIntent",
      api: "billing-gateway-private",
      method: "POST",
      path: "/internal/v1/donation-intents",
      blocking: false,
      request_schema: "DonationIntentQueueRequestV1",
      response_schema: "DonationIntentQueuedReceiptV1",
      success_status: 202,
      server_only: true,
      availability: "TEST_ONLY",
      production_state: "UNAVAILABLE",
    },
  ],
} as const satisfies ScreenViewModel;
