import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-008",
  title: "기관 상세",
  route: "/agencies/{agencySlug}",
  archetype: "ENTITY_DETAIL",
  sections: [
    {
      order: 1,
      id: "identity",
      title: "기관 식별 정보",
      component: "RevisionTimeline",
      purpose: "기관 공식명·유형·관할·변경 이력.",
      test_id: "pub_008__section__identity",
    },
    {
      order: 2,
      id: "coverage",
      title: "수집 범위",
      component: "CoverageStatement",
      purpose: "source·기간·누락.",
      test_id: "pub_008__section__coverage",
    },
    {
      order: 3,
      id: "metrics",
      title: "계약 현황 통계",
      component: "StatusAndRevisionHeader",
      purpose: "계약 수·금액·상태 분포와 denominator.",
      test_id: "pub_008__section__metrics",
    },
    {
      order: 4,
      id: "contracts",
      title: "최근 계약",
      component: "StructuredContentSection",
      purpose: "사건 유무와 무관한 계약.",
      test_id: "pub_008__section__contracts",
    },
    {
      order: 5,
      id: "cases",
      title: "공개 사건",
      component: "StatusAndRevisionHeader",
      purpose: "상태별 기록.",
      test_id: "pub_008__section__cases",
    },
    {
      order: 6,
      id: "corrections",
      title: "설명·정정",
      component: "RevisionAndCorrectionPanel",
      purpose: "해소·정정 이력.",
      test_id: "pub_008__section__corrections",
    },
    {
      order: 7,
      id: "methods",
      title: "방법론",
      component: "LongFormArticle",
      purpose: "적용된 규칙과 한계.",
      test_id: "pub_008__section__methods",
    },
  ],
  actions: [
    {
      id: "view-contract",
      label: "계약 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "view-case",
      label: "사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe-agency",
      label: "기관 업데이트 구독",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "getAgency",
      api: "public-api",
      method: "GET",
      path: "/v1/agencies/{agencyId}",
      blocking: true,
      response_schema: "AgencyResponse",
    },
    {
      operation_id: "listAgencyContracts",
      api: "public-api",
      method: "GET",
      path: "/v1/agencies/{agencyId}/contracts",
      blocking: true,
      response_schema: "AgencyContractsPage",
    },
    {
      operation_id: "listAgencyCases",
      api: "public-api",
      method: "GET",
      path: "/v1/agencies/{agencyId}/cases",
      blocking: true,
      response_schema: "AgencyCasesPage",
    },
  ],
} as const satisfies ScreenViewModel;
