import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "CAS-013",
  title: "검토 준비도",
  route: "/internal/cases/{caseId}/review",
  archetype: "WORKSPACE",
  sections: [
    {
      order: 1,
      id: "summary",
      title: "readiness",
      component: "StructuredContentSection",
      purpose: "complete/blocking.",
      test_id: "cas_013__section__summary",
    },
    {
      order: 2,
      id: "gates",
      title: "gate checklist",
      component: "KnownUnknownResponse",
      purpose: "evidence/response/privacy/language.",
      test_id: "cas_013__section__gates",
    },
    {
      order: 3,
      id: "tasks",
      title: "해결 작업",
      component: "StructuredContentSection",
      purpose: "owner·due.",
      test_id: "cas_013__section__tasks",
    },
    {
      order: 4,
      id: "reviews",
      title: "기존 review",
      component: "DecisionReviewPanel",
      purpose: "stale/valid.",
      test_id: "cas_013__section__reviews",
    },
    {
      order: 5,
      id: "snapshot",
      title: "snapshot 생성",
      component: "StructuredContentSection",
      purpose: "included version.",
      test_id: "cas_013__section__snapshot",
    },
  ],
  actions: [
    {
      id: "open-blocker",
      label: "blocker 해결",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "create-snapshot",
      label: "검토 snapshot 생성",
      capability: "review.editorial",
      operation_id: "createReviewSnapshot",
      guard: "all required gates + expected version",
      interaction_kind: "DESTRUCTIVE_CONFIRMATION",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: true,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "getReviewReadiness",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/get-review-readiness",
      blocking: true,
      response_schema: "ReviewReadinessResponse",
    },
    {
      operation_id: "createReviewSnapshot",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/create-review-snapshot",
      blocking: true,
      response_schema: "createReviewSnapshotReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
