import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "RSP-004",
  title: "첨부자료",
  route: "/respond/attachments",
  archetype: "GUIDED_FORM",
  sections: [
    {
      order: 1,
      id: "guidance",
      title: "파일 안내",
      component: "StatusAndRevisionHeader",
      purpose: "형식·크기·민감정보.",
      test_id: "rsp_004__section__guidance",
    },
    {
      order: 2,
      id: "upload",
      title: "업로드",
      component: "StructuredContentSection",
      purpose: "progress·checksum.",
      test_id: "rsp_004__section__upload",
    },
    {
      order: 3,
      id: "metadata",
      title: "문서 설명",
      component: "StructuredContentSection",
      purpose: "날짜·설명·공개 분류.",
      test_id: "rsp_004__section__metadata",
    },
    {
      order: 4,
      id: "scan",
      title: "검사 상태",
      component: "StatusAndRevisionHeader",
      purpose: "pending/clean/rejected.",
      test_id: "rsp_004__section__scan",
    },
    {
      order: 5,
      id: "files",
      title: "첨부 목록",
      component: "DataCollection",
      purpose: "remove/replace.",
      test_id: "rsp_004__section__files",
    },
  ],
  actions: [
    {
      id: "select-file",
      label: "파일 선택",
      capability: "none",
      local_only: true,
      persistence: "none",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "remove-file",
      label: "파일 제거",
      capability: "none",
      operation_id: "deleteResponseAttachment",
      interaction_kind: "COMMAND",
      assurance_level: "SCOPED_TOKEN",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "next",
      label: "제출 전 검토",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "createResponseAttachmentUpload",
      api: "submission-api",
      method: "POST",
      path: "/v1/response-session/attachments",
      blocking: true,
      response_schema: "createResponseAttachmentUploadReceipt",
    },
    {
      operation_id: "finalizeResponseAttachment",
      api: "submission-api",
      method: "POST",
      path: "/v1/response-session/attachments/{attachmentId}:finalize",
      blocking: true,
      response_schema: "finalizeResponseAttachmentReceipt",
    },
    {
      operation_id: "deleteResponseAttachment",
      api: "submission-api",
      method: "DELETE",
      path: "/v1/response-session/attachments/{attachmentId}",
      blocking: true,
      response_schema: "deleteResponseAttachmentReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
