import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-002",
  title: "통합 검색",
  route: "/search",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "query",
      title: "검색어",
      component: "UnifiedSearch",
      purpose: "기관·업체·계약·사건 검색과 유형·기간·공개 상태 파셋.",
      test_id: "pub_002__section__query",
    },
    {
      order: 2,
      id: "results",
      title: "검색 결과",
      component: "DataCollection",
      purpose: "일치 항목·공개 상태·자료 기준일과 검색 범위 각주.",
      test_id: "pub_002__section__results",
    },
  ],
  actions: [
    {
      id: "submit-search",
      label: "검색",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-result",
      label: "검색 결과 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "clear",
      label: "검색 초기화",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "download-csv",
      label: "CSV 내려받기",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "download-jsonl",
      label: "JSONL 내려받기",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: [
    "awaiting-query",
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
  ],
  dataOperations: [
    {
      operation_id: "searchPublicRecords",
      api: "public-api",
      method: "GET",
      path: "/v1/search",
      blocking: true,
      response_schema: "PublicRecordsSearchResultPage",
    },
    {
      operation_id: "downloadPublicSearchRecords",
      api: "public-api",
      method: "GET",
      path: "/v1/search/download",
      blocking: false,
      response_schema: "PublicSearchDownload",
    },
  ],
} as const satisfies ScreenViewModel;
