import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-002",
  title: "통합 검색",
  route: "/search",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "query",
      title: "검색어",
      component: "UnifiedSearch",
      purpose: "검색 범위와 예시를 제공한다.",
      test_id: "pub_002__section__query",
    },
    {
      order: 2,
      id: "types",
      title: "객체 유형",
      component: "RevisionAndCorrectionPanel",
      purpose: "사건·계약·기관·업체·방법론·정정을 구분한다.",
      test_id: "pub_002__section__types",
    },
    {
      order: 3,
      id: "results",
      title: "검색 결과",
      component: "UnifiedSearch",
      purpose: "일치 필드와 상태·freshness를 표시한다.",
      test_id: "pub_002__section__results",
    },
    {
      order: 4,
      id: "coverage",
      title: "검색 범위",
      component: "UnifiedSearch",
      purpose: "indexing 지연과 source coverage를 표시한다.",
      test_id: "pub_002__section__coverage",
    },
  ],
  actions: [
    {
      id: "submit-search",
      label: "검색",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "filter-type",
      label: "유형 필터",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "clear",
      label: "검색 초기화",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "searchPublicRecords",
      api: "public-api",
      method: "GET",
      path: "/v1/search",
      blocking: true,
      response_schema: "PublicRecordsSearchResultPage",
    },
  ],
} as const satisfies ScreenViewModel;
