import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-003",
  title: "공개 사례",
  route: "/cases",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "목록 범위",
      component: "StatusAndRevisionHeader",
      purpose: "공개 확정 개정본 한정 사례 범위.",
      test_id: "pub_003__section__scope",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "공개 상태·기관·업체·방법론·기간·소명·정정 조건.",
      test_id: "pub_003__section__filters",
    },
    {
      order: 3,
      id: "results",
      title: "결과",
      component: "DataCollection",
      purpose: "관찰 사실·미확인·상태·자료 기준일을 포함한 사례 대장.",
      test_id: "pub_003__section__results",
    },
    {
      order: 4,
      id: "pagination",
      title: "페이지 이동",
      component: "DataCollection",
      purpose: "cursor와 결과 변경을 접근 가능하게 알린다.",
      test_id: "pub_003__section__pagination",
    },
  ],
  actions: [
    {
      id: "apply-filter",
      label: "필터 적용",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-case",
      label: "사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe-filter",
      label: "이 조건 구독",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "download-csv",
      label: "CSV 내려받기",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "download-jsonl",
      label: "JSONL 내려받기",
      capability: "none",
      interaction_kind: "DOWNLOAD",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listPublicCases",
      api: "public-api",
      method: "GET",
      path: "/v1/cases",
      blocking: true,
      response_schema: "PublicCasesPage",
    },
    {
      operation_id: "downloadPublicCases",
      api: "public-api",
      method: "GET",
      path: "/v1/cases/download",
      blocking: false,
      response_schema: "PublicCasesDownload",
    },
  ],
} as const satisfies ScreenViewModel;
