import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "PUB-003",
  title: "공개 사례",
  route: "/cases",
  archetype: "SEARCH_INDEX",
  sections: [
    {
      order: 1,
      id: "scope",
      title: "목록 범위",
      component: "StatusAndRevisionHeader",
      purpose: "공개된 revision만 포함함을 설명한다.",
      test_id: "pub_003__section__scope",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "상태·기관 유형·지역·방법론·기간·소명 상태.",
      test_id: "pub_003__section__filters",
    },
    {
      order: 3,
      id: "results",
      title: "결과",
      component: "StatusAndRevisionHeader",
      purpose: "관찰 사실·미확인·상태·freshness를 포함한다.",
      test_id: "pub_003__section__results",
    },
    {
      order: 4,
      id: "pagination",
      title: "페이지 이동",
      component: "DataCollection",
      purpose: "cursor와 결과 변경을 접근 가능하게 알린다.",
      test_id: "pub_003__section__pagination",
    },
  ],
  actions: [
    {
      id: "apply-filter",
      label: "필터 적용",
      capability: "none",
      local_only: true,
      persistence: "url",
      interaction_kind: "COMMAND",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "open-case",
      label: "사건 보기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "subscribe-filter",
      label: "이 조건 구독",
      capability: "none",
      guard:
        "verified subscription destination + explicit consent + rate-limit clearance",
      operation_id: "createSubscription",
      preset: {
        scope_type: "QUERY",
      },
      interaction_kind: "COMMAND",
      assurance_level: "ANONYMOUS_PROOF",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: ["loading", "success", "empty", "partial", "stale", "error"],
  dataOperations: [
    {
      operation_id: "listPublicCases",
      api: "public-api",
      method: "GET",
      path: "/v1/cases",
      blocking: true,
      response_schema: "PublicCasesPage",
    },
    {
      operation_id: "createSubscription",
      api: "submission-api",
      method: "POST",
      path: "/v1/subscription-session",
      blocking: false,
      response_schema: "createSubscriptionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
