import type { ScreenViewModel } from "@gurine/ui";

export const screen = {
  id: "COR-001",
  title: "정정 Queue",
  route: "/internal/corrections",
  archetype: "QUEUE",
  sections: [
    {
      order: 1,
      id: "urgent",
      title: "긴급 queue",
      component: "DataCollection",
      purpose: "privacy/identity/legal.",
      test_id: "cor_001__section__urgent",
    },
    {
      order: 2,
      id: "filters",
      title: "필터",
      component: "UnifiedSearch",
      purpose: "type/state/source/SLA.",
      test_id: "cor_001__section__filters",
    },
    {
      order: 3,
      id: "requests",
      title: "요청 목록",
      component: "DataCollection",
      purpose: "target·requester class·impact.",
      test_id: "cor_001__section__requests",
    },
    {
      order: 4,
      id: "assignment",
      title: "배정",
      component: "StructuredContentSection",
      purpose: "owner.",
      test_id: "cor_001__section__assignment",
    },
  ],
  actions: [
    {
      id: "open-correction",
      label: "정정 작업 열기",
      capability: "none",
      interaction_kind: "NAVIGATION",
      assurance_level: "NONE",
      step_up_required: false,
      confirmation_required: false,
      local_only: true,
    },
    {
      id: "assign",
      label: "담당자 배정",
      capability: "publication.correct",
      operation_id: "assignCorrection",
      interaction_kind: "COMMAND",
      assurance_level: "ACTIVE_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
    {
      id: "triage",
      label: "초기 분류",
      capability: "publication.correct",
      operation_id: "triageCorrection",
      interaction_kind: "COMMAND",
      assurance_level: "RECENT_SESSION",
      step_up_required: false,
      confirmation_required: false,
    },
  ],
  states: [
    "loading",
    "success",
    "empty",
    "partial",
    "stale",
    "error",
    "unauthorized",
    "forbidden",
    "conflict",
  ],
  dataOperations: [
    {
      operation_id: "listCorrectionQueue",
      api: "control-api",
      method: "GET",
      path: "/v1/internal/queries/list-correction-queue",
      blocking: true,
      response_schema: "CorrectionQueuePage",
    },
    {
      operation_id: "assignCorrection",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/assign-correction",
      blocking: false,
      response_schema: "assignCorrectionReceipt",
    },
    {
      operation_id: "triageCorrection",
      api: "control-api",
      method: "POST",
      path: "/v1/internal/commands/triage-correction",
      blocking: true,
      response_schema: "triageCorrectionReceipt",
    },
  ],
} as const satisfies ScreenViewModel;
